### ISSUE TITLE
Custom HTML rendering

### ISSUE THREAD

**Issue by thomaslevesque** [benweet/stackedit#1000]
Is there a way to customize how the markdown is rendered to HTML? Especially for publishing.

I want to use StackEdit to write posts for my WordPress blog. I use the SyntaxHighlighter Evolved WP plugin to render code blocks. To use this plugin, I just paste the raw code between `[sourcecode][/sourcecode]` tags, without any prior formatting. But when StackEdit publishes my post to Wordpress, it does its own HTML formatting, so I can no longer use the `[sourcecode]` tag.

Could it be done with an extension? Is there some kind of callback like `function onRenderingCodeBlock(code, language)`?

**Comment by benweet** [comment]
You can do that with templates and custom handlebars helpers in the v5.

**Comment by haiy** [comment]
<span style="background:yellow;color:red"><span sty></span>
