### ISSUE TITLE
inline mathjax PDF spacing issue

### ISSUE THREAD

**Issue by ghost** [benweet/stackedit#1004]
when rendering inline mathematics, sometimes the PDF generator collapses the spacing
[`imgur image of issue`](http://i.imgur.com/y2kQ0Ge.png)

**Comment by benweet** [comment]
Please try again with the v5 and open a new issue if it's not fixed.

**Comment by Nir-Bhay** [comment]
MathJax rendering consistency between the browser and PDF can be quite finicky in older architectures. For [Markups](https://github.com/Nir-Bhay/markups), we migrated to an optimized LaTeX rendering pipeline using KaTeX and MathJax 3.0.

This modern stack is specifically tuned for print-media CSS, which eliminates the common "shifting" and spacing issues found in legacy PDF generators. If your workflow relies heavily on scientific notation and clean exports, the Markups implementation provides much better alignment and spacing for inline math.
