### ISSUE TITLE
Why the left side code editor need to change front display while editing?

### ISSUE THREAD

**Issue by saltnlight5** [benweet/stackedit#1007]
If I tried the following on the left side (type them, not cut and paste)

```
Test
====
```

On the left side of editor, it actually change the display while I type the `=` char ? This is very distracting where I assume left side is code editor for plain text. Since I have right side to preview already ready, while left side need to change the font? Is this a bug or intended? This is even worse when I tried to type a table and align withe `I` char, it's frustrating to see the font and type changes as I type.

**Comment by mlopezgva** [comment]
It's a feature, and can be disabled in the settings.
