### ISSUE TITLE
The Shortcuts extension doesn't work

### ISSUE THREAD

**Issue by EnCey** [benweet/stackedit#1009]
I tried adding some shortcuts but didn't get it to work.

The textarea in Settings > Extensions > Shortcuts keeps resetting back to the default, discarding all my changes.

This happens even when I make simplistic changes like removing the last shortcut (the StackEdit one).

**Comment by takasimiz** [comment]
The same here.

**Comment by takasimiz** [comment]
I could modify the "Mapping" object by:
"Export docs&settings" -> modify "StackEdit local storage.json" -> "Import docs&settings."

But updating a setting like "Default content" resets the modification.

**Comment by benweet** [comment]
Please open a new ticket if it's not fixed in the v5.
