### ISSUE TITLE
Can't include multi-word tags in front matter when publishing to WordPress

### ISSUE THREAD

**Issue by thomaslevesque** [benweet/stackedit#1011]
I have a front matter like this:

```

---
title: Tuples en C# 7
tags: C# 7, tuple, Visual Studio
date: 2016-07-28 01:00:00
published: false

---
```

When I publish to WordPress, the post is created with these tags:
- C#
- 7
- tuple
- Visual
- Studio

I tried to surround the tags with double-quotes, but it didn't solve the problem (the double-quotes are just treated as any other characters).

Only the commas should be used to separate the tags, not whitespace.

**Comment by benweet** [comment]
Should be fixed in the v5.
