### ISSUE TITLE
Maybe we need more themes?

### ISSUE THREAD

**Issue by Ruanxingzhi** [benweet/stackedit#1012]
Now , the editor Stackedit`Beta 4`  has only 4 themes. Maybe not enough...

A markdown editor names "Evernote":
![Evernote](http://i1.buimg.com/4851/9477303ce3483e1b.png)

Stackedit:
![Stackedit Beta 4](http://i1.buimg.com/4851/8b65f5d4b8d3daeb.png)

**Comment by benweet** [comment]
Closing this. Themes will be supported soon in the v5.
