### ISSUE TITLE
 Publishing to github organizaition repo

### ISSUE THREAD

**Issue by Ventto** [benweet/stackedit#1015]
I cannot publish to my organizations' repo. 
I get the following error message: "Could not publish on Github"

I have found the [old issue](https://github.com/benweet/stackedit/issues/233) on this point.

> That would be:
> 
> Repository: RepoName
> Username: OrganizationName
> Branch: master
> File Path: docs/document.html
> Format: HTML
> 
> I've just published a new beta (3.99.14) that makes things easier. Just put whatever url in repository field (https://stackedit-beta.herokuapp.com/).
> -- @benweet : https://github.com/benweet/stackedit/issues/233

At this time, there was a field 'Username' in a previous version that could solve the problem and apparently a new beta v3.99.14 troubleshot it using directly the repo's URL.

I have checked my repo's settings. But nothing to report.

A lead ?

**Comment by benweet** [comment]
Can you try again with the v5 and open a new ticket if it's not fixed?
