### ISSUE TITLE
MathJax script with attribute id MathJax-Element-000 colliding with each other

### ISSUE THREAD

**Issue by Namnamseo** [benweet/stackedit#1016]
I'm using StackEdit to post to my blog. First, I write something I would like to. Then I use `Export to disk -> As HTML` feature, download the HTML file, copy the whole content and paste it into my blog's `New Entry`, which supports HTML.
It works pretty well, except one day some TeX jammed in my blog.

I found that each MathJax object has some numbers in their `<script>` tag's `id` attribute. And I think StackEdit numbers them.
For example, some element would look like this:

``` HTML
<script id="MathJax-Element-188" type="math/tex">
\LaTeX=L^{A} \cdot T_{E} \cdot X \\ \textrm{Cute article.}
</script>
```

Now their numbers(188 in example above) are serial(increasingly assigned), and thus wouldn't collide at all.
But the problem is, I wrote some documents with my old comptuer, with a whole different StackEdit view (different documents, settings, ...). So numbers of MathJax objects from my old computer and from my new computer collided, aggregating with each other on my blog. You can see images below. Unreadable characters on the back are Korean.

![example](http://i.imgur.com/0FuNo0f.png)

I certainly didn't mean that happily floating 2^32. I found out that those with same numbers(same `<script> id`s) gathered together.

Again, it's not a big deal now because numbers won't collide much now, but I hope there's a way to prefix each ids with some (possibly) unique name.
If there's anything wrong with this article, please let me know. Thanks.

**Comment by benweet** [comment]
MathJax is not used anymore in the v5.
