### ISSUE TITLE
developer: npm install error (git://github.com/benweet/gulp-inject.git)

### ISSUE THREAD

**Issue by ardimedia** [benweet/stackedit#1017]
when I run `npm install` I get the following messages

`
npm ERR! git clone --template=C:\Users\Harry\AppData\Roaming\npm-cache_git-remotes_templates --mirror git://github.com/benweet/gulp-inject.git C:\Users\Harry\AppData\Roaming\npm-cache_git-remotes\git-github-com-benweet-gulp-inject-git-8bd702d143a578e3b44290d82612ab808ee17281-6cfb826f: Cloning into bare repository 'C:\Users\Harry\AppData\Roaming\npm-cache_git-remotes\git-github-com-benweet-gulp-inject-git-8bd702d143a578e3b44290d82612ab808ee17281-6cfb826f'...

npm ERR! git clone --template=C:\Users\Harry\AppData\Roaming\npm-cache_git-remotes_templates --mirror git://github.com/benweet/gulp-inject.git C:\Users\Harry\AppData\Roaming\npm-cache_git-remotes\git-github-com-benweet-gulp-inject-git-8bd702d143a578e3b44290d82612ab808ee17281-6cfb826f: fatal: unable to connect to github.com:

npm ERR! git clone --template=C:\Users\Harry\AppData\Roaming\npm-cache_git-remotes_templates --mirror git://github.com/benweet/gulp-inject.git C:\Users\Harry\AppData\Roaming\npm-cache_git-remotes\git-github-com-benweet-gulp-inject-git-8bd702d143a578e3b44290d82612ab808ee17281-6cfb826f: github.com[0: 192.30.253.112]: errno=Invalid argument

npm ERR! Windows_NT 10.0.14393

npm ERR! argv "C:\Program Files (x86)\Nodist\v-x64\6.5.0\node.exe" "C:\Program Files (x86)\Nodist\npmv\3.10.6\bin\npm-cli.js" "install"

npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Harry\AppData\Roaming\npm-cache_git-remotes_templates --mirror git://github.com/benweet/gulp-inject.git C:\Users\Harry\AppData\Roaming\npm-cache_git-remotes\git-github-com-benweet-gulp-inject-git-8bd702d143a578e3b44290d82612ab808ee17281-6cfb826f

npm ERR! Cloning into bare repository 'C:\Users\Harry\AppData\Roaming\npm-cache_git-remotes\git-github-com-benweet-gulp-inject-git-8bd702d143a578e3b44290d82612ab808ee17281-6cfb826f'...

**npm ERR! fatal: unable to connect to github.com:**

**npm ERR! github.com[0: 192.30.253.112]: errno=Invalid argument**
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\CODE\Samples\stackedit-samples\stackedit\npm-debug.log
`
Any ideas?

**Comment by chapery** [comment]
me too.

**Comment by benweet** [comment]
Should be fixed in the v5.
