### ISSUE TITLE
Unicode characters with multiple codepoints not rendering correctly in Firefox

### ISSUE THREAD

**Issue by TheSilvus** [benweet/stackedit#1018]
Unicode "compound" character don't display correctly in the edit window, but appear to be right in the "result" window. 
It only happens in Firefox, I tried it in Google Chrome and it worked fine.
Everything works fine in other text fields, i.e. the Github Issue editor displays the text fine.

I am using the Firefox ESR, currently on Version 45.3.0. I am currently not able to test with a more up to date version.

Example text:
t̲e̲s̲t̲
e̞
T̴̹̥̯̩̮̟e̹̗̘͎͎̯͍s͉t̗̜͖̭̙̰͇

![screenshot_16](https://cloud.githubusercontent.com/assets/18658672/18419078/d2ca4028-7853-11e6-8777-2ec00d276dbd.png)

**Comment by benweet** [comment]
Please open a new ticket if it's not fixed in the v5.
