### ISSUE TITLE
publish to github error

### ISSUE THREAD

**Issue by aiyodaxue** [benweet/stackedit#1019]
@benweet 
hi.
I tried to publish a document to a github repo. but it always failed.  the error message is `could not publish on github`.  I try to change the repo link from https to ssh, and ssh to https. but failed too.

this is my config

![stackediterror](https://cloud.githubusercontent.com/assets/22340455/18703851/46c0cc2c-801a-11e6-8016-d6be12c97a31.png)

Thanks.

**Comment by benweet** [comment]
Please open a new ticket if it's not fixed in the v5.
