### ISSUE TITLE
Live collaboration?

### ISSUE THREAD

**Issue by working-name** [benweet/stackedit#1020]
Hello there,

I was looking at the app before deciding to sponsor it and saw some live collaboration capabilities which looked good. In reality however, this is nothing more than a glorified diff system which messes up the formatting by inserting some huge red `//` around the changes. You can remove them but then the formatting is a mess and you end up reconciling differences manually, which is not very effective.

Is this the current capability for collaboration or have I done something to break it?

Thanks!

**Comment by benweet** [comment]
You won't see any red `//` in the v5. But yes, there is no real time collaboration, only a periodic diff/merges mechanism.
