### ISSUE TITLE
Can't type Chinese pinyin correctly

### ISSUE THREAD

**Issue by littlebeandog** [benweet/stackedit#1023]
## Issue

If I start to type in a Chinese word from the begining of a line, the cursor will jump to the upper line.
## Detail

For example
This is what i want

> 你好
> 世界

So i type in with PINYIN `nihao EOL shijie`.
Everything ok with the first word 你好.
But when i print in the very **first** PINYIN of the second word 世界(which is 's') in a new line, i got something like this:

> 你好
> s

And the **cursor** is now after 你好.

This always happens if I type in a Chinese word from the **begining of a new line** , except the first line.
## Environment

This happens in:

> System : Ubuntu 16.04 LTS(64-bit)
> Explorer : Chromium 2.0.2743.116
> IME : sougou PINYIN v2.0.0.0078

I dont know if these infomations may help somehow =w=
#### Thank you for your epic work and sharing. I'm a noob of coding but please contact me if I can do anything help fix this problem

> 42shazi@gmail.com

**Comment by CJSoldier** [comment]
I got similar problem with stackedit 4.3.14 on ubuntu16.04.  
The cursor jumped to the end of previous line as soon as I typed the first character in chinese.
But if the line I typed begins with an English charater, it won't jump.

It works well on win7.

**Comment by CJSoldier** [comment]
I just tested it on ubuntu16.04 and win7, both works well especially on win7. I mean it does not work smoothly on ubuntu chrome.
I used stackedit 4.3.14. 

I got the similar problem as you when I wrapped stackedit with electron.But I don't think it's a stackedit bug.
The cursor jumped to the end of previous line as soon as I typed the first character in Chinese. It only occurs on ubuntu16.04.

**Comment by benweet** [comment]
Please try with the v5 and create a new ticket if it's not fixed. Thanks
