### ISSUE TITLE
generated table does not render the same in the editor and on stackoverflow

### ISSUE THREAD

**Issue by romain-dartigues** [benweet/stackedit#1027]
The table generated on stackedit is not compatible with stackoverflow markdown.
I'm opening this bug even if this might be more for stackoverflow than here...
Maybe the fix would be a "Stack Exchange" compatibility mode (haven't seen a button).

Problematic Markdown sample:

```
|                   |  `>` | `\|` |     | `"` | `'` | `>-` | `>+` | `\|-`| `\|+`|
 -------------------|:----:|:----:|:---:|:---:|:---:|:----:|:----:|:----:|:----:|
| Trailing spaces   | Kept | Kept |     |     |     | Kept | Kept | Kept | Kept |
```

Stackedit and expected output:
![stackedit](https://cloud.githubusercontent.com/assets/393859/19019701/7a9eca2a-8890-11e6-909e-81855a4d56c5.png)

Stackoverflow and !@#:
![stackoverflow](https://cloud.githubusercontent.com/assets/393859/19019702/7aa0945e-8890-11e6-8168-09e560dce6c6.png)

**Comment by mlopezgva** [comment]
Just by chance, try to name the first column...

**Comment by romain-dartigues** [comment]
Sorry, should have checked before posting, this is indeed a SE problem : http://meta.stackexchange.com/questions/73566/is-there-markdown-to-create-tables

Awesome job you did, keep up ;^)
