### ISSUE TITLE
Multiline notes and loops break UML sequence rendering

### ISSUE THREAD

**Issue by O1O1O1O** [benweet/stackedit#1030]
The following sequences don't render

``` sequence
A->B: start_step
note  over A
  my note
end
B->A: end_step
```

and

``` sequence
A->B: start
loop myloop
    A->B: stuff
end
B->A: final_step
```

If I reduce the note to a single line it works, like so:

``` sequence
A->B: start_step
note  over A: my note
B->A: end_step
```

but there is nothing I can do to the `loop` to make that work.

**Comment by benweet** [comment]
Mermaid is now the only syntax supported in the v5.
