### ISSUE TITLE
Render nested lists without nesting limit

### ISSUE THREAD

**Issue by Sporky023** [benweet/stackedit#1031]
The following markdown:

```
* hello
  * deep
    * nesting
```

Renders like this:

![how deeply nested lists render](http://imgur.com/nEs21Ml.jpg)

This isn't very useful, and it would be great if it would continue to add indentation to the rendered lists as the indentation in the markdown increases.

For reference, here's how Github renders similar markdown source:
- hello
  - deep
    - nesting
      - my
        - old
          - friend

edit:  I did a cursory look through the settings to see if there was a checkbox that toggled this behavior, but I didn't see anything.  I do note that there's an html template that references a CSS file.  I will fall back on that if I must but it would be nice if this were simply how it worked anyway.

**Comment by bulrush15** [comment]
I made a Stackedit help [forum here](https://groups.google.com/forum/#!forum/stackedit/new). I hope we can help each other out. The author seems very busy.

**Comment by benweet** [comment]
Should be fixed in v5.
