### ISSUE TITLE
Allow numbered lists to start at something other than 1

### ISSUE THREAD

**Issue by Daniel-Hug** [benweet/stackedit#1032]
This is something that Stackoverflow has already implemented. See this meta question: [Can't start a numbered list on a number other than 1](http://meta.stackexchange.com/questions/137077/cant-start-a-numbered-list-on-a-number-other-than-1)

Here's an example. These are two separate lists, but the latter should start at 3 when rendered rather than 1:
```md
#### Produce
1. lettuce
2. kale

#### Meat
3. bacon
4. chicken
```

**Comment by bulrush15** [comment]
A workaround is to do manual lists in markdown for the lists after the first one. Here's some markdown. 

#### Produce
1. lettuce
2. kale

#### Meat
3\. bacon
4\. chicken

The backslash period prevents the markdown from getting converted to to a list. This is also handy for lists of dates. 

2004\. This happened. 

2005\. That happened.

**Comment by benweet** [comment]
Should be fixed in the v5 (https://stackedit.io/app).
