### ISSUE TITLE
Encountering PDF Error when Export to PDF

### ISSUE THREAD

**Issue by TonyVT** [benweet/stackedit#1037]
Hello,

After exporting to PDF in StackEdit, I'm encountering the following exception message:

**_This page contains the following errors:
error on line 1 at column 1: Document is empty
error on line 1 at column 1: Encoding error
Below is a rendering of the page up to the first error._**

I tried to reduce the file that I was exporting to just a few lines of text with Markdown code. Same result, I encountered the exception message stated above.

I purchased a sponsorship so that I could take advantage of the Export to PDF option.

Any suggestions would be most appreciated.

Kind regards,
Tony Ventura
www.tonyventura.com

**Comment by benweet** [comment]
Please provide a markdown sample to reproduce the issue.

**Comment by benweet** [comment]
Not reproduced.
