### ISSUE TITLE
StackEdit - Login to Resume Document Management?

### ISSUE THREAD

**Issue by TonyVT** [benweet/stackedit#1038]
I'm a new user of StackEdit. I was working on a few documents, created a folder to store those documents, and exited my browser session. Is there any way to get back to manage the documents I was working on? There doesn't appear to be a login of any type.

Any advice on how I can resume my work at a later time would be most appreciated.

Thank you,
Tony

**Comment by benweet** [comment]
Please try the new login feature in the v5 (https://stackedit.io/app).

**Comment by rubaboo** [comment]
Could you provide some explanation about what this login feature provides. I did a "reset application", then signed back in and all my files were back. Does that mean I don't really need to sync them to Drive/Gist etc, if I don't have collaborators? Or can the files still be gone if I clear browser cache/cookies/whatnot? Where do those files reside? Inside the profile? (Using Firefox Quantum here.)

Say I can sync every file to Gist, so they are not lost. What about the folder structure in the Explorer pane, what action can cause me to lose that?

Thanks.
