### ISSUE TITLE
Cannot export to pdf

### ISSUE THREAD

**Issue by SuperBlee** [benweet/stackedit#1041]
Hello, I am a sponsor of your product. But when I am trying to export as PDF, I receive the following messages:

> This page contains the following errors:
>
> error on line 1 at column 1: Document is empty
> error on line 1 at column 1: Encoding error
> Below is a rendering of the page up to the first error.

What should I do?

**Comment by benweet** [comment]
Can you share a markdown sample to reproduce the issue ?

**Comment by benweet** [comment]
Not reproduced.
