### ISSUE TITLE
Error on monetizejs, cannot read property 'postMessage' of null

### ISSUE THREAD

**Issue by walkerlangley** [benweet/stackedit#1042]
I got the following error after submitting payment and when trying to sign-in (I used nativefier to create a desktop app), `Uncaught TypeError: Cannot read property 'postMessage' of null(…)`, line 8 `origin && window.opener.postMessage(message, origin);`

**Comment by philip-ulrich** [comment]
Is this still an issue for you? As another use that just submitted payment for sponsorship... I did not run into this.

**Comment by benweet** [comment]
Sorry, there is no plan for native app support I'm afraid.
