### ISSUE TITLE
Document list only works once in Viewer mode

### ISSUE THREAD

**Issue by piedar** [benweet/stackedit#1043]
Chrome 54 on Windows 7 x64.

1. Click "Open in viewer" in the bottom right.
2. Click "Select document" in the top right => document list appears as expected.
3. Click "Select document" to collapse document list.
4. Click "Select document" again => document list is empty!

When the list is empty, the icon is in the wrong place on the far right of the window:

![image](https://cloud.githubusercontent.com/assets/1828312/20438565/2015e56e-ad86-11e6-96e3-34bae40aa49c.png)

**Comment by benweet** [comment]
Closing this. Should be fixed in the v5 (https://stackedit.io/app).
