### ISSUE TITLE
couchdb + self-signed SSL certificate

### ISSUE THREAD

**Issue by g33kdad** [benweet/stackedit#1045]
Hi,

I'm super noob about this stuff. I am trying to setup a couchdb instance to store/sync my stackedit.io documents.

I have the server setup and can access the couchdb instance on via my browser and I have created a new database with the <code>curl -X PUT</code> command. However, when trying to "insert the design documents" (per this instruction https://github.com/benweet/stackedit/blob/master/doc/couchdb-setup.md), node throws an error (i think) because I am using a self-signed ssl cert.

is there a fault-tolerant way to adjust the code in setup.js to account for a self-signed cert? 

thanks,
matt

**Comment by dtu-compute** [comment]
This fork https://github.com/dtu-compute/dtu-enote-stackedit have been modified to have working https and credentials for couchdb. The fork is not indented for general purpose, but the couchdb fixes are.

**Comment by diazona** [comment]
I'm having the same problem. Using a different fork of the StackEdit code is not an acceptable solution for me because I'm working with stackedit.io.

I suppose using a non-self-signed certificate would work but that's a lot of trouble to go through just to get this integration working.

**Comment by diazona** [comment]
Actually I just found [a workaround](http://stackoverflow.com/a/30438204/56541)

    NODE_TLS_REJECT_UNAUTHORIZED=0 node setup.js https://example.com/documents

This help out anyone else stumbling across this bug report with the same issue, but given how common this situation is, it would be nice to address it in StackEdit. (If nothing else, a mention in the documentation would be great.)

**Comment by benweet** [comment]
Support for CouchDB has been dropped in the v5 (https://stackedit.io/app), at least for now.
