### ISSUE TITLE
Still can't get custom CSS to work on Dropbox

### ISSUE THREAD

**Issue by bulrush15** [benweet/stackedit#1046]
I put a custom CSS file in Dropbox which is in my Stackedit folder, and the file is 'markdown.css'. 

In Stackedit I went to Menu, Settings, Advanced, and I put this in the default template (partial html): 
```
<title><%= documentTitle %></title>
<link rel="stylesheet" href="https://stackedit.io/res-min/themes/base.css" />
<style>
h1, h2, h3, h4, h5 {margin-top: 5px;
margin: 5pt 0 5pt 0;
padding: 0;
}
h1 {font-height: 130%;
}
h2 {font-height: 110%;
}
</style>
```

I also tried this in the default template which didn't work (partial html): 
```
<title><%= documentTitle %></title>
<link rel="stylesheet" href="https://stackedit.io/res-min/themes/base.css" />
<link rel="stylesheet" href="https://www.dropbox.com/s/oypb46pyzom30v0/markdown.css?dl=0" />
```

When I use Firefox Inspector on the preview pane on the right the CSS attributes are coming from base.css. 

How do I get the custom CSS?

**Comment by benweet** [comment]
Doesn't look like a bug. Probably the file `https://www.dropbox.com/s/oypb46pyzom30v0/markdown.css?dl=0` is not served as a raw text/css content.
