### ISSUE TITLE
Suggestion: add sw-cache to dependencies and make part of gulp "dist" build process

### ISSUE THREAD

**Issue by bonatoc** [benweet/stackedit#1047]
sw-cache provides a [simple, effective gulp implementation example](https://codelabs.developers.google.com/codelabs/sw-precache/#3).

I see stackedit knows how to handle offline, but aren't [service workers the way to go from now on](https://www.youtube.com/watch?v=cmGr0RszHc8)? 
Does stackedit have a sort of API for storing into localStorage? Do you think there's much work in refactoring? I see some serialized files when inspecting, so I assume it's practically the same logic, instead of relying on the (probably non-existing at the time of engineering) SW API.

Does it make sense?

**Comment by benweet** [comment]
Using SW in the v5 (https://stackedit.io/app).
