### ISSUE TITLE
Suggestion - less boxy sidebar 

### ISSUE THREAD

**Issue by samrose3** [benweet/stackedit#1048]
The current sidebar seems a bit boxy and over-styled. Thought I'd suggest maybe simplifying.

### Current 
![stackedit_ _editor](https://cloud.githubusercontent.com/assets/11774595/20834674/92417c00-b864-11e6-8c76-4a401165af4a.png)

### Suggested Revision
![stackedit_ _editor](https://cloud.githubusercontent.com/assets/11774595/20834658/8053546e-b864-11e6-9168-3de4a917a6a0.png)

**Comment by benweet** [comment]
Closing this. The design has changed in the v5 (https://stackedit.io/app).
