### ISSUE TITLE
Can't see Preview on Firefox 50.0.2

### ISSUE THREAD

**Issue by ryanttb** [benweet/stackedit#1049]
Even in a Private Window with a new document, the text is there but the Preview is not.

http://oi65.tinypic.com/j8o1lh.jpg

Some errors in console:

* Init listener threw an exception. Continuing. Error: Module 'WrappedSelection' not supported   main.js:2759:57
* TypeError: c.getSelection is not a function    main.js:23615:148

**Comment by benweet** [comment]
Closing this. Please open a new ticket if it's not fixed in the v5 (https://stackedit.io/app).
