### ISSUE TITLE
umlDiagrams.js - include `theme` as setting

### ISSUE THREAD

**Issue by gnimmelf** [benweet/stackedit#1050]
[diagram.drawSVG](https://github.com/benweet/stackedit/blob/82ba08fbfdc0c64036453d6fab24027565e5409c/public/res/extensions/umlDiagrams.js#L45) has `theme` hardcoded to `simple`.

Could it grab it from the settings so I can use `hand` theme? (Assuming theme switching works as-is...)

Cheers for en excellent piece of work!

**Comment by benweet** [comment]
Closing this. Support for UML diagrams will be available soon in the v5 (https://stackedit.io/app).
