### ISSUE TITLE
409 conflict with own couchdb

### ISSUE THREAD

**Issue by jmatsushita** [benweet/stackedit#1052]
Hi there,

I've just tried to use my own couchdb instance and the couchapp is installed correctly AFAICT, however when syncing I get a popup `409 document update conflict` and the POST shows 

![image](https://cloud.githubusercontent.com/assets/356097/21138988/037ec830-c131-11e6-89eb-d3ca793bd2cf.png)

Inspecting the payload it shows that it's containing a revision number which according to the CouchDB documentation, shouldn't be including in the initial POST to create a document.
 
![image](https://cloud.githubusercontent.com/assets/356097/21138562/e75e29ae-c12e-11e6-88d7-ab6d42d3ff2c.png)

This also happens after I try creating a New Document.

Strangely, if I do this with the smileupps.com default couch it doesn't set the `_rev`

![image](https://cloud.githubusercontent.com/assets/356097/21139054/6307ae5c-c131-11e6-8c4a-876a2e0fd5b2.png)

**Comment by jmatsushita** [comment]
If I then POST the initial document manually (removing the `_rev`) then subsequent saves work.

**Comment by dtu-compute** [comment]
This fork https://github.com/dtu-compute/dtu-enote-stackedit have been modified to have working https and credentials for couchdb. The fork is not indented for general purpose, but the couchdb fixes are.

**Comment by benweet** [comment]
CouchDB support has been dropped in the v5 (https://stackedit.io/app), at least for now.
