### ISSUE TITLE
Should document's contentType be 'text/plain;charset=utf-8'?

### ISSUE THREAD

**Issue by Kinka** [benweet/stackedit#1054]
Default value of content type in the helper function `couchdbHelper.uploadDocument` is `text\/plain`, such setting cannot do well with non ASCII strings like Chinese. Saving content to coudb's attachments will have the wrong MIMEType so that non ASCII strings not show properly.

```
                    _attachments: {
                         content: {
                             content_type: 'text\/plain;charset=utf-8',
                             data: utils.encodeBase64(content)
                         }
                     }

```

**Comment by benweet** [comment]
CouchDB support has been dropped in the v5 (https://stackedit.io/app), at least for now.
