### ISSUE TITLE
html code div

### ISSUE THREAD

**Issue by leotiger** [benweet/stackedit#1055]
If you put the following into StackEdit things break in preview:

```
### I'm an inline html

<div>
<p>hello from StackEdit Inline HTML</p>
</div>
```

But if you add a space in front of the closing `</div>` things work just fine:

```
### I'm an inline html

<div>
<p>hello from StackEdit Inline HTML</p>
 </div>
```

This bit of code fixes this weird behavior for me:

```
        editor.getConverter().hooks.chain("preConversion", function(text) {
			
			text = text.replace(/^\<\/div\>/gm,
                function (wholeMatch) {
                    return " </div>";
                }
            );
			return text;
        });
```

Probably there's a better solution diving into the code.

Regards.
uh

**Comment by benweet** [comment]
Fixed in the v5 (https://stackedit.io/app).
