### ISSUE TITLE
Intraword in /Extensions/MarkdownExtra.js does not work properly

### ISSUE THREAD

**Issue by leotiger** [benweet/stackedit#1056]
Hi again.

This does not show up correctly:

```
_hello**hello**hello_
```
It produces, with Intraword enabled the following

_hello\*\*hello\*\*hello_ instead of

_hello**hello**hello_

Maybe I did not get this right but turning of the intraword option in settings the markdown converter runs the _DoItalicsAndBold function defined in core.js which does the job as expected.

Regards.
uh

**Comment by benweet** [comment]
Fixed in the v5 (https://stackedit.io/app).
