### ISSUE TITLE
Bold is not distinctive enough or Regular is too bold

### ISSUE THREAD

**Issue by cilerler** [benweet/stackedit#1060]
Would you please change Bold or Regular text so we can separate the difference easily?

In **editor** _(left side)_ it is very clear

![image](https://cloud.githubusercontent.com/assets/385958/21735829/7f860a12-d43a-11e6-82a9-4ce13b1f3b38.png)

But **output** _(right side)_ is really difficult to separate bold and regular text
![image](https://cloud.githubusercontent.com/assets/385958/21735306/d69cc15a-d436-11e6-93d7-638ce29c89e3.png)

🥇 also,  is there a way to set exactly same font and size that you use in **editor** to **output**?

**Comment by benweet** [comment]
Fixed in v5 (https://stackedit.io/app).
