### ISSUE TITLE
Dollar Sign Causes Odd Formatting

### ISSUE THREAD

**Issue by robarwebservices** [benweet/stackedit#1061]
![err](https://cloud.githubusercontent.com/assets/334314/21775268/d043880c-d66b-11e6-985c-a4a4a4a1b383.png)

Using a dollar sign causes weird looking output.

**Comment by leotiger** [comment]
With MathJax enabled you probably have to escape dollar signs: \$ to avoid that MathJax does some inline handling for everything in between $ and $ like in $1.00 a math expression of $1.00

If you don't need MathJax disable it in the settings of StackEdit.
Regards.
uh

**Comment by benweet** [comment]
Should be fixed in the v5 (https://stackedit.io/app). Please open a new ticket if it's not.
