### ISSUE TITLE
toc options

### ISSUE THREAD

**Issue by Flamenco** [benweet/stackedit#1062]
It would be nice to have the generated table of contents only use the headings that follow it.  That way a page can display an overview/title that is not placed in the table.

How this would be configured is open for discussion, but I suggest using key=value pairs that can further be extended.

```
# A Title
[toc (ignore-previous=true) ]
# A Section
# A Section
```

**Comment by benweet** [comment]
`[toc]` marker support has been removed in the v5. Please use handlebars templates and helpers to make exotic tocs in your exports.
