### ISSUE TITLE
All Files Become Identical

### ISSUE THREAD

**Issue by dawaltconley** [benweet/stackedit#1064]
Hey, so I've encountered this bug twice now and it's really devastating. I'll be working on a document, I won't be able to publish to github, will switch to another document to see if it still works, and find that that *other* document has changed to be identical to the first. I'm not sure if this happens all at once or if switching to a new document triggers this, but all of them will have suddenly become identical with some one document that I was working on. I've lost a lot of work this way. I began syncing everything with Drive after it happened the first time, but since opening a new file prompts it to update to Drive, this bug erased my work there as well.

After this happened most recently, I deleted all my files, yet Stackedit kept doing this when I tried to import older drive files (making them copies of the default Hello! file). The first time I fixed this problem by clearing the browser cache: now this is not working. It seems to occur with files with a fair amount of comments on them; I wonder if this is the cause?

For what it's worth, I'm using Stackedit on the Android Chrome app.

**Comment by benweet** [comment]
Closing this. Please open a new ticket if the problem still exists in the v5 (https://stackedit.io/app).
