### ISSUE TITLE
Allow strike-out ~bla~

### ISSUE THREAD

**Issue by cilerler** [benweet/stackedit#1066]
in many markdown sites including _GitHub_ wrapping a word with `~` means strikeout which we don't have it in _StackEdit_ please support that ~simple~ feature. :smile:

**Comment by chamie** [comment]
We have double-tilde for striking. Isn't that enough?
![image](https://user-images.githubusercontent.com/7083065/29710420-d97f85ca-8998-11e7-923c-39d39bb0988f.png)

**Comment by cilerler** [comment]
my bad, missed that somehow. 
I apologize taking your time
