### ISSUE TITLE
localhost/editor shows blank page

### ISSUE THREAD

**Issue by FruitfulApproach** [benweet/stackedit#1069]
I click 'Start writing now!'  and it loads a blank page.    

Installation went smoothly except maybe for `bower install` which stayed running after it seemed to finish making me to d ^C at the command line to close it.

Browser: Chrome (Version 55.0.2883.87 m (64-bit))
OS:  Win 7 64-bit

**Comment by FruitfulApproach** [comment]
I'm letting bower run longer.  That's probably it

**Comment by metal3d** [comment]
Same for me.

**Comment by benweet** [comment]
Closing this. Please open a new ticket if the problem still exists in the v5 (https://stackedit.io/app).
