### ISSUE TITLE
TeX "\newcommand" doesn't cause re-render in time

### ISSUE THREAD

**Issue by Menci** [benweet/stackedit#1070]
```markdown
// Add the newcommand here

aaa

### Title

bbb

ccc

$ \A $
```

Add `$ \newcommand{A}{AAAAA} $` to the first line, then the last line won't be re-rendered.

It seems that StackEdit only renders some lines before and after the updated line, so other equations stays the same. Are there any way to know 'they should be re-rendered'?

**Comment by benweet** [comment]
Closing this. Please open a new ticket if the problem still exists in the v5 (https://stackedit.io/app).

**Comment by Menci** [comment]
But how can I enable math equations in v5?

**Comment by benweet** [comment]
Please have a look at the markdown cheat sheet in the menu.
