### ISSUE TITLE
UX Bug: Scrollbars in Extentions under extension-preview-buttons drag the panel.

### ISSUE THREAD

**Issue by mmdts** [benweet/stackedit#1072]
Dragging the scroll bars in the Markdown Syntax and HTML Code extensions in the extension-preview-buttons panel drags the entire panel instead of just scrolling. The app could be changed such that the drag event on the scroll bar does not propagate.

**Comment by benweet** [comment]
Closing this. Please open a new ticket if the problem still exists in the v5 (https://stackedit.io/app).
