### ISSUE TITLE
Can't work with chrome on ios

### ISSUE THREAD

**Issue by volcani** [benweet/stackedit#1073]
It looks like stackedit works on iOS when using chrome, as said in this issue.

https://github.com/benweet/stackedit/issues/281

But now, from iPad with iOS10, it doesn't work.
Only blank is there, nothing appears(buttons or even error massege).
How can I use on Chrome with iOS?

**Comment by benweet** [comment]
Closing this. Please open a new ticket if the problem still exists in the v5 (https://stackedit.io/app).
