### ISSUE TITLE
Synchronize all folders and files with Google Drive

### ISSUE THREAD

**Issue by dawid-zukowski** [benweet/stackedit#1078]
Is possible to synchronize all folders and files with Google Drive? I have a lot of content and I want to sync with my other devices. Sync each file manually is time-consuming.

**Comment by benweet** [comment]
Fixed in v5 (https://stackedit.io/app).

**Comment by AstroTom** [comment]
Can you please explain the process for syncing all my google or dropbox folders? I tried linking my account but it is not obvious.

**Comment by drewzh** [comment]
@AstroTom I'm in the same boat - it seems to only sync 1 file at a time - useless for my use case. I need it to read all markdown files in a google drive folder - including sub folders. Any idea? Did you get anywhere with this?

FYI @benweet

**Comment by kpfromer** [comment]
This would be a handy feature. Is there any status on this issue?
