### ISSUE TITLE
how to write a matrix with liner label and row label

### ISSUE THREAD

**Issue by TankAbraham** [benweet/stackedit#1079]
I wanna write a matrix with liner label and row label.
I have tried some envrionment such as \{bordermatrix} and so on, but compiler can`t deal with it correctly.

Code below is the Latex code which I have tried:

$\bordermatrix{%
& 0 & 1 & 2 \cr
0 & A & B & C \cr
1 & d & e & f \cr
2 & 1 & 2 & 3 \cr
}$

**Comment by TankAbraham** [comment]
oops, I  forget to say : Thanks!

**Comment by benweet** [comment]
That's neither a bug nor a feature request. I guess you'll find answers on https://tex.stackexchange.com/.
