### ISSUE TITLE
How to publish to GitHub wiki?

### ISSUE THREAD

**Issue by funkyidol** [benweet/stackedit#108]
I want to publish my documents to the repository wiki page directly. 

My repository is at location https://github.com/funkyidol/CodingNotes
I tried using the clone url for wiki ( https://github.com/funkyidol/CodingNotes.wiki.git) but it keeps giving the error "Could note publish on GitHub"

**Comment by edouard-mangel** [comment]
Hello, 

Thanks a lot for your work on stackedit, it's a really great tool. 
I used stackedit to publish to github via gh-pages but the sequence diagrams I did do not show properly, I can only see the text and the diagrams don't appear. Is there any way I could have them display properly? 

Thanks a lot.
