### ISSUE TITLE
working-indicator bar never stops working on google drive/doc

### ISSUE THREAD

**Issue by joshball** [benweet/stackedit#1080]
The working indicator bar continues to show work for a google doc. I see in the network tab that there are requests to google drive changes every second. Which makes sense. But the ui is a bit unnerving if it just continues to show work when nothing is actually happening (no changes are being made)

Also, it is unclear what "work" is actually being done. When you hover over it, no information is shown.

So the issues:
1. Work should not be shown constantly
2. Some feedback on what work is being done might be helpful.

Thoughts?

**Comment by benweet** [comment]
Closing this. Please open a new ticket if the problem still exists on v5 (https://stackedit.io/app)
