### ISSUE TITLE
documentPanel toggle bug

### ISSUE THREAD

**Issue by chenhaodonHD** [benweet/stackedit#1082]
In viewerMode,document panel can't toggle in second,there is not fixViewportScrolling() in layout.js.
layout.js
if (window.viewerMode) {
    previewPanel.width = wrapperL3.width;
    previewPanel.height = wrapperL3.height;
    previewContainer.width = wrapperL3.width;
    previewContainer.height = wrapperL3.height;
    previewPanel.applyCss();
    previewContainer.applyCss();
    return onResize();
}

**Comment by benweet** [comment]
Closing this. Please open a new ticket if the problem still exists on v5 (https://stackedit.io/app)
