### ISSUE TITLE
Using a Japaense IME to select kanji causes the cursor to jump to the previous line.

### ISSUE THREAD

**Issue by mca62511** [benweet/stackedit#1083]
When typing in Japanese, every time you use the IME to auto-select your kanji, it jumps the cursor up to the previous line. At first I thought I was accidentally hitting my touchpad, but I've tried it again on a different computer with the touchpad disabled. This has happened on both a Windows 7 machine and a Chromebook.

-----------------

The following is a description of what a Japanese IME is for context.

When typing in Japanese you use software called an IME.

An IME takes input using roman characters (a, b, c, d) and interprets them as Japanese characters.

If you type "arigatou" it results in the phrase, ありがとう

However, Japanese also uses Chinese characters. In order to select those Chinese characters, you need to either pick them from a list which appears as you type, or press "space" and then "enter" to have the IME guess which Chinese character you're looking for.

You type the letters "gakusei" which results in the hiragana "がくせい", it shows a list of potential Chinese characters and you either select one, or by pressing "space" and "enter" it results in "学生"

**Comment by outloudvi** [comment]
Same problem here. Using an IME and the cursor goes bottom.
Fix is hoped.

**Comment by benweet** [comment]
Closing this. Please open a new ticket if the problem still exists on v5 (https://stackedit.io/app)
