### ISSUE TITLE
Problems with wordpress and dropbox

### ISSUE THREAD

**Issue by LizzAlice** [benweet/stackedit#1084]
On one computer, I am able to connect to dropbox with stack edit, on the other it does not work.
Also, on the computer where I am able to connect to dropbox, I can't publish on WordPress. I am asked to approve twice and then I get the message that the access to WordPress is not authorized, although the login credentials are the right ones.

**Comment by benweet** [comment]
Closing this. Please open a new ticket if the problem still exists on v5 (https://stackedit.io/app)
