### ISSUE TITLE
Support Abbreviations

### ISSUE THREAD

**Issue by felipe1982** [benweet/stackedit#1087]
http://fletcher.github.io/MultiMarkdown-4/abbreviations

Abbreviations should be working, but they are not:

```
*[HTML]: HyperText Markup Language
*[W3C]:  World Wide Web Consortium
```

Then, wherever you use the words HTML or W3C in your document, the abbr markup will be added:

```
The HTML specification
is maintained by the W3C.
```

becomes:

```
The <abbr title="Hyper Text Markup Language">HTML</abbr> specification
is maintained by the <abbr title="World Wide Web Consortium">W3C</abbr>.
```

**Comment by benweet** [comment]
Closing this. Please open a new ticket if the problem still exists on v5 (https://stackedit.io/app)
