### ISSUE TITLE
Feature Request : c3.js as Charting provider?

### ISSUE THREAD

**Issue by benjaminradio** [benweet/stackedit#1088]
I love StackEdit and us it almost exclusively for documentation, but one feature I do wish for is native charting. Its not hard to roll your own but C3.js seems like a good fit for StackEdit. Both C3.js and it's dependency D3.js can be used offline and the syntax is very markdown-esque. I think it would fit well with the fenced code blocks like the UML diagrams.

**Comment by benweet** [comment]
Hi, can you point me to the syntax documentation ? Thanks

**Comment by benweet** [comment]
Will reopen the ticket once I have the relevant documentation.

**Comment by benjaminradio** [comment]
I  don't see a charting option currently implemented so I wanted to revive this issue.

Full documentation is on the C3.js site at [https://c3js.org/reference.html](https://c3js.org/reference.html).

Taken from the examples at [https://c3js.org/samples/simple_xy_multiple.html](https://c3js.org/samples/simple_xy_multiple.html), I would imagine a markdown-like implementation might look like:

    ```chart
    data: {
        xs: {
            'data1': 'x1',
            'data2': 'x2',
        },
        columns: [
            ['x1', 10, 30, 45, 50, 70, 100],
            ['x2', 30, 50, 75, 100, 120],
            ['data1', 30, 200, 100, 400, 150, 250],
            ['data2', 20, 180, 240, 100, 190]
        ]
    }
    ```

That would easily translate to javascript:

```javascript
var chart = c3.generate({
    data: {
        xs: {
            'data1': 'x1',
            'data2': 'x2',
        },
        columns: [
            ['x1', 10, 30, 45, 50, 70, 100],
            ['x2', 30, 50, 75, 100, 120],
            ['data1', 30, 200, 100, 400, 150, 250],
            ['data2', 20, 180, 240, 100, 190]
        ]
    }
});
```
I think all you'd need to do would be to include D3 from [https://d3js.org/d3.v5.min.js](https://d3js.org/d3.v5.min.js) and C3 from a host like cloudflare at [https://cdnjs.cloudflare.com/ajax/libs/c3/0.7.8/c3.min.js](https://cdnjs.cloudflare.com/ajax/libs/c3/0.7.8/c3.min.js). Custom CSS may need to be added to match the look-and-feel of StackEdit.
