### ISSUE TITLE
Will Stackedit stop working with Dropbox on June 28, 2017

### ISSUE THREAD

**Issue by terryroe** [benweet/stackedit#1089]
When I authorized Stackedit on my Dropbox account today, I received a warning that the app may stop working on June 28, 2017.  Will Stackedit be updated so it will continue working with Dropbox?

**Comment by SirGnip** [comment]
I received an email from Dropbox today saying that StackEdit will no longer work with Dropbox on Sept 28, 2017.  Here's a portion of the email I received from Dropbox

> Hi Scott,On September 28, 2017, we’ll be making some changes to Dropbox that will likely affect the following 3rd party apps linked to your Dropbox account: StackEdit. You’re receiving this email because you’ve used these apps at least once within the past month.
> 
> While we’ve informed all developers about our upcoming changes, the developers for the apps listed above have yet to update their apps accordingly. If they don’t update their apps before September 28, these apps will no longer be able to access Dropbox. That said, any data already saved in Dropbox won’t be affected and will still be accessible from our official web, mobile, and desktop clients.

Sounds like the StackEdit Devs need to update how it interacts with Dropbox.  Anyone have more info about this?  Any plans for an update?  I rely pretty heavily on StackEdit and its Dropbox integration.  I'd hate to loose it.

**Comment by benweet** [comment]
Closing this. Please open a new ticket if the problem still exists on v5 (https://stackedit.io/app)
