### ISSUE TITLE
Publish Github/Gitlab issue

### ISSUE THREAD

**Issue by madeupname** [benweet/stackedit#1091]
StackEdit is so much better than the standard issue and wiki editors for Github and Gitlab. I especially love the ease at which you can create nested bulletted/numbered lists, which is super useful for user stories and specs. 

Is there any way to publish a StackEdit file as an issue or wiki page on those services? I know I can cut and paste, but syncing them would be a huge win whenever I needed to edit.

**Comment by madeupname** [comment]
Just a note that if you put StackEdit on Github Marketplace as a drop in replacement for the issue and wiki editors, I'd throw money at you so fast the atmosphere would catch fire.

**Comment by benweet** [comment]
I think it's impossible with current API, at least for the wiki, sorry.
