### ISSUE TITLE
Make Dropbox Access Configurable

### ISSUE THREAD

**Issue by erikbgithub** [benweet/stackedit#1093]
It is absolutely inacceptable that stackedit just grabbed complete access to my dropbox. What the hack, man!

Let users choose/create a folder to share with stackedit.

PS: Dropbox announced in the share request that their API will change. May want to check that one out.

**Comment by benweet** [comment]
Closing this. Please open a new ticket if the problem still exists on v5 (https://stackedit.io/app)
