### ISSUE TITLE
Import failing on Chrome/Android

### ISSUE THREAD

**Issue by ferdossi** [benweet/stackedit#1097]
Hi,

The import functionality from cloud fails on android when I do it with Chrome, it's working fine with other browsers.
When you open Stackedit for the 1st time, you have this tutorial long text, then you import any document from the cloud, there is a flash message saying the file was imported successfully, but in fact it is not, the file is not imported at all and the bad thing is that the existing text sticks right there and so the automatic update replaces this existing text with your file content and you  loose everything.
Rgds.

**Comment by cryptogee** [comment]
Did anybody reply to you on this issue??

I don't see the point in giving these guys money if they can't keep your files safe! I have the same issue, all my files are gone, I'm praying that there is some kind of backup...

**Comment by benweet** [comment]
Closing this. Please open a new ticket if the problem still exists on v5 (https://stackedit.io/app)
