### ISSUE TITLE
Can't recover files - really desperate

### ISSUE THREAD

**Issue by cryptogee** [benweet/stackedit#1100]
Earlier on I cleared my browser cache knowing that I would be signed out of StackEdit but thought that was no drama as I have an account and I'd just sign back in.

Imagine my absolute horror when I found that despite signing back in, all of my files have gone! I tried the doc recovery however all it does is recover the Hello file. Is there anything I can do? Please help me, this is a disaster.

**Comment by benweet** [comment]
In the welcome file, it's stated that you have to synchronize files if you want them safe. Sorry.
