### ISSUE TITLE
Export to PDF utilities for selfhosting

### ISSUE THREAD

**Issue by fangqiao** [benweet/stackedit#1101]
Hi, Thanks for developing stackedit. I like its expressiveness. I want to self-host it. I also need the utility that converts the markdown to PDF. 

If you don't mind, can you please share with us which technology you use for the conversion? And if possible, also open source your solution? 

Many thanks in advance.

**Comment by benweet** [comment]
Hi, please send an email to stackedit.project@gmail.com if you need some (not-free) support.
