### ISSUE TITLE
How to decrease font size on PDF export

### ISSUE THREAD

**Issue by cilerler** [benweet/stackedit#1102]
PDF font sizes are at least 40% bigger than what they supposed to be, how can I decrease it?

> _I saw in https://wkhtmltopdf.org/usage/wkhtmltopdf.txt there is a **DPI** value but it doesn't changing anything at all._

[Title (3).pdf](https://github.com/benweet/stackedit/files/1220158/Title.3.pdf)

**Comment by benweet** [comment]
You can customize that via CSS in the PDF template, in the settings.
