### ISSUE TITLE
Sponsorship options

### ISSUE THREAD

**Issue by sidneydemoraes** [benweet/stackedit#1108]
I would love to sponsor this project as I use it in a daily basis and I really think it's awesome.

However, I don't trust Monetize and would like to use a more reliable option such as Paypal. Is it going to be possible?

**Comment by benweet** [comment]
Added PayPal options in the v5.

**Comment by Mercala** [comment]
I don't have a Paypal account, how can I sponsor? I would like to export as PDF features.
