### ISSUE TITLE
Space between # and text

### ISSUE THREAD

**Issue by MrGrimod** [benweet/stackedit#1109]
When using Stackedit on stackedit.io, text that is formated without space between # and text is highlighted.
When pasting to github text isn t highlighted anymore. 
Beginners are very confused with that.

**Comment by pricci1** [comment]
True, even the author has this problem, check the [wiki](https://github.com/benweet/stackedit/wiki) and you will see what I mean.

**Comment by MrGrimod** [comment]
This moment when you have to commit two times -.-

**Comment by benweet** [comment]
Please open a new bug if it's still there in the v5: https://stackedit.io/app
