### ISSUE TITLE
Pagebreaks not working

### ISSUE THREAD

**Issue by taigereye** [benweet/stackedit#1113]
No LaTex command is working to create a simple pagebreak in a document on StackEdit. If I upload a Markdown file, and add \pagebreak, \newpage, or the like it simply appears as plaintext both in the viewer and in the exported PDF. Is there any way to fix this? Pagebreaks are a simple but fundamental piece of functionality that any editor should have.

**Comment by maxymax68** [comment]
a real bummer, especially if having a table spanning several pages. The table header is repeated on following pages over normal table rows. This is a real issue that needs fixing. Any idea how to workaround it?

**Comment by benweet** [comment]
Please try to add page breaks using `<div class="page-break-after"></div>`.

**Comment by sidneydemoraes** [comment]
Unfortunately, `<div class="page-break-after"></div>` is not working neither in editor or app versions.

**Comment by EvWoN** [comment]
Page breaks are sadly still not working...

**Comment by benweet** [comment]
`<div class="page-break-after"></div>` seems to work fine with PDF exports. What's the problem again?

**Comment by apatrida** [comment]
the problem is that it isn’t working, adding that to the document does nothing.

**Comment by sidneydemoraes** [comment]
> `<div class="page-break-after"></div>` seems to work fine with PDF exports. What's the problem again?

Hi Benoit. Page break on PDF exports only works if we use _Styled HTML_ option. If we try _ Styled HTML with TOC_ for instance it doesn't work.

**Comment by devranjandas** [comment]
Pagebreak is not workign for me as well.

**Comment by coilysiren** [comment]
To add another comment here since there's back and forth, page breaks did not work when I tried them just now.

1. I insert the text `<div class="page-break-after"></div>`
2. I choose `Export as PDF`
3. I choose `Styled HTML`
4. The resultant PDF does not contain a page break at the appropriate location
