### ISSUE TITLE
Is there any way to download StackEdit to my computer, so that I can use it offline?

### ISSUE THREAD

**Issue by sn0wyfall** [benweet/stackedit#1114]
Sorry for the nooby question, but I'm trying to figure this out.

StackEdit is quite useful for me – I like the scroll sync and the markdown and LaTeX integration into the live preview at the right. I would love to use StackEdit in certain situations where I don't have any internet connection. The only way I can see myself doing that is by opening it in a browser and leaving it open there. However, is there a better way of opening it on my computer whenever I wanted to, without having to connect to the internet at all? This project is open-source so I assumed it would be easy to do that.

Thanks!

**Comment by Medicliffy** [comment]
You can use it offline in the browser.

If I understand correctly, it'll save files locally in your browser's local storage - so just be careful not to delete this before it has a chance to sync with Dropbox/Drive etc. and you should otherwise be set using it just as if online.

**Comment by sn0wyfall** [comment]
@Medicliffy Oh, I understand that, thanks. I'm just wondering though whether it would be possible to _open_ StackEdit without an internet connection. So, for example, let's say that StackEdit goes down. Then I wouldn't be able to load it onto my browser anymore, right? So is there any way to prevent something unfortunate like that happening?

**Comment by Medicliffy** [comment]
If you're using Chome, they have an [extension](https://chrome.google.com/webstore/detail/stackedit/iiooodelglhkcpgbajoejffhijaclcdg) (not sure about support for other browsers) which should resolve that. I forgot clarify in my first comment!

I tested it after disconnecting from the internet and was able to get to my notes.

**Comment by sn0wyfall** [comment]
Oh, that's awesome! Thanks! I'll try that out!
