### ISSUE TITLE
**`bold code`** is rendered okay but not highlighted okay

### ISSUE THREAD

**Issue by smsrkr** [benweet/stackedit#1117]
**`code`** spans within strong tags are previewed properly, but the editor highlighter thinks the `**` marker at the span's end is the beginning of the next strong marker.

![se_strong_code_hilite_bug](https://user-images.githubusercontent.com/3525376/31044070-b6556476-a5e9-11e7-845b-cc2f5123bdc4.png)
In the image, this bug makes `; highlighted **badly` show up in bold. (Bug exists in both SE4 and SE5.)

**Comment by benweet** [comment]
I'm afraid the syntax highlighting in the editor won't be as accurate as the effective markdown conversion. It would be too much of an effort trying to cover all the spec. Sorry.
