### ISSUE TITLE
New editor version is very slow

### ISSUE THREAD

**Issue by stueliueli** [benweet/stackedit#1118]
Hello There

Since a few days I'm using the new version of stackedit at stackedit.io/app. The main reason for this is that the version at /editor does not support syncing to dropbox anymore, because "The API is deprecated" or something alike.

Sadly, the new editor is being very slow while using bigger files (500+ Lines with Code). It makes it really hard to use it. 
Am I missing something, or is there something in planning?

I'm using Firefox 55.0.3 on Windows 10
MS Surface Pro 3, i7

Thank you for your reply.

**Comment by benweet** [comment]
Hi, can you share a markdown file to reproduce the issue ?
Many thanks

**Comment by stueliueli** [comment]
I made a paste with a current file:

https://pastebin.com/GsD1d1c4

Thank you

**Comment by benweet** [comment]
Should be fixed in v5.8.
