### ISSUE TITLE
Dropbox API expired

### ISSUE THREAD

**Issue by wintermelons** [benweet/stackedit#1122]
As per [Dropbox blog](https://blogs.dropbox.com/developers/2017/09/api-v1-shutdown-details/), the api is returning `{400: {"error": "v1_retired"}}`, which is outputed as an error when a file is saved on Dropbox.

**Comment by benweet** [comment]
This is fixed in the v5 (https://stackedit.io/app).

**Comment by wintermelons** [comment]
Never mind, I just saw V5. It just wasn't updated in my Chromebook app. Thanks!
