### ISSUE TITLE
Save to Github "OK" button in modal does nothing

### ISSUE THREAD

**Issue by Daniel-Hug** [benweet/stackedit#1123]
1. I gave permissions to my Github,
2. clicked "Save to Github" under the synchronize window
3. typed a repository URL and file path: 
![screenshot-stackedit io-2017-10-04-12-11-19-881](https://user-images.githubusercontent.com/1326984/31194858-4388999c-a8fd-11e7-8e56-4b93ed465b1e.png)
4. tapped OK

...and nothing happened — no errors in the console even.

**Comment by benweet** [comment]
Hi Daniel,
That looks weird. Is your network connection ok ? Do you see any failure or pending request in the network tab of the browser developper tools ?

**Comment by Daniel-Hug** [comment]
I've refreshed and such. It's making several requests to google apis with 200 status.

**Comment by benweet** [comment]
Can you check you're running the v5.0.4 in menu>more>about. If you don't have this about menu it means you're not running the latest version.
To upgrade, you have to close all the StackEdit tabs and relaunch it.

**Comment by Daniel-Hug** [comment]
Yes, I'm running 5.0.4 on Chrome 61.0.3163.100 (Official Build) (64-bit Windows 10)

**Comment by Daniel-Hug** [comment]
Works fine in Firefox.

**Comment by Daniel-Hug** [comment]
Synchronizing to Google Drive works. But I can't sync any file to GitHub.

**Comment by benweet** [comment]
Ok, I think it's because of the final `/` in the repository URL.

**Comment by Daniel-Hug** [comment]
Yes, it works without the slash.
