### ISSUE TITLE
Console error when pressing "cancel" in "File synchronization" modal

### ISSUE THREAD

**Issue by Daniel-Hug** [benweet/stackedit#1124]
1. Sync file with Google Drive
2. Click menu > "Synchronize" > "File Synchronization" to open modal
3. Click "Cancel" in modal

Error appears in console:

![screenshot-stackedit io-2017-10-04-22-24-48-259](https://user-images.githubusercontent.com/1326984/31212080-172c21f6-a953-11e7-9af6-dd73d1dde106.png)

On latest Chrome.

**Comment by benweet** [comment]
Should be fixed.
