### ISSUE TITLE
Is there a way to sync documents between v4 and v5?

### ISSUE THREAD

**Issue by orome** [benweet/stackedit#1129]
Version 5 seems to be unaware of any version 4 documents. Is this the intent or just a not-yet addressed feature?

**Comment by shana** [comment]
Was wondering the same...

**Comment by liuyigh** [comment]
I guess we can always synchronize the two via Google Drive etc.?

**Comment by orome** [comment]
@liuyigh That's not really the question.

**Comment by benweet** [comment]
You can import v4 backups in v5. I guess that's good enough.

**Comment by orome** [comment]
@benweet How is that goo enough?

**Comment by benweet** [comment]
@orome the v4 is being deprecated and is going to disapear in a near future so 2 ways sync is not relevant.

The question is how is that not good enough. Can you describe your use case?

**Comment by orome** [comment]
@benweet It's not *syncing*. You've addressed a different issue here: forced migration from 4 (which is news to me).
