### ISSUE TITLE
Blogger Publisher\YAML properties

### ISSUE THREAD

**Issue by dmineau** [benweet/stackedit#1130]
For Stack Edit 5, when I try to publish to Blogger, none of the file properties I set work.  Here are the current 3 that I enter:
title: My Custom Title
tags: Label1, Label2
status: draft

The post is still named the same as the document, it has no labels, and automatically publishes instead of staying a draft.

(and yes, I am putting them into the new default File screen)

**Comment by benweet** [comment]
> (and yes, I am putting them into the new default File screen)

Do you use the file properties dialog in the menu ?

![image](https://user-images.githubusercontent.com/1005257/32414703-c50d7b96-c224-11e7-87a9-9ef2a53e8913.png)

**Comment by dmineau** [comment]
First, Thank you very much for responding.  I understand that you've been moving on to another project.

Yes, File properties is what I'm trying to use.
Here's the box I'm entering the properties into.
![stackeditproperties](https://user-images.githubusercontent.com/20189330/32446622-82a5307e-c2d7-11e7-9651-a9c6d2d98552.PNG)

**Comment by benweet** [comment]
Should be fixed now.

**Comment by dmineau** [comment]
Confirmed.  Thank you again!

**Comment by ojitha** [comment]
The title worked for me, but not mermaid
title: AngularJS Basics
tags: AngularJs
extensions:
  mermaid:
    enabled: true
