### ISSUE TITLE
Restore a file put in trash

### ISSUE THREAD

**Issue by ferdossi** [benweet/stackedit#1132]
On my android, I deleted a synced file by accident on the left pane, so now it's in trash 
I know that on a PC it's possible to restore with a drag and drop, but how would you do that on a mobile ? How do I restore my file? What will happen after 7 days ?

**Comment by benweet** [comment]
Hi, it should be in the trash on your laptap as well, so you can move it back from there. Can you check that you're running the v5.0.5 on both sides (in the Menu > More > About dialog).

**Comment by ferdossi** [comment]
Yes it is 5.0.5 on both sides but the trash is not synchronized and btw why would it be?
what would make the link between my android and my labtop? I did not sign in with my google account on both sides, I just opened a dropbox file on my android.

**Comment by benweet** [comment]
Ok, I understand. Reopening the file from Dropbox should basically restore the file from the trash. Would it be a solution ?

**Comment by ferdossi** [comment]
nop, I tried, the file sticks in the trash even after reopening, I can work with it normally but it's in the trash..
The only way I found was to reset the app.

Anyway, working with local folders seems limited to PC only

**Comment by benweet** [comment]
Should be fixed now.
