### ISSUE TITLE
Icons missing in v5

### ISSUE THREAD

**Issue by RachelAmbler** [benweet/stackedit#1133]
Just wondering if this is a v5 beta issue, or a design choice.

Clarification - Icons such as the ones generated thusly: `<i class="icon-compass"></i>`

**Comment by benweet** [comment]
These were icons provided in the v4. They are not provided anymore in v5 I'm afraid.

**Comment by Norfeldt** [comment]
StackEdit is a beautiful piece of work.  

What would your suggestion be on how to insert icons in version 5?

**Comment by benweet** [comment]
You can still use `<i class="icon-compass"></i>` and include the font awesome  stylesheet (or any other icon font that works with CSS classes) in a custom template. The icons won't be rendered in the editor, but they will be in your exports and publications.

**Comment by Norfeldt** [comment]
When you say `won't be rendered in the editor` do you also mean the markdown viewer?

I assume that I have to go into `More...`, but how to setup the stylesheet in the custom templates confuses me a little..

**Comment by learnwell** [comment]
I'm bummed too ... for what its worth, these icons still seem to render in the live preview for stackedit: https://www.webpagefx.com/tools/emoji-cheat-sheet/
