### ISSUE TITLE
UML flowchart diagrams do not render

### ISSUE THREAD

**Issue by tydel** [benweet/stackedit#1136]
When attempting to use flowchart.js markup in a markdown document in the editor, it doesn't render in the preview pane.

For instance:

```flow
st=>start: Problem
sub1=>subroutine: Resolve Problem
e=>end: Problem Resolved
op1=>operation: Escalate to Escalation Engineer
op2=>operation: Escalate to Management
cond1=>condition: Able to Resolve?
cond2=>condition: Able to Resolve?

st->op1->cond1
cond1(yes)->sub1->e
cond1(no)->op2
op2->cond2
cond2(yes)->sub1->e
cond2(no)->e
```

Just displays as text:

![6d2d2b6a-4a3f-4a13-adce-90d22a0833ff](https://user-images.githubusercontent.com/425605/31515622-a6fe6cf6-af4a-11e7-8e1d-471756c61481.png)

**Comment by RachelAmbler** [comment]
You using *=* when you should be using *-* ?

I tried this in *v4* and it rendered your first sequence

```
\``` sequence
st->start: Problem
sub1->subroutine: Resolve Problem
e->end: Problem Resolved
op1->operation: Escalate to Escalation Engineer
op2->operation: Escalate to Management
cond1->condition: Able to Resolve?
cond2->condition: Able to Resolve?
\```
```

![2017-10-13_7-29-16](https://user-images.githubusercontent.com/1454901/31544357-6714ed4c-afe8-11e7-9b58-0a66216d15cf.png)

**Comment by benweet** [comment]
In the v5, you will have to use the mermaid syntax (```mermaid).

**Comment by yxliang01** [comment]
@benweet Would be great if this can be documented. I couldn't find any info related to this except looking into issues.

**Comment by martin-neotech** [comment]
You can render UML diagrams using [Mermaid](https://mermaidjs.github.io/). For example, this will produce a sequence diagram:

\```mermaid
sequenceDiagram
Alice ->> Bob: Hello Bob, how are you?
Bob-->>John: How about you John?
Bob--x Alice: I am good thanks!
Bob-x John: I am good thanks!
Note right of John: Bob thinks a long<br/>long time, so long<br/>that the text does<br/>not fit on a row.

Bob-->Alice: Checking with John...
Alice->John: Yes... John, how are you?
\```

And this will produce a flow chart:

\```mermaid
graph LR
A[Square Rect] -- Link text --> B((Circle))
A --> C(Round Rect)
B --> D{Rhombus}
C --> D
\```
