### ISSUE TITLE
Enhancement: Gantt Chart

### ISSUE THREAD

**Issue by ofenerci** [benweet/stackedit#1137]
I wonder stackedit could publish "Gantt Chart." There is already a similar extension in [cmd markdown editor](https://www.zybuluo.com/mdeditor).

**Comment by benweet** [comment]
The v5 now provides support for mermaid diagrams which has gantt diagrams support: https://mermaidjs.github.io/gantt.html

**Comment by vekexasia** [comment]
hey @benweet I've tried to copy-paste the example but it didn't work.
