### ISSUE TITLE
Find & Replace missing in v5

### ISSUE THREAD

**Issue by miaoyushun** [benweet/stackedit#1139]
I can replace some text when I press `Command + F` in V4, 
but there is only popup a browser find bar in V5, 
my browser is chrome 61 on OSX 10.12.

**Comment by benweet** [comment]
Should be available in the v5.1.

**Comment by theoryshaw** [comment]
@miaoyushun did this get implemented, do you know?  Can't seem to find it on v5.1.

**Comment by c-coelho** [comment]
@theoryshaw, you can use find & replace functionality by pressing `mod+alt+f` or `mod+g`. I found it by looking for the shortcuts on Menu/More../Settings/Default settings.

**Comment by jan-niestadt** [comment]
Wow, that's well hidden functionality. ;-)

**Comment by xinatcg** [comment]
> @theoryshaw, you can use find & replace functionality by pressing `mod+alt+f` or `mod+g`. I found it by looking for the shortcuts on Menu/More../Settings/Default settings.

works, If can have a help page to see all the shortcut will be good!

**Comment by xinatcg** [comment]
find the default keymap, it is in the setting config:

<img width="278" alt="image" src="https://github.com/benweet/stackedit/assets/55399567/8d74eb6a-11e3-44e7-8388-466e3818ad9e">

<img width="555" alt="image" src="https://github.com/benweet/stackedit/assets/55399567/c3185be1-da49-4fa5-82a7-7f00954b8325">


```

# Keyboard shortcuts
# See https://craig.is/killing/mice
shortcuts:
  mod+s: sync
  mod+f: find
  mod+alt+f: replace
  mod+g: replace
  mod+shift+b: bold
  mod+shift+c: clist
  mod+shift+k: code
  mod+shift+h: heading
  mod+shift+r: hr
  mod+shift+g: image
  mod+shift+i: italic
  mod+shift+l: link
  mod+shift+o: olist
  mod+shift+q: quote
  mod+shift+s: strikethrough
  mod+shift+t: table
  mod+shift+u: ulist
  '= = > space':
    method: expand
    params:
    - '==> '
    - '⇒ '
  '< = = space':
    method: expand
    params:
    - '<== '
    - '⇐ '

```
