### ISSUE TITLE
Use github wiki repository as backing store

### ISSUE THREAD

**Issue by zwn** [benweet/stackedit#1141]
I'd like to be able to edit github wiki pages. However, right now I get 404 when I enter the url of a github wiki repository.

**Comment by Arregi** [comment]
I can edit without issues now, is this really the right place to post this?

**Comment by zwn** [comment]
I still cannot (I get "Could not publish on GitHub." message). I assumed it is not implemented.

What steps lead to you being able to edit github wiki pages using the stackedit editor? My steps are:
1. go to https://stackedit.io/editor#
2. press Publish on GitHub
3. fill the repository url - copied from the wiki pages (marked as "Clone this wiki locally")
4. set file path
5. press publish

I figured if this is not the right place, someone will let us know (I don't know of a better place).

**Comment by Arregi** [comment]
Sorry man, I completely misunderstood your issue. And yes this is of course the right place. Sorry again 🙈

Imanol

**Comment by benweet** [comment]
I'm afraid there is no way to edit wikis with the current GitHub API.

**Comment by jon077** [comment]
@benweet  - Is this still the case?  It looks like you can add .wiki to the end of the repo URL and clone a wiki.  I tried it and it didn't work, so i doubt it, but just checking in case this changed in the past two years.
