### ISSUE TITLE
Line breaks inserted where unexpected

### ISSUE THREAD

**Issue by moses-moore-spafax** [benweet/stackedit#1142]
According to the [Markdown format](https://github.com/fletcher/MultiMarkdown/blob/master/Documentation/Markdown%20Syntax.md), included in the Stackedit help text:
_"Manual line breaks: end a line with two or more spaces."_

I expect `alpha\ \ \nbeta` should render as `<p>alpha<br>beta</p>`,  
and `alpha\nbeta` should be `<p>alpha beta</p>`  
because the former has two or more spaces before the line-ending, and the latter has less than two spaces (zero) before the line-ending.

Instead what I see is  `alpha\nbeta` -> `<p>alpha<br>beta</p>` 

(I used `\ ` to represent a single whitespace character (ie \x20) because github's markdown renderer collapses spaces even inside backticks.)

**Comment by benweet** [comment]
This was configurable in the settings in the v4. It's now configurable in the file properties, and that's the default behavior in v5.

**Comment by crisperdue** [comment]
To clarify, using the current Stackedit on https://stackedit.io/app#,
I find that line breaks in Markdown source (as in a paragraph)
generate linebreaks in Stackedit previews by default
when using the gfm preset.

I am able to override this using the File Properties user interface
using the following YAML:
```
extensions:
  preset: gfm
  markdown:
    breaks: false
```

Just `preset: gfm` does not achieve this.
