### ISSUE TITLE
Missing icon on phone browser

### ISSUE THREAD

**Issue by threkk** [benweet/stackedit#1144]
Is there any reason behind [removing](https://github.com/benweet/stackedit/blob/master/index.html#L7) the icons for phones?

**Comment by benweet** [comment]
Should be there now.

**Comment by ferdossi** [comment]
Are you sure?  I don't see any new icon on the 5.1.2, I mean the new line, the hyperlink..
Unless I switch my browser to desktop view

**Comment by benweet** [comment]
Yes, icons are injected by the FaviconsWebpackPlugin: https://github.com/benweet/stackedit/blob/8c02d1e221ef3748389250128553610f48d572a7/build/webpack.base.conf.js#L87
