### ISSUE TITLE
Stackedit 5 Frozen 

### ISSUE THREAD

**Issue by zzt93** [benweet/stackedit#1149]
OS: 
Linux zzt-pc 4.13.9-200.fc26.x86_64 #1 SMP Mon Oct 23 13:52:45 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Browser:
Google Chrome Version 62.0.3202.75 (Official Build) (64-bit)

Description:
Open [stackedit 5](stackedit.io/app) and a few seconds, it is frozen and chrome's cpu usage will exceed 100% util it is closed.

If you need more info, let me know. Thanks.

**Comment by benweet** [comment]
Hi,

Can you try this:

1. Make sure you have only 1 StackEdit tab open
2. Hard refresh the page (StackEdit should upgrade itself)
3. Go to Menu>More>About and make sure you're running the v5.1.1
4. Tell me if it's fixed

Thanks!

**Comment by zzt93** [comment]
It seems not frozen now. Maybe I opened one StackEdit 5.1.1 and one StackEdit 4 at that time. Thanks.

BTW, just refresh StackEdit 4 seems not upgrade to StackEdit 5 for me. What do you mean 'hard refresh'?
