### ISSUE TITLE
math output in pdf slightly off

### ISSUE THREAD

**Issue by kasperpeulen** [benweet/stackedit#115]
Here is the original html:
http://pastehtml.com/view/dh3wmjg55.html

This is the pdf output:

![image](https://f.cloud.github.com/assets/1035299/1214407/74c0402e-263d-11e3-89fb-3651c8171393.png)

I tried to do the same with this html2pdf converter: http://www.html2pdf.it/

Which look slighly more like the original:
![image](https://f.cloud.github.com/assets/1035299/1214418/ad553bd8-263d-11e3-89b0-858065d0d90d.png)

**Comment by benweet** [comment]
Closing as too old.
