### ISSUE TITLE
maths

### ISSUE THREAD

**Issue by profjlg** [benweet/stackedit#1157]
why no more used of  mathjax ?

for example how to box a formula ?

$\boxed{}$ is not understood (V5) though it was with V4

**Comment by benweet** [comment]
The v5 now uses [katex](https://github.com/Khan/KaTeX). I guess you'll have to open a ticket there.

**Comment by RoyiAvital** [comment]
Why not have an option between them?

By the way, any chance to have release notes between release versions in GitHub?
