### ISSUE TITLE
Error on installation (incompatible module)

### ISSUE THREAD

**Issue by saatomic** [benweet/stackedit#1158]
I've closely followed the installation instructions (on a Kali 2017.2) but encountered the following issue:

```
# yarn install
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error indexeddbshim@3.0.4: The engine "node" is incompatible with this module. Expected version ">=6.9.2".
error Found incompatible module
```

I guess this is rather an issue with my system and yarn itself, but I wasn't sure so I thought it may be wort submitting.

**Comment by benweet** [comment]
As the error message says, just upgrade your node to version >=6.9.2.
