### ISSUE TITLE
Can't sign into my Google account.

### ISSUE THREAD

**Issue by JuneYubin** [benweet/stackedit#1159]
I made a yearly donation via monetize.js and tried to sign into my Google account. Both accounts share the same mail address.

Whenever I click "Sign in with Google":
1. New window with Google sign in form opens.
2. I type in my information and click on "Sign in".
3. The window closes itself.
4. Nothing changes at Stackedit.

The weird thing is that Google doesn't ask me to grant permission for the app. So now I'm kinda confused whether this is a Google or Stackedit issue.

Please help, thanks!

**Comment by benweet** [comment]
The v5 won't bring you to the MonetizeJS website as PayPal is replacing MonetizeJS.

However, if you've signed in on https://monetizejs.com/, the v5 should detect it. Please let me know if it doesn't.

**Comment by JuneYubin** [comment]
This is what happens when I try to sign into my Google account:
https://www.youtube.com/watch?v=2hHp1pM7FT8

The sync works with v4, but with v5, nothing happens...

**Comment by benweet** [comment]
Ok I misunderstood the issue. Can you provide the version of the browser you're using ?

**Comment by benweet** [comment]
Can you revoke StackEdit access to your Google account here and try again: https://myaccount.google.com/permissions

**Comment by JuneYubin** [comment]
Something's changed! 

After revoking access and signing in again, Google actually asked me to grant access which didn't happen before.

But the issue is still there. I click "Sign in", a new window appears and disappears again. But I'm still not signed into Google.

**Comment by JuneYubin** [comment]
Okay, my console tells me this:

<img width="1671" alt="bildschirmfoto 2017-11-14 um 21 33 48" src="https://user-images.githubusercontent.com/16415014/32803389-acf1ef04-c983-11e7-9da6-3c70d2592c8c.png">

**Comment by JuneYubin** [comment]
Omg, I just found out why I couldn't log in... I had to activate my Google Plus profile. Now I can finally log in!

**Comment by benweet** [comment]
Glad to hear that!
