### ISSUE TITLE
[BUG] Failed to add photo from google photos

### ISSUE THREAD

**Issue by Xuanwo** [benweet/stackedit#1161]
### Reproduct steps:

1. Link your google photo account.
2. Choose a photo to upload

### Expect:

phoho been added.

### Exactly:

nothing happened, and a warning showed in console:

![image](https://user-images.githubusercontent.com/5351546/32988685-0739f8da-cd44-11e7-9c3d-47b4b4c33851.png)

**Comment by benweet** [comment]
Should be fixed now.
