### ISSUE TITLE
Unable to open Stackedit anymore

### ISSUE THREAD

**Issue by SchoolGuy** [benweet/stackedit#1162]
Hi benweet,
your current version (5.2.4) is not compatible with my Desktop Firefox 57.0, Edge and Chrome (same machine) are fine. Also the current Android Play Store Firefox (57.0) is fine with 5.2.4. I am using Windows 10. Your website ([https://stackedit.io/app](https://stackedit.io/app)) is displaying just the logo with the site-title "StackEdit". Version 4 works fine, previous versions were working also like a charm.

Regards,
SchoolGuy

**Comment by benweet** [comment]
I'm not able to reproduce this. Can you clear your local storage, your indexed DB and see if it's better?

**Comment by SchoolGuy** [comment]
I cleared local storage via third point in the main menu and there deleted the cookies and clicked the button with clear website cache. This brought nothing, also a browser restart after this achieved nothing. (German version, so sorry that I cannot write you what I clicked in the English version)

**Comment by benweet** [comment]
That's probably not enough (make sure you remove the indexed DB). I don't have any problem with Firefox 57.0.

**Comment by SchoolGuy** [comment]
I also cleared indexed DB, it is still not working. The funny part is, there was no indexed DB, just a folder assigned to this site which is in the temporary folder of my profile, I deleted it. No luck either....

**Comment by SchoolGuy** [comment]
Now Firefox is showing me the following output in the console:
``` javascript
UnknownError
localDbSvc.js:22:20
TypeError: ServiceWorker script at https://stackedit.io/sw.js for scope https://stackedit.io/ encountered an error during installation.
{…}
error: "unauthorized"
reason: "user_not_authenticated"
status: 401
__proto__: Object { … }
authorize:8:30
<anonym>
https://monetizejs.com/authorize:8:30
```

**Comment by SchoolGuy** [comment]
For all the Googlers who are visiting. I fixed it with a **complete** reset of Firefox.

**Comment by jkyeung** [comment]
@SchoolGuy - what do you mean by "complete reset of Firefox"? Sorry for being clueless, but what steps does that entail?

**Comment by SchoolGuy** [comment]
@jkyeung I deleted alle Folders/Registry, restarted my Computer, then feshly installed Firefox and added my Firefox-Sync Profile.
