### ISSUE TITLE
Underbrace in StackEdit 5 not working

### ISSUE THREAD

**Issue by SchoolGuy** [benweet/stackedit#1163]
Hi benweet,
your current StackEdit-Version is not rendering the command `$\underbrace{Text}_{Text}$`. I am not able to fix this via custom settings or similar approaches. I tried your app on Windows 10 (Firefox, Edge, Chrome) and Android (Firefox, Chrome) nowhere it is working. It would be nice if you could create a hotfix for this.

Regards,
SchoolGuy

**Comment by benweet** [comment]
The v5 uses [katex](https://github.com/Khan/KaTeX). I guess you should open a ticket there.

**Comment by SchoolGuy** [comment]
In my eyes there is a high posibility that you have misconfigured your webserver: [https://github.com/Khan/KaTeX/issues/908](https://github.com/Khan/KaTeX/issues/908). If not then I will open a ticket on the katex repo.

**Comment by SchoolGuy** [comment]
@benweet Is this checked? In the referenced issue it shows that this feature is working.

**Comment by benweet** [comment]
Yeah it must be a bug in StackEdit.
