### ISSUE TITLE
Formatting inside code block

### ISSUE THREAD

**Issue by Dimpl** [benweet/stackedit#1164]
In the left panel, additional formatting appears inside multi-line code blocks (````). It is correct in the right panel.

For example
Expected:
\````
one_two_three
\````

Actual:
![untitled](https://user-images.githubusercontent.com/2556805/33005103-0a4aefc6-ce10-11e7-9924-c125d39a2d1d.png)

**Comment by benweet** [comment]
Please try with three ticks (```).
