### ISSUE TITLE
Is there a way to apply CSS to the preview panel?

### ISSUE THREAD

**Issue by theoryshaw** [benweet/stackedit#1166]
Is there a way to apply CSS to the preview panel?

I tired to use that...

![image](https://user-images.githubusercontent.com/507113/33037013-d7db833a-cdf5-11e7-8d7f-635a152ddc39.png)

**Comment by benweet** [comment]
Duplicate.

**Comment by theoryshaw** [comment]
https://github.com/benweet/stackedit/issues/137
