### ISSUE TITLE
[Question] Need help to integrate Mathjax

### ISSUE THREAD

**Issue by kamlekar** [benweet/stackedit#1169]
I wrote an article on Stackedit.io using Math formula symbols like `$\implies$`. I suppose that is MathJax. 

When I publish/export my article, I am unable to get this Mathjax symbols. I suppose I need to add few js plugins and css. Please point me how to include them.

PS: I have seen this github repo in deep. Still can't figure it out.

**Comment by benweet** [comment]
Not a bug nor a feature request.
