### ISSUE TITLE
Pasting over selection skips cursor

### ISSUE THREAD

**Issue by opatut** [benweet/stackedit#1170]
Using v5 at https://stackedit.io/app

**Steps to reproduce**
- write some text, e.g. `foo bar baz`
- copy something into clipboard, e.g. `nom` (length matters!)
- select a piece of the written text, but 
  * either by clicking at the end and dragging backwards
  * or by moving the cursor to the end, holding shift and moving backwards
- paste "over" the selection (Ctrl-V)

**Expected behaviour**
- the selection is replaced with the clipboard
- the cursor is at the end of the pasted part

**Actual behaviour**
- the selection is correctly replaced with the clipboard (good!), but
- the cursor is N characters after the end of the pasted part, where N is the length of the *replaced* (selected) piece of text

(Note that this is indeed a different bug from #818, though maybe related)

**Comment by benweet** [comment]
Shoud be fixed in v5.8.
