### ISSUE TITLE
avoid auto github sync

### ISSUE THREAD

**Issue by rajanand** [benweet/stackedit#1176]
I have markdown document which is synced with google drive and github [repo](https://github.com/rajanand/notes/commits/master). There are several commits created in github as and when I edit the document in stackedit. Is there any option to manually sync once I am done with the editing?

**Comment by rajanand** [comment]
There is a feature to publish manually instead of auto synchronize. This issue can be closed.

**Comment by JohnTube** [comment]
Hi @rajanand 
Could you point me to this option where auto-sync can be disabled?

**Comment by kabeleced77** [comment]
As a workaround I added following custom setting:
`autoSyncEvery: 3153600000000`

This will now automatically sync every 100 years instead of default every 90 seconds.
