### ISSUE TITLE
error Command failed with exit code 137

### ISSUE THREAD

**Issue by mashirozx** [benweet/stackedit#1177]
Here when install it, it shows:
```BASH
root@mine:/var/www/node/stackedit# yarn install
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ gulp build-prism
[23:22:21] Using gulpfile /var/www/node/stackedit/gulpfile.js
[23:22:21] Starting 'build-prism'...
[23:22:21] Finished 'build-prism' after 114 ms
Done in 1.65s.
root@mine:/var/www/node/stackedit# yarn start

yarn run v1.3.2
$ node build/dev-server.js
> Starting dev server...
Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
On Ubuntu 17.04, with:  nodejs v8.9.1; yarn 1.3.2; npm 5.5.1

Sorry, I'm new to Node, and the official site had a bad connection in my country, so I need to install StackEdit locally... Thanks,

**Comment by mashirozx** [comment]
P.S. Someone said it's caused by the memory limit of the machine :(
Is that true? My server has 1G RAM, is it enough? 😢

**Comment by benweet** [comment]
That’s right, this is provoked by linux’s oom killer. Try to increase the ram or the swap.

**Comment by thinsoldier** [comment]
How much should it be increased to id 1GB is not enough?

**Comment by mashirozx** [comment]
@thinsoldier I tried a 4 GB machine, still not enough :-/

**Comment by thinsoldier** [comment]
@mashirozx I encountered the error while running the new vue-ui which uses some kind of server to server its gui and then webpack dev server to server my project. At 512 megs the dev server failed to start, even with the vue-ui gui turned off. With yarn instead of npm at 512 megs both servers started but if I navigated within the vue-ui gui site the dev server would crash. At 1GB I would see errors mentioning memory in the terminal of the dev server but it wouldn't crash. It seems that 2gb is enough for me but I think the switch from npm to yarn might have something to do with it.

**Comment by deXterbed** [comment]
Thanks guys, i needed to increase the swap size!

**Comment by margox** [comment]
In addition, you can check if there are other CSS styles that override the font style of the editor text.

**Comment by quietseditionist** [comment]
I got this when compiling an Angular 5 app, just changed the memory on my Docker settings to 2GB and that did the trick.

**Comment by Frank-686** [comment]
我虚拟机给了8G内存 还是会报错 请问有解决方案嘛

**Comment by omeryousaf** [comment]
> I got this when compiling an Angular 5 app, just changed the memory on my Docker settings to 2GB and that did the trick.

On mac, i had to increase the space allocation for a VirtualBox (one of the tools through which docker is orchestrated on a mac) instance from 1024MB storage limit to 2048MB. I followed the way described in https://stackoverflow.com/a/36982696/4997994.

**Comment by LeulAria** [comment]
check your ram if it's used by other things
htop or another tool and kill unused processes
