### ISSUE TITLE
about the link open in _blank

### ISSUE THREAD

**Issue by xuanfeng** [benweet/stackedit#118]
Now all the link are open in current page , how to change them with open in new page?

**Comment by franzau** [comment]
I added the extension
userCustom.onPreviewFinished = function() {
    $('#preview-contents a').attr('target','_blank');
}
as benweet suggested.
It worked a charm at first, but at some point my links in StackEdit lost their _blank attribute.

I have tried with new documents, have toggled the CustomExtentions button in Settings, but nothing happens.
Any idea? thanks

**Comment by franzau** [comment]
Actually, the extension does add the _blank attribute - the attribute is there if I inspect the source code in the right window (iFrame).
But it seems that the _blank attribute is stripped away when I click the  HTML-code button or publish the HTML on a file.
Is there anything that I can modify? Thanks in advance
