### ISSUE TITLE
Identify code that could benefit from `async` / `await`

### ISSUE THREAD

**Issue by Zearin** [benweet/stackedit#1182]
It looks like there are several people who love StackEdit and want it _so badly_, but are having some performance issues when they use it for projects that are larger than simple testing can reliably reproduce.

I think a good portion of these performance issues would go away if you identified bottlenecks, and rewrote their functionality to leverage the new `async` and `await` keywords.  (These keywords were added to JavaScript because there was demand for them, after all.)

**Comment by benweet** [comment]
I’m afraid performance issues are related to dom not JavaScript itself.
