### ISSUE TITLE
V5 Does Not Open Existing Markdown Files without StackEdit Metadata?

### ISSUE THREAD

**Issue by seamlik** [benweet/stackedit#1183]
Using v5.3.0, I couldn't open any existing Markdown files in my Google Drive. The editor simply complained

> Could not open file `file-id`

I do notice that the Markdown files generated by StackEdit itself have a special ending like

> `<!--stackedit_data:`
> `file-id`
>`-->`

So if StackEdit V5 is never supposed to work with any other file editor, I guess I'll refrain from using it. I sincerely hope I am wrong about it. This editor is an awesome work.

**Comment by benweet** [comment]
I think it's a matter of permission. You can give StackEdit full access permission by re-adding the Google Drive account in the sync/publish menu.

**Comment by seamlik** [comment]
No I do not believe it is a matter of permission, since I can open files created using StackEdit but not those pure Markdown files (i.e. without StackEdit's metadata at the end of the file.

And I also don't believe closing the issue immediately solves anything.

**Comment by seamlik** [comment]
Hmm, just confirmed the problem was fixed. Thanks for the great work!
