### ISSUE TITLE
Sign in vs Synchronize

### ISSUE THREAD

**Issue by rubaboo** [benweet/stackedit#1184]
Could you provide some explanation about what the login (Sign in with Google) feature provides (v5).
* Where can I see StackEdit data that gets stored in my Google account?
* From what I can see, all my folders and files come back once I sign in. So synchronization to GitHub is not really necessary, correct?

**Comment by writexavier** [comment]
v4:
Synchronize -> Save on Google Drive -> Setup Autosync
"AutoSync feature automatically saves all documents to your  Google Drive account and keep them synchronized."

v5:
Synchronize -> Save on Google Drive - no Autosync option :`( 

Can we please have the Autosync feature in v5?

Having a directory where the actually plain text files were being stored was an extremely important feature of v4.

**Comment by benweet** [comment]
- "Sign in with Google" will synchronize the whole workspace using Google Drive app data (you won't see the data, but you can see the space it's using in Google Drive>Settings>Manage apps).
- GitHub/Google Drive/Dropbox synchronization will only sync a single file in your workspace.

You probably want to sync your whole workspace for convenience and safety. Syncing a file is for specific use cases like sharing or integrate into a build chain.

Also note that you can create a synced workspace from a Google Drive folder which is also a good choice for portability.

**Comment by writexavier** [comment]
This is awesome!  Thank you sir.  I will be donating.

**Comment by RoyiAvital** [comment]
Any chance having "Workspace" in Dropbox?

**Comment by RoyiAvital** [comment]
@benweet , It seems there is issue with the Dropbox Sync.

It seems you can only Sync ones and then you can not load files from the Application folder (Restrict Mode).

**Comment by alexgreen** [comment]
> Also note that you can create a synced workspace from a Google Drive folder which is also a good choice for portability.

How can I do this? 
I'm currently syncing app data to a google drive account but I don't see any folder-level sync options.
