### ISSUE TITLE
Formatted code blocks should not auto-wrap code

### ISSUE THREAD

**Issue by KOGI** [benweet/stackedit#1189]
Code blocks should either stretch the document width or render horizontal scroll bars (or at least a way to set that option somewhere). The current word-wrapping makes code examples messy when rendered.

(maybe something like ` ```javascript-wrap` and ` ```javascript-no-wrap` ?)

Bad: ![clipboard03](https://user-images.githubusercontent.com/1231996/34582362-6e4777d2-f148-11e7-9c5c-d2c1d12c545e.jpg)

Good: ![clipboard04](https://user-images.githubusercontent.com/1231996/34583400-7b2a8792-f14c-11e7-8e94-b5341ed5e984.jpg)

**Comment by benweet** [comment]
Please try with the v5 and create a new ticket if it's not fixed.
