### ISSUE TITLE
Question on the file history

### ISSUE THREAD

**Issue by ferdossi** [benweet/stackedit#1191]
Hi, 
This is not a bug, just  a question.
If I synchronize Stackedit with my google account, that means all files will be saved with history in my google drive.
Is there a way to configure the number of versions in the past or their age that I want to keep in history? or will it grow endlessly? Can I remove any archived file at all?

In fact how much KB does it consume?
Thx

**Comment by benweet** [comment]
No, I don't think you can configure that. According to Google:

> Google Drive automatically purges (or "prunes") older revisions in order to optimize disk usage.

https://developers.google.com/drive/v3/web/manage-revisions
