### ISSUE TITLE
V4 to V5 migration

### ISSUE THREAD

**Issue by philuser** [benweet/stackedit#1193]
Does not work with Firefox. Display blocked with only the StackEdit logo in V5 and firefox 57.0.4 (64-bit) (no active extension) in linux Suse tumbleweed.

Works with chromium, but no display of type icons
```
          <i class="icon-file"></i> Create a document`
```
The[TOC] label does not work

The couchdb synchro would be really relevant ;)

**Comment by benweet** [comment]
Hi,

Icons and TOC are not supported anymore in the editor, they were not portable anyway. But you can still play with templates if you want custom things in your exports.

CouchDB will be reintroduced soon as a provider for workspace synchronization.

No problem with Firefox 57.0 on OSX. I won't be able to test and fix the app on every OS, sorry.. Feel free to create a PR if you find anything.
