### ISSUE TITLE
Sponsorships from monetize.js aren't available in Version 5

### ISSUE THREAD

**Issue by acsrujan** [benweet/stackedit#1195]
Updating to latest version (from Stackedit 4 to stackedit 5), I can no longer use my monetize.js to sign in.
Couldn't find any notes related to it. Could you please help with it?

**Comment by rhan-mentad** [comment]
Second this, I used a hotmail address since my gmail one didn't work with moentize.js back in v4.

**Comment by benweet** [comment]
Everything should be fine if you sign in on https://monetizejs.com.
