### ISSUE TITLE
Stackedit5 russian latex

### ISSUE THREAD

**Issue by PolyProgrammist** [benweet/stackedit#1197]
It breaks with some text in russian, for example, this:
$привет$

gives the error:
KaTeX parse error: Expected 'EOF', got 'п' at position 1: п̲ривет

Maybe it's the same https://github.com/benweet/stackedit/issues/1194

**Comment by PolyProgrammist** [comment]
Also the next example works in stackedit4 and doesn't work in stackedit5:
\begin{equation}
n
\end{equation}

Maybe need to worry about compatibility

**Comment by benweet** [comment]
Should be fixed.
