### ISSUE TITLE
StackEdit 5 doesn't format tables

### ISSUE THREAD

**Issue by rbondi** [benweet/stackedit#1200]
Issue #920 says v5 has table formatting, but I don't see any table formatting command, or auto formatting (sorry if I missed it)?

**Comment by benweet** [comment]
In the v5, there is a table button in the navigation bar.

**Comment by rbondi** [comment]
Hi Benoit,

That doesn’t fix the feature request, which is to **format** the ASCII of a
table - to under spaces and hyphens to make all the pipe symbols of each
column be underneath each other.

Kind regards, |r:b:
