### ISSUE TITLE
Google Photos Integration Not Working

### ISSUE THREAD

**Issue by jimholmes** [benweet/stackedit#1201]
In V5 I'm unable to add images using the "Open from Google Photos" option.

Repro:

0) Add Google account under main menu. Successful: Workspace shows "Synced"
1) Open document
2) Add some plain text
3) Click Image button on Toolbar
4) Click Add Google Photos account on resulting dialog, follow steps to select one of the several Google accounts I have.
   (Note: Got no confirmation whether or not this was successful.)
5) Click Open from Google Photos in same dialog. 

Expected: Photos page should open, allowing me to select (and/or upload) an image

Actual: Image dialog disappears. Nothing else happens.

100% reproducable, both on Chrome and Firefox for OSx.

**Comment by benweet** [comment]
Should be fixed in v5.6.
