### ISSUE TITLE
Custom default content does not appear

### ISSUE THREAD

**Issue by brutalpixie** [benweet/stackedit#1202]
The custom default content defined in settings doesn't not appear in the document created, and the "default" is greyed out with no option to change it.

This is a problem for us, as it adds time to the workflow, and in the prior version of StackEdit was simple to change. Now it's super unclear where the editor is drawing default content from, and thus where to change it is also unclear.

**Comment by benweet** [comment]
You should have something like that in the "Custom settings" tab :

```yaml
newFileContent: Hello!
```

Then, you should have "Hello!" every time you create a new file in the file explorer with the top-left corner button.
