### ISSUE TITLE
editor will not load; `Uncaught SyntaxError: Invalid regular expression...`

### ISSUE THREAD

**Issue by aaronduino** [benweet/stackedit#1203]
I cannot access https://stackedit.io/app on my computer (I've tried both chrome & firefox).

In the developer console, I get the following error:

```
Uncaught SyntaxError: Invalid regular expression: /([ 
	]+)|(%[^
]*[
]|[!-\[\]-â€§â€ª-íŸ¿ï¤€-ï¿¿]|[ï¿½-ï¿½][ï¿½-ï¿½]|\\verb\*([^]).*?\3|\\verb([^*a-zA-Z]).*?\4|\\[a-zA-Z@]+|\\[^ï¿½-ï¿½])/: Range out of order in character class
    at new RegExp (<anonymous>)
    at Object.81../ParseError (katex.js:1324)
    at a (katex.js:14)
    at katex.js:22
    at Object.82../Lexer (katex.js:1407)
    at a (katex.js:14)
    at katex.js:22
    at Object.86../MacroExpander (katex.js:2175)
    at a (katex.js:14)
    at katex.js:22
81../ParseError @ katex.js:1324
a @ katex.js:14
(anonymous) @ katex.js:22
82../Lexer @ katex.js:1407
a @ katex.js:14
(anonymous) @ katex.js:22
86../MacroExpander @ katex.js:2175
a @ katex.js:14
(anonymous) @ katex.js:22
109../Parser @ katex.js:11696
a @ katex.js:14
(anonymous) @ katex.js:22
1../src/ParseError @ katex.js:54
a @ katex.js:14
e @ katex.js:36
(anonymous) @ katex.js:36
(anonymous) @ katex.js:1
(anonymous) @ katex.js:1
n @ bootstrap 83007fbbb7c6aa2b58de:54
(anonymous) @ app.543ea23a861044e8f056.js:8226
n @ bootstrap 83007fbbb7c6aa2b58de:54
(anonymous) @ app.543ea23a861044e8f056.js:7817
n @ bootstrap 83007fbbb7c6aa2b58de:54
(anonymous) @ app.543ea23a861044e8f056.js:8625
n @ bootstrap 83007fbbb7c6aa2b58de:54
window.webpackJsonp @ bootstrap 83007fbbb7c6aa2b58de:25
(anonymous) @ app.543ea23a861044e8f056.js:1
```

Here's a screenshot:
<img width="1280" alt="screen shot 2018-01-14 at 10 55 23 pm" src="https://user-images.githubusercontent.com/16829510/34930402-1bb99c64-f97e-11e7-852c-27b81bcf9765.png">

Thanks for all your work making stackedit. I use it all the time and I'm sure I'm just the unlucky duck trying to use it during a broken build

**Comment by benweet** [comment]
I can't reproduce this. Can you tell me about your environment ? (browser/OS versions)
Also, can you try with a private navigation tab ?

**Comment by aaronduino** [comment]
I cannot get stackedit to work on any of my devices, but it works for my friends' devices. (I must be one of those technologically cursed people spoken of in xkcd)

I'm closing this since it seems to be 100% on my side.

Thanks for stackedit, and I apologize for the false alarm.
