### ISSUE TITLE
V4 -> V5 Migration Guide?

### ISSUE THREAD

**Issue by KyleMit** [benweet/stackedit#1205]
With the deprecation of V4, is there any official documentation / release notes as how to how migrate settings to V5?

The settings menus are pretty different, and without the GUI, I'm not sure what magic strings to include to preserve previous settings (unless those features have just been deprecated).  

### [Version 4](https://stackedit.io/editor) Settings
![image](https://user-images.githubusercontent.com/4307307/35049493-321abde8-fb6e-11e7-920f-8c48fb0dd324.png)

### [Version 5](https://stackedit.io/app) Settings
![image](https://user-images.githubusercontent.com/4307307/35049505-3c1826c8-fb6e-11e7-847f-1f4616644111.png)

----

In particular, I'm looking for ways to Disable the **HTML Sanitizer**, Specify the **Syntax Highlighter**,  and add custom **UserCustom** Extensions

**Comment by benweet** [comment]
These are not configurable anymore, mostly for security concern. Also as of v5, Prism.js is the only syntax highlighter available to reduce the overhaul complexity and increase the performance.

**Comment by baflo** [comment]
According to #569 one could add PlantUML extension with the UserCustom extensions. Is there a way in the new version?
