### ISSUE TITLE
Error occur when export as PDF

### ISSUE THREAD

**Issue by nypgand1** [benweet/stackedit#1206]
I'm a sponsor who loves the template of StackEdit 4.3.21, but  I got this error since yesterday:
> Error when trying to generate PDF: Bad Request

And even got the same error after switching to v5.6.5
> HTTP error 400.

Is there anyone who knows what can I do?

**Comment by alfredbuehler** [comment]
Same problem here. My sponsorship is valid until April.

**Comment by benweet** [comment]
Can you try to replace `http://localhost/` with `https://stackedit.io/` in the PDF template ?

**Comment by nypgand1** [comment]
@benweet It works. Thank you.

**Comment by devEngine** [comment]
I hate to chime in here after what appears to be a closed bug, but I'm getting the same error today.  

As far as I can tell, the PDF template reads https://stackedi.io/ . Unfortunately, I appear to be having this same issue (I believe my sponsorship is valid for some time as I just signed up last week, but I could be wrong).  Any suggestions would be much appreciated.
