### ISSUE TITLE
Max text length in StackEdit 5?

### ISSUE THREAD

**Issue by hautonjt** [benweet/stackedit#1208]
I've migrated a rather long document over from StackEdit 4 over to StackEdit 5, and I've been noticing that the text in the document is being cut off at exactly 150,000 characters. Is this a new undocumented character limit?

**Comment by GAZ082** [comment]
I'm having an editor with this same limit!

**Comment by benweet** [comment]
There has to be a limit. Maybe 150,000 is not enough. What would you suggest ?

**Comment by GAZ082** [comment]
1 MB? other editors seem not to have such small limitation.

**Comment by hautonjt** [comment]
I don't think having a limit is much of an issue; I just didn't expect the limit to have changed from StackEdit 4 to 5. If I didn't realize I had a backup I would have lost a significant amount of data. I don't know what the limit in StackEdit 4 is, but I think that StackEdit 5 should have the same limit as the previous version so that migrating over would not cause a loss of data.

Since the limit is too small for me right now, I'm running a local copy with the limit increased instead.

**Comment by linquize** [comment]
Do you already have a lot of markdown doc?  localStorage has limit of around 5-10MB

**Comment by benweet** [comment]
Just increased it to 250KB. I don't think a text file would be more than that anyway.

**Comment by WattanaGaming** [comment]
> I don't think a text file would be more than that anyway.

Surely you have never read Minetest's lua_api.txt. That thing is huge, nonsensically huge.
