### ISSUE TITLE
Paypal error for sponsorship

### ISSUE THREAD

**Issue by flagnico** [benweet/stackedit#1210]
I tried to buy a sponsorship to export to doc, but I have since yesterday a Paypal error : please try again later!
Can you check it please?
Thanks

**Comment by localjo** [comment]
Same. Unfortunately can't use StackEdit for my needs because I can't sponsor. :(

**Comment by peter-lillie** [comment]
Yeah I am having that issue right now! I want to send it to a PDF because for some reason when I publish to GitHub Katex is not rendering no matter what format I use :(

**Comment by benweet** [comment]
Should be fixed now.
