### ISSUE TITLE
General Questions: Is there a StackEdit community and What Android App do folks use?

### ISSUE THREAD

**Issue by iwyatt** [benweet/stackedit#1213]
Hello - sorry for using issues comment for general questions, so if there is a better place, please point the direction.

1) Is there a stackedit community where I can interact with other users and enthusiasts for the purpose of asking general questions, swapping tips, and helping new users adopt the tool, and working collaboratively on pull requests?

2) What Android application do members of the stack edit community prefer to use to read or write notes they've stored in the stackedit google drive (or dropbox drive)?

Thanks.

**Comment by SchoolGuy** [comment]
1. Mainly to my knowledge github is the only way of communication. If @benweet is ok with it we could open a gitter chat or open a discord server.
2. I use Firefox and open the website. It is working great with my tablet and smartphone.

**Comment by benweet** [comment]
I've setup a discourse server which I plan to use as a wiki:
https://community.stackedit.io/

I'm open to other suggestions if it doesn't fit your needs.

**Comment by iwyatt** [comment]
Thanks! I reposted the Android question above in the community.
