### ISSUE TITLE
Katex Not Rendering

### ISSUE THREAD

**Issue by peter-lillie** [benweet/stackedit#1217]
Hey there! So, when I publish to <a href="https://github.com/peter-lillie/Calc1VirtualNotebook/blob/master/Calculus%20I.md">GitHub<a> from StackEdit, the math rendering breaks :(

<b>In StackEdit</b>
![capture1](https://user-images.githubusercontent.com/26393480/35547746-f4fc3b8c-0548-11e8-8f8d-f5d247b7e222.PNG)

<b>In GitHub</b>
![capture2](https://user-images.githubusercontent.com/26393480/35547751-f91d6614-0548-11e8-9587-67ccd7925740.PNG)

I have tried all of the formats and none of them seem to work. Maybe I am missing somehthing, but I have not changed any of the default settings. I also tried downloading and uploading all the availible formats, but that did not work either. 

Any help would be greatly appreciated.
Peter

**Comment by SchoolGuy** [comment]
Math rendering is done by katex with stackedit, Github has only plain markdown without the katex plugin, so the rendering does not work while looking at the file on Github.

**Comment by peter-lillie** [comment]
@SchoolGuy are there any workarounds that you have found?

**Comment by SchoolGuy** [comment]
No because you need a rendering script, which interprets the stuff. The only thing you could do (which is a lot of work) create a e.g. greasemonkyscript which is basicly katex. But you would then need to check if a script like katex is already included in the site. I personly have no idea without a hell of a work....

**Comment by peter-lillie** [comment]
@SchoolGuy thanks for the insight, I will have to find out something else haha

**Comment by SchoolGuy** [comment]
Ok, I guess @benweet would be thankful, if you could close the issue 😄
