### ISSUE TITLE
Everything disappeared !

### ISSUE THREAD

**Issue by lilipou** [benweet/stackedit#1218]
Hello ! 
I started to use https://stackedit.io/app a few week ago. Yesterday, I used CClean (i don't know if it's linked) and today every documents desepeared, only my files remain. I don't know if it is normal because when i go at https://stackedit.io/editor my old documents and files are always here !
I hope i could recover my documents...

Excuse my english,
Thank you in advance !

**Comment by SchoolGuy** [comment]
You will not be able to recover your documents. CCleaner is deleting files, so your CClearner deleted your documents. The files from stackedit 4 are stored at local storage while stackedit 5 is storing files in the indexed db, seems like CCleaner is deleting indexed db, but not local storage.... Hope this helps!

**Comment by lilipou** [comment]
I supposed that I should have expected it... Thanks for your answer !

**Comment by SchoolGuy** [comment]
Hm I don't know how deep your knowledge goes, but you could use the inspector tool of your browser and look what's happening. I hope that it is reasonable for you that add-ons like noscript and similar stuff is affecting the behaviour of stackedit.

**Comment by benweet** [comment]
Can you try with a private navigation tab ?
