### ISSUE TITLE
Stackedit 4:  Error when trying to generate PDF: Bad Request

### ISSUE THREAD

**Issue by petered** [benweet/stackedit#1219]
Whenever I try to generate a PDF, I get  Error when trying to generate PDF: Bad Request.  

Unlike in previous posts about this topic, my document has no images, just markdown.  It happens for any document.

This is a bit annoying because I just paid to sponsor for the purpose of generating PDFs.

**Comment by benweet** [comment]
Should be fixed. If not, please try to reset the settings.
