### ISSUE TITLE
Can't download workspace backup in Stackedit 5

### ISSUE THREAD

**Issue by GeraldNDA** [benweet/stackedit#1220]
When I click "Export Workspace Backup", the button looks pressed but nothing happens. 

I did some investigations and noticed that you create an iframe (still happens on button press) with the site with the hash "exportWorkspace=true". Navigating to this site worked, but pressing the button still doesn't download the file.

User Agent String: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0

**Comment by Ventto** [comment]
Idem and "Import Workspace Backup" opens the window to select a file but nothing happens.

Environment: 

* OS:  Arch Linux 4.16.13-1
* Firefox 60.0.1

**Comment by kennymckormick** [comment]
the same issue for me

**Comment by benweet** [comment]
Should be fixed in v5.12.
