### ISSUE TITLE
Fail to publish to blogger

### ISSUE THREAD

**Issue by zzt93** [benweet/stackedit#1223]
When publish to blogger, stack edit report `HTTP error 500`. So anyone knows why? and any workaround?

**Comment by SHZhao74** [comment]
Same problem.
Re-login, clear localStorage, and sessionStorage can not resolve it.
As I publish, console print the error msg:
```js
GET https://www.googleapis.com/blogger/v3/blogs/byurl?url=https%3A%2F%2Fshzhao74.blogspot.tw 500()
error:{code: 500, message: null}
```
I tried to paste the url and get the following responsive:
```js
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}
```

**Comment by zzt93** [comment]
I found a workaround: export markdown to clipboard and directly paste to blogger and publish post.

**Comment by benweet** [comment]
I can't reproduce this. Do you still have the issue?

**Comment by SHZhao74** [comment]
Somehow, the issue has been solved. Thanks for your responsive. 😃 👍

**Comment by zzt93** [comment]
Yes, I guess it is fixed by Blogger now.
