### ISSUE TITLE
How can I turn tex back to MathJax replace katex.

### ISSUE THREAD

**Issue by FavorMylikes** [benweet/stackedit#1225]
I have try to write some settings in stackedit v5 over the default like this below 

    pandoc:
      highlightStyle: kate
      toc: true
      tocDepth: 3
      mathJax: true

or

    pandoc:
      highlightStyle: kate
      toc: true
      tocDepth: 3
      mathJax: someurl

But it looks not work for me.
Is there any wiki page for this?

**Comment by benweet** [comment]
`mathJax` is not allowed here. You can only override the default settings which are:

```
pandoc:
  highlightStyle: kate
  toc: true
  tocDepth: 3
```

**Comment by FavorMylikes** [comment]
Thank you for your reply.
But it does not render when I use Katex syntax.

    \begin{aligned}
       a&=b+c \\
       d+e&=f
    \end{aligned}

Maybe it is my fault but I'm not sure, it copy from [Katex site](https://khan.github.io/KaTeX/function-support.html)

**Comment by FavorMylikes** [comment]
Need double $
My fault

**Comment by RoyiAvital** [comment]
KaTeX is really behind MathJaX.
It hurts Students using StackEdit.

Any chance you give us the option to use MathJaX as it used to be?

Thank You.

**Comment by petered** [comment]
You can still use old StackEdit with the url: https://stackedit.io/editor#

**Comment by RoyiAvital** [comment]
@petered , Or just leave StackEdit for other and better (Math support wise) solution.

**Comment by petered** [comment]
@RoyiAvital like what?

**Comment by RoyiAvital** [comment]
@hackmdio is wonderful!
Also using [ReText](https://github.com/retext-project/retext) and [Visual Studio Code](https://code.visualstudio.com/) with [Markdown Preview Enhanced extension](https://github.com/shd101wyy/markdown-preview-enhanced) give better Math capabilities and work offline.
