### ISSUE TITLE
Bring Back HTML to Markdown import feature from old version

### ISSUE THREAD

**Issue by robarwebservices** [benweet/stackedit#1227]
Hi all. Great product. 

I am requesting that you bring back the import from HTML (html to markdown) feature from v4. I used this quite a lot actually. 

Thanks,
Gary

**Comment by Serhiy-Shekhovtsov** [comment]
Looks like now there is no way to display a tasks list or a single checkbox. User extensions are not supported neither is HTML.

**Comment by benweet** [comment]
Fixed in v5.8.
