### ISSUE TITLE
Copy HTML to clipboard

### ISSUE THREAD

**Issue by rbondi** [benweet/stackedit#1228]
This feature has disappeared from StackEdit 5 as far as I can tell?
It was introduced in https://github.com/benweet/stackedit/issues/17.
Please bring it back!

**Comment by benweet** [comment]
There is a "copy to clipboard" button in the export dialog.

**Comment by rbondi** [comment]
Sorry Benoit:
- where is the export dialog? I simply cannot find it.
- can I only see it if I'm logged in to Google? I can't do that for work
reasons, I'm not allowed to.
- I'm sorry, but this is an example of the UI being much harder to figure
out in Stackedit 5, compared to 4. I'll send you more examples of this
later.
Kind regards, and I still love StackEdit,
|r:b:

:: :r:b: ::
