### ISSUE TITLE
Ctrl+S (or Cmd+S) should save current document

### ISSUE THREAD

**Issue by steren** [benweet/stackedit#123]
Ctrl+S on Windows and Cmd+S on Mac are associated with saving the current document in many applications, even cloud-based one such as Google Docs.

My expected behavior after having synchronised with Google Drive and hitting Ctrl+S:
Start a synchronization of the current document

Current behavior:
Open Chrome´s save HTML page dialog, which is not relevant because is downloading and saving all the application

**Comment by victorel-petrovich** [comment]
Hi,
ctrl+s does  not work on my samsung chromebook (chrome os), in order to open the dialog to choose save as .md ? Could that be implemented, along with ctrl+o?

thanks
