### ISSUE TITLE
Wrong or not enough characters count

### ISSUE THREAD

**Issue by flagnico** [benweet/stackedit#1230]
Hello, I have a problem with the characters count. In StackEdit 5, we can access the numbers of bytes in Markdown or the numbers of characters in html. But I need to know how many characters are typed in my text document. There are too many markdown bytes and the html characters are not enough. Can you add the text characters count including spaces ? (this is what html count lacks of).
Thanks

**Comment by benweet** [comment]
> There are too many markdown bytes

What do you mean by that? The `bytes` number is actually char based, see:

https://github.com/benweet/stackedit/blob/8d3c4d65b47fa3ac9135f9c85d8d9a118d2b0cfa/src/components/StatusBar.vue#L46

**Comment by flagnico** [comment]
Thanks for your answer. It seems it's ok and I was wrong. Sorry!
