### ISSUE TITLE
Render cursor position in reader view

### ISSUE THREAD

**Issue by girone** [benweet/stackedit#1234]
This is an enhancement suggestion. 

The idea is to see the cursor position not only in the left-hand side markdown editor, but also corresponding cursor position on the right-hand side reader view. This would make writing documents much easier, because one could focus only on the resulting output and be less distracted by all the "formatting" characters. 

As an enhancement of this enhancement, support for moving the cursor around in the reader view and simultaneously moving the corresponding cursor in the markdown editor would be great.

Let me know if I can be more elaborate on this suggestion.

**Comment by benweet** [comment]
Sorry I don't see where this is going. The preview panel is not meant as an editor.
