### ISSUE TITLE
Stackedit 5 much laggier on large documents than Stackedit 4

### ISSUE THREAD

**Issue by jonahdlin** [benweet/stackedit#1235]
This is a less technical issue. I've got a 15000 word document that behaves normally in Stackedit 4, but causes very large amounts of lag in Stackedit 5. I can still use it, but sometimes it takes up to 10 seconds for keystrokes to register. All my documents reach lengths like this, and I've had to move all my document-writing back to Stackedit 4.

Perhaps it's due to syntax highlighting in the editor (I've already turned off image loading in the editor), or due to the constant refreshing of the viewer (it would be nice to be able to make this lazy, like in Stackedit 4).

**Comment by benweet** [comment]
Weird, SE5 is supposed to support larger files.

What browser are you using ? Can you share a markdown file to reproduce the issue ?

**Comment by jonahdlin** [comment]
I'm using the latest version of Chrome.

Here's a copy of the file in question: https://drive.google.com/file/d/1ksAg498iOZAeoegHqDfRQ3WW_dIyq8ZP/view?usp=sharing

Feel free to mess around with it and edit if you need. It's only a copy of the real document.

**Comment by benweet** [comment]
Is it better with v5.8 ?

**Comment by jonahdlin** [comment]
It's quite a bit better now. Still a lot of lag when backspacing multiple characters (i.e. holding the backspace key down), but for typing or deleting individual characters it's a lot quicker.

It's also hardware specific. There is lag on my Chromebook, which has pretty low-end hardware, but I experience almost no lag on my more powerful home computer.
