### ISSUE TITLE
When naming a document, typing ENTER should not always close renamer textbox

### ISSUE THREAD

**Issue by atsushieno** [benweet/stackedit#1239]
It often happens in softwares and websites from non-multibyte character input languages, but StackEdit has the problem that when we switch to Japanese or Chinese input mode and enter our natural characters (Japanese or Chinese), we often have to type ENTER to choose the right candidate for alphabets-to-Chinese/Kana sequences ("commit" inputs). If we commit characters on the file name entry textbox on StackEdit, it immediately completes its (re)naming mode and hides the textbox, while we need to type more to continue.

**Comment by benweet** [comment]
Should be fixed in v5.9.
