### ISSUE TITLE
Publish to email

### ISSUE THREAD

**Issue by kaithar** [benweet/stackedit#124]
It's possibly trivial, but it would be very useful if this had the ability to publish to an email address, for emailing draft documents.
I'd imagine the best way would be to have it done as a proxy, like ssh, and just not run a public proxy for it so that there's no open relay issues.

**Comment by airjoshb** [comment]
If I had the ability to publish to email-say, open doc in a new gmail email inside of chrome, I would be using this almost every day for my publishing.

**Comment by benweet** [comment]
Closing as too old.
