### ISSUE TITLE
v5 refuses to publish to blogspot  without google plus

### ISSUE THREAD

**Issue by meoso** [benweet/stackedit#1240]
v5 refuses to publish to blogspot without google plus and i refuse to activate such.

**Comment by benweet** [comment]
What error do you have in the JavaScript console?

**Comment by meoso** [comment]
I have to redact.  Sorry for false issue, i thought i had troubleshot properly & fully but i know what was wrong: I did not use `http://` when referencing my blogspot.

i dont recall the exact error, something about i need to create google plus profile or something, then publishing would fail with 404 maybe.
