### ISSUE TITLE
since v5, v4 render issues

### ISSUE THREAD

**Issue by meoso** [benweet/stackedit#1241]
Since v5 was released, using v4 (due #1240), i have noticed many render fails.

When i paste a bunch of MD into the left pane, i am forced to place some carriage-returns (then delete them) in order to render properly.  for example:

Headings
---
will fail to render upon first paste.

Some other things refuse to render at all, no matter how i try to edit, but look correct on the left pane. particularly text with `code` within it.

**Comment by benweet** [comment]
Sorry, I can't reproduce that.

**Comment by meoso** [comment]
after further troubleshooting i believe it is when the front-matter does not have an empty-line after the last `---`

**Comment by meoso** [comment]
video showing v5 render issue (not v4): https://drive.google.com/file/d/1u0hyfvOfQFtHStXBKjh9_RnEv4LIBTeF/view?usp=sharing

**Comment by meoso** [comment]
this happens when i have custom html; otherwise it renders properly with the exception of my front-matter.
