### ISSUE TITLE
flowchart renders as code

### ISSUE THREAD

**Issue by mordrax** [benweet/stackedit#1242]
Firstly, this is a nice app, thanks for creating it.

My issue is that the example flowchart doesn't render when I copy paste it into my document. It also doesn't work when I create a new document and paste it there.
```
```flow
st=>start: Start
e=>end
op=>operation: My Operation
cond=>condition: Yes or No?

st->op->cond
cond(yes)->e
cond(no)->op
```.
```

The period at the end is because I don't know how to escape '```' to demonstrate I'm just copying the flowchart.

Version  5.7.1

**Comment by benweet** [comment]
StackEdit v5 now uses the [Mermaid syntax](https://mermaidjs.github.io/) for charts and diagrams.

Example:

	```mermaid
	sequenceDiagram
	Alice ->> Bob: Hello Bob, how are you?
	Bob-->>John: How about you John?
	Bob--x Alice: I am good thanks!
	Bob-x John: I am good thanks!
	Note right of John: Bob thinks a long<br/>long time, so long<br/>that the text does<br/>not fit on a row.

	Bob-->Alice: Checking with John...
	Alice->John: Yes... John, how are you?
	```
