### ISSUE TITLE
need for assistance in organizing couchdb data with stackedit5

### ISSUE THREAD

**Issue by philuser** [benweet/stackedit#1244]
bravo..., the new workspace management especially in synchronization with couchdb is quite remarkable.
However, this marks an important break with the previous model with stackedit4. The way data is stored, including metadata, but also the storage tree, differs radically. 
I used to make' views' (couchdb) for searching my documents via metadata, this is of course no longer possible. The new method uses several files with certain parts in encrypted mode (hach) for each document. This is much more efficient but more complex to understand, so it would be possible to communicate me (us) a documentation specifying the model of organization and storage of documents in the couchdb database.
Thank you very much for your support.

**Comment by benweet** [comment]
Please get it touch with us for commercial support.
