### ISSUE TITLE
version 5 not using mathjax but katex while version 4 uses mathjax... because of that version 5 doesnt recognize new line '\\' of course

### ISSUE THREAD

**Issue by yborges** [benweet/stackedit#1247]
When I'm using stackedit.io/app and type $r\\\b$ I get the following error:

KaTeX parse error: Expected 'EOF', got '\\\\' at position 2: r\̲\̲r

I did a little bit of research and it seems that Katex is actually an alternative for MathJax. So my guess is that MathJax is not even being used in the editor. I tried including mathjax with

<script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>

but it had no effect.

stackedit.io/editor does recognize '\\\\' without problems. There I get a message that the editor is deprecated, I guess because mathjax is being used at stackedit.io/editor because that page uses version 4 of the markup editor and not version 5 as stackedit.io/app

my question is: is this a bug? if not, then how can I make version 5 render formulas using mathjax and not katex?

**Comment by yborges** [comment]
better title

**Comment by RoyiAvital** [comment]
I wish there was an option to chose MathJaX instead of KaTeX.
I have many MD files created with StackEdit on my Drive that now are broken since KaTeX doesn't support basic features which are supported in MathJaX.

**Comment by benweet** [comment]
No plan to support MathJax in v5, sorry.

**Comment by RoyiAvital** [comment]
@benweet ,
It means it breaks compatibility of StackEdit.
I have previous files created by StackEdit which now aren't rendered at all due to the move to KaTeX.

**Comment by benweet** [comment]
Yes v5 is not backward compatible. That’s why v4 is still accessible.
