### ISSUE TITLE
Explorer bug

### ISSUE THREAD

**Issue by Yves0** [benweet/stackedit#1250]
when expand all directory，the triangle can't scroll with the directory
![](http://wx2.sinaimg.cn/large/006pLqqCgy1fozclbzrffj307i0rnaab.jpg)
![](http://wx2.sinaimg.cn/large/006pLqqCgy1fozclsavi3j307c0rmdg3.jpg)

**Comment by benweet** [comment]
Should be fixed in 5.9.
Thanks for your report.
