### ISSUE TITLE
Stuck on Title screen when opening app

### ISSUE THREAD

**Issue by dylan16hl** [benweet/stackedit#1254]
When using the app (at https://stackedit.io/app) the page shows the Stackedit logo and will not continue to the application. I am using Firefox on osx, and have tried deleting cookies and local storage and it did not help. 

This does not happen in Safari. 

Looking at the Console in Firefox, there is an error:

`Error: Can't connect to IndexedDB.`
`localDbSvc.js:33:12`

Has anyone else experienced this?

![The screen I am seeing](https://user-images.githubusercontent.com/8991101/37045667-51837454-211b-11e8-9658-17568e4338e0.png)

**Comment by jkyeung** [comment]
Yeah, other people have experienced this, and not just on Mac. Both Linux and Windows too:

https://community.stackedit.io/t/cant-run-stackedit-5-in-ff-58-02-linux/43

Why did you close this? How did you resolve it?

**Comment by dylan16hl** [comment]
The issue fixed itself. I believe I marked it closed the same day it was
fixed, maybe a day or two afterwards.
