### ISSUE TITLE
UX: Restore file is hidden

### ISSUE THREAD

**Issue by mordrax** [benweet/stackedit#1261]
The first issue I had was when stackedit 'merged' a version I was editing offline with a version that had already been changed.

Then when I went to revert from history, I couldn't find the restore button, for some reason, the title bar was minimised and so the restore didn't appear. Took me a while to figure out why.

ie. this was hidden
![image](https://user-images.githubusercontent.com/4709169/37248057-76ec0568-251b-11e8-851d-6c840ed9ff9c.png)

**Comment by benweet** [comment]
Fixed.
