### ISSUE TITLE
Cannot move files and folders in Firefox

### ISSUE THREAD

**Issue by J-Kilby** [benweet/stackedit#1265]
Using StackEdit 5.9.0 in Firefox or Firefox Developer Edition on windows 10, you cannot drag files or folders in the explorer tab.

**Comment by geckolinux** [comment]
Ahhh, so that's why it doesn't work. I thought it simply wasn't possible. I imagine it only works in Chrome?

**Comment by benweet** [comment]
Fixed in v5.10.2.

**Comment by geckolinux** [comment]
Thanks very much!
