### ISSUE TITLE
front-matter gets rendered (v5)

### ISSUE THREAD

**Issue by meoso** [benweet/stackedit#1271]
am i  doing something wrong?  take this example of front-matter, it gets rendered rather than becoming data

```
---
layout: "post"
title: "YOUR-TITLE-HERE"
tags:
- tag
- tag
published: "false"
---
```

[![Selection_756.png](https://s26.postimg.org/xgrkjerxl/Selection_756.png)](https://postimg.org/image/9ps71arqd/)

**Comment by benweet** [comment]
You have to use YAML file properties in the menu, not YAML front matter.
