### ISSUE TITLE
[Bug] Unable to render mermaid subgraph

### ISSUE THREAD

**Issue by yxliang01** [benweet/stackedit#1278]
The following mermaid code will result in rendering a normal code block instead of a flow chart.
```mermaid
graph TD
	subgraph one
	a-->b
	end
```
While it's perfectly fine to be rendered at https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcblx0c3ViZ3JhcGggb25lXG5cdGEtLT5iXG5cdGVuZCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19 .

And, the following mermaid code is rendered correctly in stackedit.
```mermaid
graph TD
	a-->b
```

I have checked, mermaid introduced support of subgraph at 7.0.5 and stackedit is using 7.1.0 .

Error message in Chrome: `TypeError: Cannot set property 'label' of undefined` at mermaidExtension.js:111

**Comment by Raekh** [comment]
Made it work with your bit of code.
1. ```mermaid on the first line
2. Removed the tabspaces, replaced them with regular spaces.

**Comment by jaune162** [comment]
Change the version of `mermaid` to `7.0.5`(not has prefix with `^`), It's ok!

**Comment by benweet** [comment]
Fixed with v5.14.10.
