### ISSUE TITLE
Chart radarStyle => standard not work in PHPword ??

### ISSUE THREAD

**Issue by LDKJJ** [benweet/stackedit#1280]
Hey to all
I want to write my radar chart with standard i make ( $xmlWriter->writeElementBlock('c:radarStyle', 'val', 'standard'); ) using PHPword chart but is not work it show a marker !
please if you have any answer help me thank you @phpword
example => https://ibb.co/gO0Eun
Best regards Saleh

**Comment by LDKJJ** [comment]
up

**Comment by benweet** [comment]
Not a StackEdit issue I presume.

**Comment by LDKJJ** [comment]
@benweet why ?

**Comment by benweet** [comment]
I don't see any relation with StackEdit in your description. Looks like you opened an issue in the wrong place (--> https://github.com/PHPOffice/PHPWord).

**Comment by LDKJJ** [comment]
this is the part addchart in phpword => PhpOffice\PhpWord\Writer\Word2007\Part\Chart.php in function writePlotArea()
