### ISSUE TITLE
PHPword add radar chart with style standard not work

### ISSUE THREAD

**Issue by LDKJJ** [benweet/stackedit#1282]
Hey i want to add a radar chart with standard type using PHPword i make ($xmlWriter->writeElementBlock('c:radarStyle', 'val', 'standard');) but is not work for me plz any answer thank you :)

**Comment by benweet** [comment]
Off-topic, again. Please open your ticket in the relevant repository, again: https://github.com/PHPOffice/PHPWord/issues/new
