### ISSUE TITLE
docker container deployment fail to sign in with google

### ISSUE THREAD

**Issue by GARENFEATHER** [benweet/stackedit#1283]
I just deployed a docker container on cloud platform, and it fail to sign in with google because of oauth link

screenshot:
![oauth failed](https://media.discordapp.net/attachments/420095259125743637/429109833203974144/UMMUUD5QL1587QD.png)

reference link: [stackedit-hasura](https://stackedit.functional56.hasura-app.io)

**Comment by benweet** [comment]
Not a bug. You need to change the client id.

**Comment by GARENFEATHER** [comment]
@benweet so where's the client id setting? any documentation about docker deployment ?

_Sent from my PRO 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
