### ISSUE TITLE
Merging of local and cloud data intended?

### ISSUE THREAD

**Issue by snospmiS** [benweet/stackedit#1288]
I already mentioned this issue as a reply to [this thread](https://github.com/benweet/stackedit/issues/1128) and just want to make sure it doesn't stay unperceived due to the fact that the original thread has been already closed.

-------

Hi there!

Is the process of merging local and cloud data together intended? 
Because, as I use StackEdit on different devices, this produces some unpleasant side effects. 

Let me give an example:

**Step 1**: Using my PC, signed in via Google, I create a new file named "_Test_" and write "_123_".
**Step 2**: StackEdit automatically synchronizes and the data is stored locally and in GoogleDrive.
**Step 3**: I open StackEdit on my tablet (signed in) and it syncs with GoogleDrive so I get my "_Test_" file which contains "_123_". Now I delete this text and instead write "_456_". After the auto-sync, I close StackEdit.
**Step 4**: Back on my PC, I open StackEdit again, and the old local "_Test_" file which still contains "_123_" is merged with the newer cloud file which contains "_456_". What I get is a new file which contains "_456123_".

As already stated, this is kind of unpleasant when editing files on different devices.

Nevertheless, I LOVE StackEdit!

Best wishes!

**Comment by benweet** [comment]
Fixed in v5.11.
Thanks for your report.
