### ISSUE TITLE
Add option to disable autonumber in v5

### ISSUE THREAD

**Issue by Bilge** [benweet/stackedit#1289]
Frustratingly, v5 tries to be clever by automatically renumbering all entries in numeric lists. This is highly undesirable because I number everything as `1.` and let the markdown parser display the correct numerals. This is preferable because otherwise inserting an item at the top of the list causes every other entry to be renumbered, which causes muddy diffs, obscuring the real change set when reviewing changes.

**Comment by benweet** [comment]
Fixed in v5.11.
