### ISSUE TITLE
Support for asciidoctor

### ISSUE THREAD

**Issue by ChrLipp** [benweet/stackedit#129]
Stackedit is great! However I would love to see support for Asciidoctor if this is possible.

You can find the parser here: https://github.com/asciidoctor/asciidoctor.js
Asciidoctor files have the extension 'adoc' by default.

**Comment by benweet** [comment]
Closing as too old.

**Comment by sjoerdspieker** [comment]
+1 for Asciidoc support

**Comment by jmfayard** [comment]
@benweet Is there a newer ticket where we could discuss the issue?
