### ISSUE TITLE
Cutting blocks of text places the cursor in an unexpected position

### ISSUE THREAD

**Issue by Bilge** [benweet/stackedit#1295]
Cutting blocks of text (CTRL+X) should place the cursor where the block was just removed from, but the cursor ends up half way in the middle of some other paragraph. I frequently cut blocks of text, and then start typing, expecting to replace the fragment that was just cut, but instead end up typing in the middle of some random part of the document. That is, I have to manually reposition the cursor after every cut operation, which is a constant source of frustration and slows down work flow.

**Comment by benweet** [comment]
Should be fixed in v5.11.2.
