### ISSUE TITLE
Secondary Google Drive workspaces do not save files

### ISSUE THREAD

**Issue by timcharper** [benweet/stackedit#1296]
If I creates a workspace the targets in existing folder, or, I have Section space Edit create a folder for new workspace for me (I don't populate the existing folder ID text box), then the folders get created, but none of the state gets saved.

When I click the synchronize button, then the clock icon/progress indicator spins forever. If I choose the "Reset application" option in the menu, and then re-sign into Google Drive, I see the workspace that I created but none of my changes are saved.

**Comment by timcharper** [comment]
Thanks for the fast response!

I do see an error in the JavaScript console, but it has to do with monetizeJs (authorization error).

<img width="553" alt="screen shot 2018-04-11 at 13 26 59" src="https://user-images.githubusercontent.com/183/38641518-1c913d52-3d8c-11e8-9abe-85a3945306ec.png">

I just tried using stack edit with my personal Google account (instead of my work Google account), and it does work. So, it seems like it might be a permissions error with my work Google account, but I have no idea how to fix it.

I've tried sharing a workspace that I created with my personal Google account with my work Google account, and then adding the workspace by specifying the folder ID in my work Google account, and this did not work. However, the workspace continues to work for my personal Google account.

**Comment by timcharper** [comment]
To be clear, the primary stackedit workspace for my work Google account works just fine.

**Comment by timcharper** [comment]
If helpful, I can record a video and send it, or, jump on a quick Google hang out session

**Comment by benweet** [comment]
> it may be because your Google Drive has a long change log. Have you tried to keep syncing for a minute or two?

**Comment by timcharper** [comment]
Yes, I have tried syncing for much longer than a minute. Also, worthy of note, the default workspace for my work Google account does work fine, and the brand-new secondary workspace does not.

**Comment by timcharper** [comment]
Okay, well, looks like it is going through the change log. I've opened up the network inspector, and it is going through **LOTS** of changes, for files outside of the workspace folder. It looks like if I leave it open for about 10 minutes, then it finally catches up.

It looks like there is no easy way to query the Google drive API such that you only get changes for the folder in which the workspace data is stored. That's unfortunate. :-(
