### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by Astuceman** [benweet/stackedit#1302]
It not work at all in firefox 59.0.2 (64 bits)
Windows 10 16299.371

I'm stuck here : https://stackedit.io/app#
![screenshot-2018-4-24 stackedit](https://user-images.githubusercontent.com/19632209/39172448-755a889e-47aa-11e8-9826-6a09634ececf.png)

work perfect on Edge and Chromium

**Comment by stefnotch** [comment]
It works for me. Try disabling all of your addons?

**Comment by Astuceman** [comment]
I found whats' wrong
It's not an addon problem

It's privacy problem, with cookies I guess
I'm surfing always in private

<img width="713" alt="capture 22" src="https://user-images.githubusercontent.com/19632209/39210619-ecc180ba-4811-11e8-9f27-6796103543e6.PNG">

Going on classic mode (save everything trough sessions) let me access to the app without problem

**Comment by stefnotch** [comment]
```
Error: Can't connect to IndexedDB.
```

It's because of this Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=781982

**Comment by benweet** [comment]
Thanks @Astuceman @stefnotch for your investigation.

**Comment by ooker777** [comment]
I don't surf in private, yet this still happens to me (FF 52 ESR) 

![](https://i.imgur.com/yiuCsHC.png)

**Comment by shawtux** [comment]
This is still not working in FF 62.0.3 (64-bit) Windows 7.

Is there some sort of workaround? 


```
Failed to register/update a ServiceWorker for scope ‘https://stackedit.io/’: Storage access is restricted in this context due to user settings or private browsing mode. runtime.js:18
[Show/hide message details.] Error: Can't connect to IndexedDB.
```

**Comment by n8henrie** [comment]
My fix for this issue in Firefox / Windows / private browsing: https://github.com/benweet/stackedit/issues/1418#issuecomment-1003629066
