### ISSUE TITLE
Is there an offline version for this?

### ISSUE THREAD

**Issue by mm-2018** [benweet/stackedit#1305]
I would like it if this markdown editor can be used as a standalone application for Windows, Mac, Linux, Android and iOS. I really love how fully featured this online application is (to the point that I believe it could replace word processors in some cases for my workflow), but I dislike that it depends on a constant connection to be used, and that it can't be used on mobile. Would you be able to fulfill this?

**Comment by benweet** [comment]
It only relies on an Internet connection the very first time you open it. Once fully loaded, it's available offline.
