### ISSUE TITLE
Code Syntax HightLight for C# not working

### ISSUE THREAD

**Issue by raytangRT** [benweet/stackedit#1306]
I run an offline stackedit@5.11.3 and see no syntax highlight for C#, and the online version do have highlight

![2018-04-30 13_49_28-stackedit](https://user-images.githubusercontent.com/30689714/39416176-82c13244-4c7d-11e8-85d4-366456f4fb77.png)

**Comment by benweet** [comment]
You should write `csharp` instead of `c#`.
