### ISSUE TITLE
Enable editing of google drive docs as markdown files

### ISSUE THREAD

**Issue by BillHoag** [benweet/stackedit#1308]
A suggested enhancement is for stackedit to be able to operate on a google drive doc as though it was plain text markdown (`.md`) file.

This would provide the following benefits:
a. Portability of edits from any machine where the user can access chrome
b. Automatic backups and revisions provided by google drive docs
c. Collaboration abilities provided by google drive docs

For collaboration, ideally, edits would be synced live in the same way google drive docs are. Minimally, it would be helpful for collaborators to be informed if their copies become out-of-date, and they could reload.

(In theory, a non-chrome browser could directly collaborate on a markdown drive doc, just not seeing the formatted markdown provided by stackedit.)

**Comment by benweet** [comment]
That's not in the roadmap I'm afraid. StackEdit used to support Google Drive realtime collaboration in some previous version but it was hard to maintain.
