### ISSUE TITLE
Blockquote within a list item doesn't get formatted as blockquote when editing, but renders correctly

### ISSUE THREAD

**Issue by peey** [benweet/stackedit#1315]
Markdown in Editor:

![image](https://user-images.githubusercontent.com/4688870/40216419-2117b698-5a84-11e8-94c7-06ed3feade04.png)

Renders as:

![image](https://user-images.githubusercontent.com/4688870/40216436-385f4bfe-5a84-11e8-9ee2-3a532e2befd2.png)

But you'll notice that for the second list item, the quote wasn't highlighted as it was for the last item.

This issue is present only when I have a quote immediately after a list item is started, e.g.

```
- > A quote
```

and not when the quote is within the list item, but it's not immediately after the list item is started, i.e.
```
- Another item
  > But the quote is here
```
works correctly.

Interestingly, it still works even if the first line in the above snippet is empty, e.g. 
```
- 
  > But the quote is here
```
works correctly.
 
The whole markdown from screenshot to reproduce the issue:

```
## Hello
- List item 1
- > A quote
 
  And something I have to say about the quote
- Another item
  > But the quote is here
  
   And something I have to say about the quote is here
```

**Comment by benweet** [comment]
No plan to fix this I'm afraid. See https://github.com/benweet/stackedit/issues/1117.
