### ISSUE TITLE
can't access old account

### ISSUE THREAD

**Issue by Tim-at-AST** [benweet/stackedit#1323]
My son used to have a **school email account** under which he belonged to *stackedit* and now he can't access it because he attends a different school.  

We are receiving charges on our credit card, but cannot log in or access the site to change any preferences.

What is the best way to proceed to cancel his old school account?

**Comment by benweet** [comment]
Hi, can you provide me with the MonetizeJS user ID you have in the payment receipt ?

**Comment by Tim-at-AST** [comment]
can i send it to you privately somehow, not in public forum?

**Comment by Tim-at-AST** [comment]
Yes, here it is:

pduke@bsalex.net <mailto:pduke@bsalex.net>

Thanks

tim

**Comment by benweet** [comment]
Yes, you can PM me on https://community.stackedit.io/u/benweet/activity.

**Comment by Tim-at-AST** [comment]
just created account under tim.at.ast . can you grant PM privileges?
