### ISSUE TITLE
Google drive app can't login to stackedit

### ISSUE THREAD

**Issue by andaag** [benweet/stackedit#1324]
I connected stackedit with google drive using the google drive ui. When clicking on it I'm asked to login, I do and nothing happens in the stackedit window.

The following error is available in the console:
```
googleHelper.js:238 Uncaught (in promise) Error: Google account ID not expected.
    at googleHelper.js:238
```

**Comment by andaag** [comment]
I tried this again and it now works. The solution was 1/2:
1. I was logged in on the wrong google apps account (my private one)
2. I logged in on stackedit.io and setup authentication there.

**Comment by abstratt** [comment]
Got the same behavior today - I too had multiple Google accounts logged in, which may have confused StackEdit.

Steps:
1 . logged in to 2 Google accounts
2.  tried to use StackEdit for the first time to open a .md file in Drive under account 1 (account 0 is the one you are redirected to when you go to a URL such as https://drive.google.com (which will redirect you to https://drive.google.com/drive/u/0/my-drive)  
3. when authorizing StackEdit, I get the error "Google account ID not expected'

**Comment by abstratt** [comment]
Opened #1470.

**Comment by throcean** [comment]
> I tried this again and it now works. The solution was 1/2:
> 
> 1. I was logged in on the wrong google apps account (my private one)
> 2. I logged in on stackedit.io and setup authentication there.

Solved.Thanks a lot.
