### ISSUE TITLE
Anchors don't work

### ISSUE THREAD

**Issue by kathrynhamilton** [benweet/stackedit#1326]
I am trying to create hyperlinks within a document by using 
* ```[Link to Section](#section)``` as a hyperlink
* ```# <a name="section"></a>Section``` as an anchor

Due to the html sanitizer (I think), the anchor `{#section}` is not recognized. I am no longer able to turn off html sanitizer.

How do I add an anchor?!

**Comment by kathrynhamilton** [comment]
Basically the same question as #859 but now html sanitizer can't be disabled.

**Comment by benweet** [comment]
Anchors are automatically added to markdown headings. Each anchor is the slugified text of its heading.

Example :

```md
[Link to section A](#section-a)

# Section A
```
