### ISSUE TITLE
Paste from word has extra "endif" text

### ISSUE THREAD

**Issue by SimonCropp** [benweet/stackedit#1327]
If i copy and paste from word basic formatting seems to work, which is awesome.

But it seems to prefix it with some weird `<![endif]-->` text

![image](https://user-images.githubusercontent.com/122666/41324603-b819d20a-6ef8-11e8-9a0c-73043e7c5075.png)

**Comment by samsarana** [comment]
For any others who run into this issue: if you're using Chrome, you can install [Paste as Markdown](https://chrome.google.com/webstore/detail/paste-as-markdown/lmelpnmpkekjahgdihfajfebaddffokl?hl=en) and then use alt-c (Windows) or option-c (Mac) as a workaround
