### ISSUE TITLE
Katex dependency update

### ISSUE THREAD

**Issue by gem763** [benweet/stackedit#1335]
Do you have any plan to update Katex dependency? Stackedit is currently using ver. 0.9.0alpha, but katex has been already released upto 0.10.0 or more.

**Comment by farleyknight** [comment]
Agreed. I'm seeing an issue with fractions because StackEdit is using an older version of Katex. It's been mentioned here: https://github.com/Khan/KaTeX/issues/824

**Comment by flxwu** [comment]
bumped in PR #1365
