### ISSUE TITLE
Unicode characters in math

### ISSUE THREAD

**Issue by RobertGoulding** [benweet/stackedit#1337]
I have a whole lot of markdown documents that use the unicode "degree" symbol in math mode (rather than the horrible LaTeX workaround ^\circ). They used to render perfectly in Stackedit; but now every one of them gives KaTeX error such as

KaTeX parse error: Expected 'EOF', got '°' at position 7: i = 58°̲ 20′

Is there any way to fix this?

**Comment by flxwu** [comment]
Unicode should be supported in kaTeX v0.10.0, bumped in PR #1365
