### ISSUE TITLE
Math won't render if there's a space next to the '$' in 5

### ISSUE THREAD

**Issue by Menci** [benweet/stackedit#1338]
```
$ 233 $ // Not Working

$233 $ // Not Working

$ 233$ // Not Working

$233$ // Works
```

In StackEdit 4 they're working but now in StackEdit 5 only the last (without spaces) works.

**Comment by benweet** [comment]
Yes, the v5 complies with the pandoc spec: http://pandoc.org/MANUAL.html#math
