### ISSUE TITLE
Paypal "not working at the moment" error

### ISSUE THREAD

**Issue by ironsalsa** [benweet/stackedit#1343]
Hey all - I'm trying to sponsor this app through Paypal transfer, and it gives me a "not working at the moment" error once I cloud through the dollar mo

# URL:
https://stackedit.io/app#

# Browser:
Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)

# OS:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

# How to reproduce
Click on the "sponsoring" link, and click any dollar amount. Paypal errors out.

**Comment by benweet** [comment]
Should be fixed now, sorry for the inconvenience. You may have to close your browser tabs and reload the app to get the update.
