### ISSUE TITLE
\tag Katex fails to render

### ISSUE THREAD

**Issue by LolnationCH** [benweet/stackedit#1352]
This should render properly with Katex : ```\tag{hi} x+y^{2x}```
This is the example from the Katex doc : [https://khan.github.io/KaTeX/docs/supported.html#annotation](https://khan.github.io/KaTeX/docs/supported.html#annotation)

However, this simply cause this error in stackedit.io : 
```KaTeX parse error: Expected 'EOF', got '\tag' at position 1: \̲t̲a̲g̲{hi} x+y^{2x}```
The same message appears using ```$``` and ```$$``` for the equation.

Is there another way to tag equation if tag is not supported?

Thanks

**Comment by flxwu** [comment]
tag comes with KaTex v0.10.0-alpha, as seen here: https://github.com/Khan/KaTeX/releases/tag/v0.10.0-alpha

We could support it by bumping KaTex (currently 0.9.0-alpha)
