### ISSUE TITLE
PDF Export not working

### ISSUE THREAD

**Issue by berkowitze** [benweet/stackedit#1357]
I have a very simple md file going:

```
# Homework 1
```

I try to export it with Styled HTML (same issue with or without TOC), but upon opening the PDF I get a "Failed to load PDF document" error; seems like the file is empty.

**Comment by nypgand1** [comment]
Same here. Need Help.

**Comment by stuart-hill** [comment]
Same here.

**Comment by NegativeZero000** [comment]
Not sure if it is pertinent here but it would be a lot easier to test and replicate the issue if you included information about your OS and browser version.

**Comment by lucasRolff** [comment]
The error that is returned is the following:

![https://snaps.hcdn.dk/2018_08_20_ys9bge6u50ches5.png](https://snaps.hcdn.dk/2018_08_20_ys9bge6u50ches5.png)

Same problem persist in Chrome and Firefox (both being latest release)

**Comment by benweet** [comment]
Should be fixed in v5.12.1. Sorry for the inconvenience.
