### ISSUE TITLE
stackedit has Uncaught SyntaxError: Unexpected token export error in brunch

### ISSUE THREAD

**Issue by shahryarjb** [benweet/stackedit#1358]
I have tried to install stackedit in brunch but I have some error. I read this [link](https://elixirforum.com/t/phoenix-and-brunch/1786) before installing Stackedit.
At first I saw a security error in this package
```
error: Processing of node_modules/indexeddbshim/dist/indexeddbshim.js failed. Error: Could not load module './CFG' from '/home/mojtaba/Desktop/shahryar/elixir/stackedit2/assets/node_modules/indexeddbshim/dist'. Make sure the file actually exists.

```
for the sake of this error I move src in the node_modules/indexeddbshim to dist, but I have  another error 

in my browser consol: 
```
Uncaught SyntaxError: Unexpected token export
```
I think this error is because of my App.js which has a error like this: 
```
export default CFG
```
It always has a error and I decide to disable indexeddbshim library, I don't have the error anymore but it doesn't work, I imported `import './emojiExtension'` in my app.js file but it doesn't work

how can I do this ?

My frameworks is Phoenix by elixir

**Comment by benweet** [comment]
Should be good with:

```
    "node": ">= 8.0.0",
    "npm": ">= 5.0.0"
```
