### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zchrissirhcz** [benweet/stackedit#1360]
➜  stackedit git:(master) npm install
npm WARN tarball tarball data for eslint@3.19.0 (sha1-yPxiAcf0DdCJQbh8CFdnOGpnmsw=) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for stylelint@7.13.0 (sha1-ER+Xttpy53XICADWu29fhpmXeF0=) seems to be corrupted. Trying one more time.
npm WARN stackedit@5.11.4 No repository field.

npm ERR! Unexpected end of JSON input while parsing near '...3.5.1","semver":"~5.4'
npm WARN registry Unexpected warning for https://registry.npm.taobao.org/: Miscellaneous Warning ECONNREFUSED: request to https://registry.npm.taobao.org/to-ico failed, reason: connect ECONNREFUSED 127.0.0.1:40131
npm WARN registry Using stale package data from https://registry.npm.taobao.org/ due to a request error during revalidation.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chris/.npm/_logs/2018-08-11T07_30_21_964Z-debug.log

**Comment by benweet** [comment]
Should be good with:

```
    "node": ">= 8.0.0",
    "npm": ">= 5.0.0"
```
