### ISSUE TITLE
I just found a real bug like circular reference!!!

### ISSUE THREAD

**Issue by FavorMylikes** [benweet/stackedit#1361]
You definitely want to reward me.
LOL
Just a half hour ago, there a file disappeared directly because of some create folder or file action.

So I check the IndexedDB in browser.

Here is the picture.

![image](https://user-images.githubusercontent.com/16064851/44084115-77a1b212-9fe8-11e8-81f3-867c504f7d0f.png)
![image](https://user-images.githubusercontent.com/16064851/44084121-7ac384f2-9fe8-11e8-81c4-51500bee62df.png)

I'm sure you'll understand what going on.

They are their respective parents object.

So, may be this could resolve some question in your issue.

**Comment by benweet** [comment]
Reproduced! Will be fixed in the next release. Thanks for your report!

**Comment by benweet** [comment]
Fixed in 5.12.
