### ISSUE TITLE
Add to KaTeX users

### ISSUE THREAD

**Issue by ylemkimon** [benweet/stackedit#1362]
Hey there, KaTeX maintainer here. Not really an issue. I'd like to ask if StackEdit would mind adding your logo to KaTeX user list? (https://github.com/Khan/KaTeX/pull/1569, preview availabe at https://deploy-preview-1569--katex.netlify.com/en/users.html) This is a really cool project! 😄

**Comment by benweet** [comment]
Please be my guest !
Here is the svg logo: https://github.com/benweet/stackedit/blob/master/src/assets/logo.svg
Let me know if I can help.

**Comment by ylemkimon** [comment]
@benweet Thank you ❤️
