### ISSUE TITLE
app won't load 

### ISSUE THREAD

**Issue by margolhe** [benweet/stackedit#1363]
Hi all, 

I would like self host stackedit, but I have some problems with load app. 

When I hit 'Start writing' on main page url go to 'http://localhost:8080/app' and I have blank page. I had tried on many combination, but without luck. 

Source of webiste 'http://localhost:8080/app'

`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>StackEdit</title>
    <link rel="canonical" href="https://stackedit.io/app">
    <meta name="description" content="Free, open-source, full-featured Markdown editor.">
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="mobile-web-app-capable" content="yes"><meta name="theme-color" content="#fff"><meta name="application-name" content="StackEdit"><link rel="apple-touch-icon" sizes="57x57" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-icon-57x57.png"><link rel="apple-touch-icon" sizes="60x60" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-icon-60x60.png"><link rel="apple-touch-icon" sizes="72x72" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-icon-72x72.png"><link rel="apple-touch-icon" sizes="76x76" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-icon-76x76.png"><link rel="apple-touch-icon" sizes="114x114" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-icon-114x114.png"><link rel="apple-touch-icon" sizes="120x120" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-icon-120x120.png"><link rel="apple-touch-icon" sizes="144x144" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-icon-144x144.png"><link rel="apple-touch-icon" sizes="152x152" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-icon-152x152.png"><link rel="apple-touch-icon" sizes="180x180" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-icon-180x180.png"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><meta name="apple-mobile-web-app-title" content="StackEdit"><link rel="icon" type="image/png" sizes="32x32" href="/icons-2e8d166bafb750685078f5ddd44d30f5/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="/icons-2e8d166bafb750685078f5ddd44d30f5/favicon-16x16.png"><link rel="shortcut icon" href="/icons-2e8d166bafb750685078f5ddd44d30f5/favicon.ico"><link rel="apple-touch-startup-image" media="(device-width: 320px) and (device-height: 480px) and (-webkit-device-pixel-ratio: 1)" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-startup-image-320x460.png"><link rel="apple-touch-startup-image" media="(device-width: 320px) and (device-height: 480px) and (-webkit-device-pixel-ratio: 2)" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-startup-image-640x920.png"><link rel="apple-touch-startup-image" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-startup-image-640x1096.png"><link rel="apple-touch-startup-image" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-startup-image-750x1294.png"><link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 736px) and (orientation: landscape) and (-webkit-device-pixel-ratio: 3)" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-startup-image-1182x2208.png"><link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 736px) and (orientation: portrait) and (-webkit-device-pixel-ratio: 3)" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-startup-image-1242x2148.png"><link rel="apple-touch-startup-image" media="(device-width: 768px) and (device-height: 1024px) and (orientation: landscape) and (-webkit-device-pixel-ratio: 1)" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-startup-image-748x1024.png"><link rel="apple-touch-startup-image" media="(device-width: 768px) and (device-height: 1024px) and (orientation: portrait) and (-webkit-device-pixel-ratio: 1)" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-startup-image-768x1004.png"><link rel="apple-touch-startup-image" media="(device-width: 768px) and (device-height: 1024px) and (orientation: landscape) and (-webkit-device-pixel-ratio: 2)" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-startup-image-1496x2048.png"><link rel="apple-touch-startup-image" media="(device-width: 768px) and (device-height: 1024px) and (orientation: portrait) and (-webkit-device-pixel-ratio: 2)" href="/icons-2e8d166bafb750685078f5ddd44d30f5/apple-touch-startup-image-1536x2008.png"></head>
  <body>
    <div id="app"></div>
    
  <script type="text/javascript" src="/app.js"></script></body>
</html>`

OS: CentOS 7.5
npm v: 3.10.10
node v: 6.14.3

npm install execute without errors 

I wonder there are any other dependencies to make to run it.

Any idea?

**Comment by margolhe** [comment]
Problem solved. 
Problem was with '__webpack_hmr' infinity loading. 

Run server on npm v.5.6.0 and node v.v8.9.4 resolved problem.

**Comment by razananisathar** [comment]
I tried running this app in node V.8.9.4.  'http://localhost:8080/app' throws error **Cannot GET /app**. What  else I have to do?
