### ISSUE TITLE
Export with Pandoc is broken

### ISSUE THREAD

**Issue by flagnico** [benweet/stackedit#1366]
Hello, 

Since 2 days, I cannot export my text with Pandoc or in PDF. The badge "sponsor" is grey (http://cloud.editocom.com/2M373A0c011y/capture280.jpg)
 
When it works, it's red!
I'm stil a sponsor user and I have the right to export with Pandoc into a Word document.
Can you help me please?
Thanks

**Comment by benweet** [comment]
Should be fixed in v5.12.1. Sorry for the inconvenience.
