### ISSUE TITLE
Easy Theming with Local CSS

### ISSUE THREAD

**Issue by sualeh** [benweet/stackedit#137]
It would be cool to use a CSS stylesheet from local storage, to make it easier for users to re-theme

**Comment by benweet** [comment]
Closing as too old.

**Comment by NetzwergX** [comment]
How would this be done in the new version 5?  `Settings->Extension->User Custom` does not exist anymore, and I could not find out how to add custom CSS / JS in those YAML files that are shown to me when trying to edit settings.

**Comment by NetzwergX** [comment]
Does this have an accompanying feature in v5, if so where can I find it, or do I need to raise a feature request for v5?

**Comment by martov1** [comment]
+1, I would like to use this too on version 5

**Comment by benweet** [comment]
V5 doesn't support custom themes at the moment but you can use a browser extension for that.
