### ISSUE TITLE
Korean typing bug

### ISSUE THREAD

**Issue by doortts** [benweet/stackedit#1376]
First, thank you for your awesome work!
Our team is trying to adopt stackedit as the main editor.
https://github.com/yona-projects/yona

But sadly, there exists a critical typing bug when to type Korean.

![korean_typing_bug](https://user-images.githubusercontent.com/520523/44722867-67d70400-ab09-11e8-856e-6d19f941b27f.gif)

When we finish a line and press enter, it doesn't change line. Just IME composing mode is ended.
Korean is a little bit different from Chinese and Japanese. When we press enter, then currently composing character are valid and showed in editor and change to new line. Space key is also same.

If this problem is fixed, I think many Korean developers and apps will use stackedit .
I hope it will be fixed.

Thank you!

**Comment by doortts** [comment]
@benweet Is there any clues? or what can I do help you?

**Comment by benweet** [comment]
Reproduced! I'll try to fix this ASAP.

**Comment by doortts** [comment]
@benweet Thank you! 👍
