### ISSUE TITLE
integrate into Github

### ISSUE THREAD

**Issue by KOLANICH** [benweet/stackedit#138]
I think it will be good to integrate this into github and make it open all .md files from here (you should contact GH developers about it).

**Comment by benweet** [comment]
Fixed in v5.

**Comment by KOLANICH** [comment]
thank you.

**Comment by ran-eh** [comment]
I could not get it to work.  Is there a blow by blow instruction doc for setup github sync?  Whatever I try, I keep getting an HTTP error 404.  Thanks!
