### ISSUE TITLE
Title, author and date in stackedit

### ISSUE THREAD

**Issue by ckesanapalli** [benweet/stackedit#1391]
Hi, I am new to the markdown and I am trying to write title, author and date 

I am trying to write like this.
```
---
title: My File
author: My name
---
```
But it is not working. I see it is yaml supported. Can anyone tell what is the right syntax.

If anyone can suggest any video or tutorial on how to write academic paper/article/report in stackedit.

**Comment by benweet** [comment]
Yaml front matter is not supported. You have to go to menu > file properties.
