### ISSUE TITLE
have never ever ever ever ever ever ever been able to use this

### ISSUE THREAD

**Issue by josejuanisaac** [benweet/stackedit#1393]
i came from google drive
i like md
as the title says, i have never ever ever ever ever been able to use this "app"
i have tried using it every few months since like 2014 or something i swear
at one point back then i was able to edit some file but drive integration was never really working...

**Comment by josejuanisaac** [comment]
console
````
Error: Can't connect to IndexedDB. localDbSvc.js:28:12
````

**Comment by benweet** [comment]
You are probably using firefox. See https://github.com/benweet/stackedit/issues/1302.

**Comment by apatrida** [comment]
This is happening in Brave (2022-March) now.
