### ISSUE TITLE
build issues: postinstall fails with prism 1.9

### ISSUE THREAD

**Issue by cpboyd** [benweet/stackedit#1411]
Log from `npm install`:
```console
Binary found at C:\Projects\GitHub\stackedit\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary is fine

> stackedit@5.13.2 postinstall C:\Projects\GitHub\stackedit
> gulp build-prism

gulp[12264]: src\node_contextify.cc:635: Assertion `args[1]->IsString()' failed.
 1: 00007FF6D6BB0205
 2: 00007FF6D6B8A176
 3: 00007FF6D6B8A241
 4: 00007FF6D6B63F9A
 5: 00007FF6D71C4102
 6: 00007FF6D71C5258
 7: 00007FF6D71C45BD
 8: 00007FF6D71C44DB
 9: 000001F000E841C1
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! stackedit@5.13.2 postinstall: `gulp build-prism`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the stackedit@5.13.2 postinstall script.
```

I've tried removing `package-lock.json` and re-running `npm install` from scratch, which succeeds...

But the resulting build gives this error when served with prism 1.15 (the original package-lock.json had 1.9):
```
Uncaught TypeError: Cannot set property 'comment' of undefined
    at Object.extend (prism.js:90)
    at Object.<anonymous> (prism.js:5392)
    at Object.<anonymous> (vendor.723162366e8d1f6b966e.js:47300)
    at n (bootstrap 0e9047d8583f52107ad0:54)
    at Object.<anonymous> (app.476a396bd6ac8bf9ab44.js:22824)
    at n (bootstrap 0e9047d8583f52107ad0:54)
    at Object.<anonymous> (index.js:1)
    at n (bootstrap 0e9047d8583f52107ad0:54)
    at Object.<anonymous> (app.476a396bd6ac8bf9ab44.js:23101)
    at n (bootstrap 0e9047d8583f52107ad0:54)
```

**Comment by woncode** [comment]
i also meet this problem, and i have try some method from #1311 issue, butt still can't solve it

**Comment by halldorel** [comment]
Also having this problem, have tried literally everything but with no luck. Old StackEdit install guides mention using bower during setup, but that's probably not related?

_I'm running npm v6.4.1, node v10.13.0 on Ubuntu 18.04.1 LTS._

**Comment by b4r** [comment]
does `npm install gulp` and/or `npm install prism` will help?

**Comment by ChrisLahaye** [comment]
@b4r I can confirm this fixed the problem for me.

**Comment by halldorel** [comment]
Using node version `v10.12.0` did it for me.

**Comment by b4r** [comment]
@ChrisLahaye nice that it worked - @halldorel interesting the version difference made it work for you. I can confirm it should work on newer installs as  `v11.3.0`

**Comment by cpboyd** [comment]
No longer having this issue with `v11.9.0` on macOS.

**Comment by Tyguy7** [comment]
I have this issue with node v10.16.3 (LTS) on Ubuntu 18.04

**Comment by sanjayabc1234** [comment]
> does `npm install gulp` and/or `npm install prism` help?

This worked form.
