### ISSUE TITLE
Checkbox not checked in HTML Export

### ISSUE THREAD

**Issue by jesperlunpet** [benweet/stackedit#1465]
When exporting a checkbox written in markdown like this:
```markdown
- [x] test
```
It will export it to: 
```html
<input type="checkbox" class="task-list-item-checkbox" disabled="">
```

As if the input was `- [ ] test`. It should export it to:
```html
<input type="checkbox" class="task-list-item-checkbox" disabled="" checked="">
```
Where the attribute `checked=""` is set.

**Comment by eralpsahin** [comment]
https://github.com/benweet/stackedit/blob/91f8cf3c10b75df65b69f9181cee8151d65a788d/src/extensions/markdownExtension.js#L155

It seems `checked` attribute does not stick to the input element created by `createElement`. I have yet to understand why.

Creating the checkbox using `innerHTML` fixes this.
