### ISSUE TITLE
Manual sync

### ISSUE THREAD

**Issue by notramo** [benweet/stackedit#1482]
Automatic sync creates too much commits on GitLab backed workspace.
There should be an option to disable autosave.

**Comment by benweet** [comment]
There is. Set `autoSyncEvery: 99999999` in the settings.

**Comment by notramo** [comment]
@benweet How does syncing work?
If there was a manual sync, does it reset the auto sync timer?
Does it detect e.g. sentences, or commas, or it can sync even a half word while continuously typing?
