### ISSUE TITLE
Google authorization page alert pops up after revoking access

### ISSUE THREAD

**Issue by alberduris** [benweet/stackedit#1496]
Yestarday, I used the _"Open from Google Photos"_ option to insert an image.

For that, the _Google_ login popped out, and I logged into my account, giving the access to my _Google Photos_ to _Stackedit_. Everything went fine.

After that, I decided that the service was not interesting for me, so I decided to **remove the access**, as I wouldn't be using it anymore.

After revoking the access from the _Google_ panel, **an alert started to pop out every few seconds** asking me to go to the _Google Authorization_ page, as follows:

![image](https://user-images.githubusercontent.com/7073086/59344423-5b294280-8d0e-11e9-85e5-f7a0873cdd37.png)

No matter what I do, the alert is still there, popping out time to time.

Tested things:
- Click on "Cancel"
- Click on the "X" to close the alert
- Giving and removing the access again
- Delete cookies
- Open/Close Stackedit
- Restart laptop

What can I do to get rid of the alert? It's almost impossible for me to right anything now on _Stackedit_.

**Comment by benweet** [comment]
With v5.14 you should now be able to remove account from StackEdit and link your account again.
