### ISSUE TITLE
Can this be embedded into another page?

### ISSUE THREAD

**Issue by joekaiser** [benweet/stackedit#150]
Great job on the editor. I feel like it is bar far the best one available.

Is there any way to embed a light weight version of this into a page? What I am looking for is a simple editor with a toolbar and a preview area, and don't have much need for the other features right now (doc sync, local storage, settings, etc..)

**Comment by jens1o** [comment]
What would be the current approach to do this, @benweet?

**Comment by benweet** [comment]
Please have a look at https://benweet.github.io/stackedit.js/.

**Comment by jens1o** [comment]
I'd need to run a version on localhost, as I will not have a persistent network connection.

My current approach would be: Host a server running stackedit locally embedded in my main application that will sync to a cloud storage as soon as I've got network access.

I really love the editor, its capabilities and if it would not be possible, I'd pretty much just rewrite everything from scratch and build my own, but just on the editor side.
