### ISSUE TITLE
Gitlab workspace sync broken

### ISSUE THREAD

**Issue by tvolodimir** [benweet/stackedit#1505]
I use Gitlab workspace. And I found issues when I created a list of documents and folders. 

Everything was going smooth until I reach 20 items in total of documents and files. I discovered that api /projects/:id/repository/tree receive 20 elements by default -
https://docs.gitlab.com/ee/api/repositories.html#list-repository-tree
Will be great to fix this 

As I understand It should work if add into fetch 'per_page ':999 at
https://github.com/benweet/stackedit/blob/da9b87620f683ff356efa71fa322a302a8fb0fa1/src/services/providers/helpers/gitlabHelper.js#L117-L123

**Comment by ProbablyFaiz** [comment]
When will this change be deployed to the stackedit.io website? I'd like to use this for a large Gitlab project I have but it doesn't sync correctly.

**Comment by FaizSurani** [comment]
@benweet Please deploy this fix as a release quickly if possible. Need it for a company project urgently, already donated $25 and happy to donate more if it can be done very soon. Thanks :)

**Comment by ProbablyFaiz** [comment]
@benweet Please deploy this fix as a release quickly if possible. Need it for a company project urgently, already donated $25 and happy to donate more if it can be done very soon. Thanks :)
