### ISSUE TITLE
!!Big Issue when using the URL insert popup

### ISSUE THREAD

**Issue by ferdossi** [benweet/stackedit#1518]
Hi,
Since the last update, there is a big issue when trying to insert a new link.

Click on the insert URL or insert image button, insert your link, click on OK=> it breaks.
Here is the error:

![image](https://user-images.githubusercontent.com/11467221/60790810-9fb7ca80-a162-11e9-83ca-58fe7ec09543.png)

**Comment by benweet** [comment]
Should be fixed in v5.14.5.
