### ISSUE TITLE
Can't sync with Google Drive after Upgrade

### ISSUE THREAD

**Issue by bbhenry** [benweet/stackedit#158]
My existing Stackedit (http) popped up a modal for upgrading to the https website. I follow the instruction, backed up my local storage and settings, upgraded to the https website and restored everything from the json file. Everything looks fine until I updated my document and need to sync with Google Drive, and it just don't work. I can't even try to import or export to Google Drive, it just times out.

I have all my documents synced to GD and none in Dropbox, so I can't really tell if that part is broken too or not. I am currently using the old Stackedit until the https issue can be resolved.

Thanks,

Henry

**Comment by johnyluyte** [comment]
For anyone who is interested, disabling "g" icon in "disconect" does not solve this problem anymore. Instead, one should uncheck the "google (1 request)"  under the "Content" item. As shown below.
![abc](https://cloud.githubusercontent.com/assets/4846501/5792611/395a063e-9f5c-11e4-8b42-79ea2985cd8f.png)
