### ISSUE TITLE
mermaid classDiagram does not render on StackEdit app

### ISSUE THREAD

**Issue by jcandan** [benweet/stackedit#1583]
Diagrams of type `classDiagram` in the StackEdit app do not render.

<img width="1673" alt="Screen Shot 2019-12-28 at 1 53 10 PM" src="https://user-images.githubusercontent.com/2332648/71548244-7ccfdb80-2979-11ea-8b50-1352606ad385.png">

Example taken from [mermaid.js](https://mermaid-js.github.io/mermaid/#/classDiagram?id=class-diagrams):

There are several mermaid.js issues ([#749](https://github.com/mermaid-js/mermaid/pull/749), [#748](https://github.com/mermaid-js/mermaid/issues/748), [#859](https://github.com/mermaid-js/mermaid/issues/859)) that deal with this functionality, but none here in the StackEdit issue queue.

I have not spun up a local instance to check into this, but I do see that the `classRenderer` is imported and configured in [mermaidExtension.js](https://github.com/benweet/stackedit/blob/master/src/extensions/mermaidExtension.js). Not sure what else is missing.

**Comment by aminzai** [comment]
Hi, I create a pull request (https://github.com/benweet/stackedit/pull/1586), I thought it can help you.

**Comment by benweet** [comment]
Fixed with v5.14.10.

**Comment by JanB1** [comment]
@benweet This seems not to have been solved, problem is still present in v5.14.10, Chrome 97.0.4692.71.
