### ISSUE TITLE
### Heading 3 not visible for some weird reason :/

### ISSUE THREAD

**Issue by joe733** [benweet/stackedit#1599]
First off StackEdit is **AMAZING**!. A big thanks to all the developers.

I'm creating some personal notes on my studies, so I just bumped into this issue...
### Heading 3 Missing!
![StackEdit](https://user-images.githubusercontent.com/38415384/75091996-5dc88100-5599-11ea-9d17-bc48cdbaa393.jpg)

But it is visible 👀 when I do this:
![StackEdit_2](https://user-images.githubusercontent.com/38415384/75092032-d6c7d880-5599-11ea-83d2-125bdf0cfe67.jpg)

Any idea why?

**Comment by sidneydemoraes** [comment]
Guess it's been fixed already. It's working fine for me.
Would you mind checking it out and closing this ticket in case it's working?

**Comment by joe733** [comment]
Hi, no the issue still persists...
I'm on Firefox 75.0
