### ISSUE TITLE
Constantly getting prompted for Google Authorization

### ISSUE THREAD

**Issue by lagerratrobe** [benweet/stackedit#1616]
I am constantly getting a message that says, 

"You are about to navigate to the Google authorization page."  

It's rather annoying.  Is there any way to make it stop?

**Comment by maryblue49** [comment]
am constantly getting a message that says,

"You are about to navigate to the Google authorization page."

It's rather annoying. Is there any way to make it stop?

**Comment by botto** [comment]
@lagerratrobe  @maryblue49  It might have to do with tracker blocking #1334

**Comment by lagerratrobe** [comment]
I don't have Ghostery installed and I can't think of what else might be preventing authorization from happening.  I'll be honest with you guys, I donated to the project and am happy to have done that, but I'm moving on.  I tried Stackedit because SimpleNote can't seem to keep things sync'd.  Now this.  I'm wasting my time trying to get work done while fighting this stupid behavior.

Best of luck figuring this out.
