### ISSUE TITLE
Mobile-friendly UI

### ISSUE THREAD

**Issue by gmarty** [benweet/stackedit#162]
StackEdit is working on mobile. However, the UI could be optimized for small screens, the main issue being the top bar taking too much space.

Also, the view panel should be removed completely. At the moment, a warning is shown when there is not enough room. The UI should use of the Viewer instead.
Then, if we do so, the viewer.html page should be listed in `cache.manifest` to allow this feature to work offline.

What do you think of these changes?

**Comment by benweet** [comment]
Closing as too old.
