### ISSUE TITLE
Where does stackedit 5 saves a workspace

### ISSUE THREAD

**Issue by brucou** [benweet/stackedit#1678]
Hi @benweet, I am a faithful user of stackedit for many years now. I unfortunately had an apocalyptic crash of my laptop and I am reinstalling everything from scractch. I would like to get back the content I was working on with stackedit, so I am wondering where could I find the workspace that stackedit saves in the browser so I can recreate it. I know there is an import/export feature, but I had not used that unfortunately...

Let me know the answer when you find the time to answer this and many thanks

**Comment by aahnik** [comment]
hi @brucou , and @benweet  I also have a close question.

When I sign in with my google account in the main workspace is automatically created and all files and comments in it are synced. 

Now there is a google drive logo beside the main workspace. 

But where exactly in google drive are my files stored? There are not visible.

I found the answer with a little exploration.

![Screenshot from 2020-10-08 11-54-41](https://user-images.githubusercontent.com/66209958/95422519-17276b80-095d-11eb-81c3-ed8566831c25.png)

Now what is this **app data folder** ?

this is documentation from [google drive API](https://developers.google.com/drive/api/v3/appdata) 

>Store application-specific data
The application data folder is a special hidden folder that your app can use to store application-specific data, such as configuration files. The application data folder is automatically created when you attempt to create a file in it. Use this folder to store any files that the user shouldn't directly interact with. This folder is only accessible by your application and its contents are hidden from the user and from other Drive apps.
The application data folder is deleted when a user uninstalls your app from their MyDrive. Users can also delete your app's data folder manually.

**Comment by aahnik** [comment]
Hi @brucou . If you had earlier signed into stack edit via google, you would be able to recover your work by signing in again.

If you had not signed in, then the data is stored locally in browser.

The folder in your computer to look for is 

- Windows 7, 8.1, and 10: `C:\Users\username\AppData\Local\Google\Chrome\User Data\Default`
- Mac OS X El Capitan: `Users/username/Library/Application Support/Google/Chrome/Default`
- Linux: `/home/username/.config/google-chrome/default`

Similar folder path is for other browsers. Replace google chrome with the name of that browser.

But inside that folder, I don't know exactly where stack edit data is stored.

**Comment by aahnik** [comment]
hi @brucou  to prevent data loss and get fine control over your markdown files, sync your workspace with a GitHub repo.

You can create a GitHub repo for storing all your work. In the commit history, you can see all the times you made changes. 

With the power of git, you can do a lot of fine control, which is not possible if you use a google drive workspace.

In the Github repo, which you will use as a stack edit workspace, there will be a trash folder and lot of other binary files sometimes.

These large numbers of files can mess up. 

The only way to prevent them is that **perform deletions and renamings** of files and folders from your computer.
Clone the repo, make changes, and push it. Then refresh the stack edit page.

**Comment by brucou** [comment]
Thanks @aahnik I got the workspace back by copying the folder that you mention. I copied the entire folder so I did not have to ask myself where specifically stack edit data is stored. Thanks again for the help.
