### ISSUE TITLE
Find/Replace Function to Stackedit.io

### ISSUE THREAD

**Issue by EgorZay** [benweet/stackedit#1686]
Dear Sir,

Consider adding find/replace function on stackedit.io.

Thanks G.

**Comment by dayfuaim** [comment]
Is <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>F</kbd> (Linux, Windows) working for you? ;)

**Comment by EgorZay** [comment]
Yes, it does!

Thank you for this shortcut.
