### ISSUE TITLE
URGENT: SSL cert expired

### ISSUE THREAD

**Issue by episage** [benweet/stackedit#1710]
![image](https://user-images.githubusercontent.com/2196095/112721748-fe5c4380-8f05-11eb-8cf5-60a1ab4fff85.png)

![image](https://user-images.githubusercontent.com/2196095/112721757-07e5ab80-8f06-11eb-8685-b56c6ef6977a.png)

My wall clock time 14:09 27 Mar 2021

**Comment by slikts** [comment]
Embedded editing doesn't work, and I can't access my writings. Cool.

**Comment by dweathers** [comment]
Is this the reason nothing is rendering correctly in my book?

https://dweathers.github.io/174/book.html

**Comment by matiboux** [comment]
> Is this the reason nothing is rendering correctly in my book?
> 
> https://dweathers.github.io/174/book.html

@dweathers Yes, as the stylesheet used for exporting in StackEdit is hosted at `https://stackedit.io/style.css` and unavailable, just like the rest of the website.

**Comment by matiboux** [comment]
Also the website is impossible to access via HTTP (non-SSL) so it is quite bad, yeah.

**Comment by dweathers** [comment]
> > Is this the reason nothing is rendering correctly in my book?
> > https://dweathers.github.io/174/book.html
> 
> @dweathers Yes, as the stylesheet used for exporting in StackEdit is hosted at `https://stackedit.io/style.css` and unavailable, just like the rest of the website.

Thank you for the reply. I wasn't sure because I _can_ open the editor.

Do you think there is any chance this is fixed soon or do I find another way to publish my book?

**Comment by matiboux** [comment]
> > > Is this the reason nothing is rendering correctly in my book?
> > > https://dweathers.github.io/174/book.html
> > 
> > 
> > @dweathers Yes, as the stylesheet used for exporting in StackEdit is hosted at `https://stackedit.io/style.css` and unavailable, just like the rest of the website.
> 
> Thank you for the reply. I wasn't sure because I _can_ open the editor.
> 
> Do you think there is any chance this is fixed soon or do I find another way to publish my book?

I found out that I can access the website (both https://stackedit.io/ and https://stackedit.io/app) on a PC on which I have the webappplication installed. The displayed certificate is waaay outdated but because of the app it is somehow trusted anyway I guess.

I'm gonna try and install the app from the chrome web store and see what happens on another PC on which I cannot access the website and don't have the app.

**Comment by matiboux** [comment]
> I'm gonna try and install the app from the chrome web store and see what happens on another PC on which I cannot access the website and don't have the app.

Nope. This doesn't work. This may be related to when the application was installed.. Weird.

If anyone knows how to save and force a certificate as trusted, this could be a fix.. even though not ideal at all.

Another solution might be to self-host a copy of the projet. I might look into that.

**Comment by matiboux** [comment]
> Do you think there is any chance this is fixed soon or do I find another way to publish my book?

@dweathers As for your question, I have no idea!
The project seems dead so far as it hasn't been updated for two years and the developer is inactive on Twitter.

Also contributions on Github from @benweet sums to.. two. Not promising.

**Comment by dweathers** [comment]
Thank you for your help. In the meantime I will find somewhere else to put the book as the students have an exam this week.

**Comment by matiboux** [comment]
> Thank you for your help. In the meantime I will find somewhere else to put the book as the students have an exam this week.

@dweathers Good luck!

If you don't want to remake all your book I managed to reset the settings to the website, and access the website despite the expired certificate and i downloaded the `style.css` file!

(this was after trying to regenerate it from the source files in this repository but that wasn't successful because it isn't the same file at all...)

Anyway I'll upload to a website of mine so you can download and/or use it directly! (wait for the edit of this in, like, 2mins)

**Comment by matiboux** [comment]
@dweathers It is uploaded! Check out https://stackedit.mtbx.it/style.css

If you wanna use it on your website, just replace
```html
<link rel="stylesheet" href="https://stackedit.io/style.css" />
```
with
```html
<link rel="stylesheet" href="https://stackedit.mtbx.it/style.css" />
```

👌

**Comment by dweathers** [comment]
> @dweathers It is uploaded! Check out https://stackedit.mtbx.it/style.css

Thanks so much! The book now renders correctly. The math is rendering the same way it did on the SE app this morning, which is to say binomial coefficients look a little funny. I'm going to see why MathJaX and the style file are colliding with one another.

Thanks again for recovering that style file. I copied it and put it on my own server to prevent this issue in my future.

Have a great day!

**Comment by matiboux** [comment]
> The math is rendering the same way it did on the SE app this morning, which is to say binomial coefficients look a little funny. I'm going to see why MathJaX and the style file are colliding with one another.

@dweathers I forgot there was also fonts hosted on the stackedit website as well. That's what you're still missing. Here's the lists of font that should be included in the `style.css` file:

```
$ grep -Ro 'url(.[^)]*)' style.css
url(/static/fonts/KaTeX_AMS-Regular.e78e28b.woff2)
url(/static/fonts/KaTeX_AMS-Regular.7f06b4e.woff)
url(/static/fonts/KaTeX_AMS-Regular.aaf4eee.ttf)
url(/static/fonts/KaTeX_Caligraphic-Bold.4ec58be.woff2)
url(/static/fonts/KaTeX_Caligraphic-Bold.1e802ca.woff)
url(/static/fonts/KaTeX_Caligraphic-Bold.021dd4d.ttf)
url(/static/fonts/KaTeX_Caligraphic-Regular.7edb53b.woff2)
url(/static/fonts/KaTeX_Caligraphic-Regular.d3b46c3.woff)
url(/static/fonts/KaTeX_Caligraphic-Regular.d49f2d5.ttf)
url(/static/fonts/KaTeX_Fraktur-Bold.d5b59ec.woff2)
url(/static/fonts/KaTeX_Fraktur-Bold.c4c8cab.woff)
url(/static/fonts/KaTeX_Fraktur-Bold.a31e7cb.ttf)
url(/static/fonts/KaTeX_Fraktur-Regular.32a5339.woff2)
url(/static/fonts/KaTeX_Fraktur-Regular.b7d9c46.woff)
url(/static/fonts/KaTeX_Fraktur-Regular.a48dad4.ttf)
url(/static/fonts/KaTeX_Main-Bold.8e1e01c.woff2)
url(/static/fonts/KaTeX_Main-Bold.22086eb.woff)
url(/static/fonts/KaTeX_Main-Bold.9ceff51.ttf)
url(/static/fonts/KaTeX_Main-BoldItalic.284a17f.woff2)
url(/static/fonts/KaTeX_Main-BoldItalic.4c57dbc.woff)
url(/static/fonts/KaTeX_Main-BoldItalic.e8b44b9.ttf)
url(/static/fonts/KaTeX_Main-Italic.e533d5a.woff2)
url(/static/fonts/KaTeX_Main-Italic.99be0e1.woff)
url(/static/fonts/KaTeX_Main-Italic.29c8639.ttf)
url(/static/fonts/KaTeX_Main-Regular.5c734d7.woff2)
url(/static/fonts/KaTeX_Main-Regular.b741441.woff)
url(/static/fonts/KaTeX_Main-Regular.5c94aef.ttf)
url(/static/fonts/KaTeX_Math-BoldItalic.d747bd1.woff2)
url(/static/fonts/KaTeX_Math-BoldItalic.b13731e.woff)
url(/static/fonts/KaTeX_Math-BoldItalic.9a2834a.ttf)
url(/static/fonts/KaTeX_Math-Italic.4ad08b8.woff2)
url(/static/fonts/KaTeX_Math-Italic.f030390.woff)
url(/static/fonts/KaTeX_Math-Italic.291e76b.ttf)
url(/static/fonts/KaTeX_SansSerif-Bold.6e0830b.woff2)
url(/static/fonts/KaTeX_SansSerif-Bold.3fb4195.woff)
url(/static/fonts/KaTeX_SansSerif-Bold.7dc027c.ttf)
url(/static/fonts/KaTeX_SansSerif-Italic.fba01c9.woff2)
url(/static/fonts/KaTeX_SansSerif-Italic.727a9b0.woff)
url(/static/fonts/KaTeX_SansSerif-Italic.4059868.ttf)
url(/static/fonts/KaTeX_SansSerif-Regular.d929cd6.woff2)
url(/static/fonts/KaTeX_SansSerif-Regular.2555754.woff)
url(/static/fonts/KaTeX_SansSerif-Regular.5c58d16.ttf)
url(/static/fonts/KaTeX_Script-Regular.755e249.woff2)
url(/static/fonts/KaTeX_Script-Regular.d524c9a.woff)
url(/static/fonts/KaTeX_Script-Regular.d12ea9e.ttf)
url(/static/fonts/KaTeX_Size1-Regular.048c39c.woff2)
url(/static/fonts/KaTeX_Size1-Regular.08b5f00.woff)
url(/static/fonts/KaTeX_Size1-Regular.7342d45.ttf)
url(/static/fonts/KaTeX_Size2-Regular.81d6b8d.woff2)
url(/static/fonts/KaTeX_Size2-Regular.af24b0e.woff)
url(/static/fonts/KaTeX_Size2-Regular.eb130dc.ttf)
url(/static/fonts/KaTeX_Size3-Regular.b311ca0.woff2)
url(/static/fonts/KaTeX_Size3-Regular.0d89264.woff)
url(/static/fonts/KaTeX_Size3-Regular.7e02a40.ttf)
url(/static/fonts/KaTeX_Size4-Regular.6a3255d.woff2)
url(/static/fonts/KaTeX_Size4-Regular.68895bb.woff)
url(/static/fonts/KaTeX_Size4-Regular.ad76725.ttf)
url(/static/fonts/KaTeX_Typewriter-Regular.6cc31ea.woff2)
url(/static/fonts/KaTeX_Typewriter-Regular.3fe216d.woff)
url(/static/fonts/KaTeX_Typewriter-Regular.2570235.ttf)
url(/static/fonts/lato-normal.27bd77b.woff)
url(/static/fonts/lato-normal-italic.f28f2d6.woff)
url(/static/fonts/lato-black.f80bda6.woff)
url(/static/fonts/lato-black-italic.798eafd.woff)
url(/static/fonts/RobotoMono-Regular.0b6a547.woff)
url(/static/fonts/RobotoMono-Bold.819f3b2.woff)
url(#arrowhead)
url(#arrowhead)
url(#arrowhead)
url(#arrowhead)
```

Long story short, I downloaded everything and put them where I hosted my the file on my web server so that the link to the `style.css` file I gave works as expected.

And as for you to download, I've bundled all the fonts in a `.zip` file you can find attached to this comment!
You can find it here: [fonts.zip](https://github.com/benweet/stackedit/files/6217913/fonts.zip)

**Comment by NetzwergX** [comment]
If you are having a problem with Chrome letting you not view the site despite accepting the risk of the outdated certi, you can delete the HSTS settings for stackedit.io. This tutorial helps: https://www.thesslstore.com/blog/clear-hsts-settings-chrome-firefox/ That way, you can at least recover all docs in markdown format and everything else you still need.

**Comment by eakbas** [comment]
> @dweathers It is uploaded! Check out https://stackedit.mtbx.it/style.css
> 
> If you wanna use it on your website, just replace
> 
> ```
> <link rel="stylesheet" href="https://stackedit.io/style.css" />
> ```
> 
> with
> 
> ```
> <link rel="stylesheet" href="https://stackedit.mtbx.it/style.css" />
> ```

Thank you very much for the link! Can you please keep this for a while? We also have lecture notes that were using stackedit's style.css. We will be looking for alternatives.

**Comment by nathanganser** [comment]
Is this basically the end of StackEdit? Anyone willing to spin up a fork?

**Comment by benweet** [comment]
Sorry guys for the inconvenience, it was due to an outdated version of cert-manager.

**Comment by eakbas** [comment]
The same problem happened again! When I try to access https://stackedit.io/style.css, I get NET::ERR_CERT_DATE_INVALID.
