### ISSUE TITLE
Multiple views of documents (read-only)

### ISSUE THREAD

**Issue by leidegre** [benweet/stackedit#174]
Currently, I cannot modify multiple documents at the same time (multiple tabs not allowed). That's alright by me but I'd really like to be able to view multiple documents while I edit another document.

Right now I export the documents I wish to use as reference but it would be really sweet if there was a way for me to view/browse any number of documents (in separate view/read-only tabs) while I'm composing a new document.

**Comment by benweet** [comment]
The v5 now supports multi-tabs.
