### ISSUE TITLE
GitHub authorization has changed

### ISSUE THREAD

**Issue by lorenx** [benweet/stackedit#1755]
Hello,
I don't know if you are aware but GitHub has changed its authentication method, on May 5, 2021: see [here](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/) and [here](https://docs.github.com/en/rest/guides/basics-of-authentication#accepting-user-authorization).

In fact, as I try to add my Github repo, StackEdit receives this error:

```
{
    "status": 400,
    "body": {
        "message": "Must specify access token via Authorization header. https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param",
        "documentation_url": "https://docs.github.com/v3/#oauth2-token-sent-in-a-header"
    }
}
```

Anyway...
GitLab integration [is not working](https://github.com/benweet/stackedit/issues/1629), GitHub is not working either now.
What should we do?

I hope in a quick fix, thank you very much.

**Comment by lorenx** [comment]
I guess it's the same as #1724.
But it doesn't seem fixed...

**Comment by unovil** [comment]
> ```
> {
>     "status": 400,
>     "body": {
>         "message": "Must specify access token via Authorization header. https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param",
>         "documentation_url": "https://docs.github.com/v3/#oauth2-token-sent-in-a-header"
>     }
> }
> ```
> 
> Anyway...
> GitLab integration [is not working](https://github.com/benweet/stackedit/issues/1629), GitHub is not working either now.
> What should we do?

Same problem here, I granted access to Github so I could sign in from StackEdit and it worked fine, but when I try to add a workspace from Github I get an "HTTP Error 400" sign and this:
![image](https://user-images.githubusercontent.com/70586029/129340862-73fcbd07-8c79-405c-946f-d69b0654731b.png)

**Comment by lorenx** [comment]
Yeah, that's the exact error I get too.
It should be simple to change how the token is sent, if only some dev would reply us... @benweet

**Comment by leils** [comment]
Getting the same exact error, bumping.

**Comment by mogoe1** [comment]
For the time being, I developed a workaround. I know there already is #1724  that fixes the issue, but I wanted to keep using [StackEdit](stackedit.io) whilst the request is not yet merged.

Once you are on the screen asking you to  "Grant access to your private repositories," open the developer console and paste the following lines.

```js
window.XMLHttpRequest =  class MyXMLHttpRequest extends window.XMLHttpRequest {
  open(...args){
    if(args[1].startsWith("https://api.github.com/user?access_token=")){
      // apply fix as described by github
      // https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/#changes-to-make
  
      const segments = args[1].split("?");
      args[1] = segments[0]; // remove query params from url
      const token = segments[1].split("=")[1]; // save the token
      
      const ret = super.open(...args);
      
      this.setRequestHeader("Authorization", `token ${token}`); // set required header
      
      return ret;
    }
    else {
      super.open(...args);
    }
  }
}
```

This overrides `window.XMLHttpRequest`, which [StackEdit](stackedit.io) uses to send API-Requests to GitHub, and modifies requests to `https://api.github.com/user`. Specifically, it moves the token from query to header.

Once the repository is connected, you can remove the overridden `XMLHttpRequest` by reloading the page.

**Comment by jacobhq** [comment]
Thank you @mogoe1!

**Comment by steffiland** [comment]
Thank you! Ran into this problem this morning...

**Comment by albydeca** [comment]
@benweet Can confirm issue still persists as of today

**Comment by tyoc213** [comment]
```
{
  "message": "Must specify access token via Authorization header. https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param",
  "documentation_url": "https://docs.github.com/v3/#oauth2-token-sent-in-a-header"
}
```

Yeah, just right now

**Comment by yenow** [comment]
@mogoe1 thank you!!!

**Comment by baomastr** [comment]
big up @mogoe1

**Comment by swoogles** [comment]
Heads up to other recently-frustrated StackEdit users-
From all appearances, the project maintainer is gone. He has had 0 Github activity since March of last year: https://github.com/benweet
I've tried searching for any news items about him, checking for career changes/death announcements/ etc, but without success.
With 8+ months of silence from the solo maintainer, I recommend people start finding/creating alternatives. I know I would be very happy to support someone forking this and taking it into the future :)

**Comment by steffiland** [comment]
also had the impression of the project being unmaintained now...  meanwhile I switched to Obsidian, which i really love.... Migration is quite easy.

**Comment by Squiddim** [comment]
This is still an ongoing issue.
Any news on this being added upstream

> For the time being, I developed a workaround. I know there already is #1724 that fixes the issue, but I wanted to keep using [StackEdit](stackedit.io) whilst the request is not yet merged.
> 
> Once you are on the screen asking you to "Grant access to your private repositories," open the developer console and paste the following lines.
> 
> ```js
> window.XMLHttpRequest =  class MyXMLHttpRequest extends window.XMLHttpRequest {
>   open(...args){
>     if(args[1].startsWith("https://api.github.com/user?access_token=")) {
>       // apply fix as described by github
>       // https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/#changes-to-make
>   
>       const segments = args[1].split("?");
>       args[1] = segments[0]; // remove query params from url
>       const token = segments[1].split("=")[1]; // save the token
>       
>       const ret = super.open(...args);
>       
>       this.setRequestHeader("Authorization", `token ${token}`); // set required header
>       
>       return ret;
>     }
>     else {
>       return super.open(...args);
>     }
>   }
> }
> ```
> 
> This overrides `window.XMLHttpRequest`, which [StackEdit](stackedit.io) uses to send API-Requests to GitHub, and modifies requests to `https://api.github.com/user`. Specifically, it moves the token from query to header.
> 
> Once the repository is connected, you can remove the overridden `XMLHttpRequest` by reloading the page.

**Comment by Lovegiver** [comment]
Thanx a lot. I'm admirative for persons like you who understand something about front end and security ^^

**Comment by snowsum** [comment]
> For the time being, I developed a workaround. I know there already is #1724 that fixes the issue, but I wanted to keep using [StackEdit](stackedit.io) whilst the request is not yet merged.
> 
> Once you are on the screen asking you to "Grant access to your private repositories," open the developer console and paste the following lines.
> 
> ```js
> window.XMLHttpRequest =  class MyXMLHttpRequest extends window.XMLHttpRequest {
>   open(...args){
>     if(args[1].startsWith("https://api.github.com/user?access_token=")) {
>       // apply fix as described by github
>       // https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/#changes-to-make
>   
>       const segments = args[1].split("?");
>       args[1] = segments[0]; // remove query params from url
>       const token = segments[1].split("=")[1]; // save the token
>       
>       const ret = super.open(...args);
>       
>       this.setRequestHeader("Authorization", `token ${token}`); // set required header
>       
>       return ret;
>     }
>     else {
>       return super.open(...args);
>     }
>   }
> }
> ```
> 
> This overrides `window.XMLHttpRequest`, which [StackEdit](stackedit.io) uses to send API-Requests to GitHub, and modifies requests to `https://api.github.com/user`. Specifically, it moves the token from query to header.
> 
> Once the repository is connected, you can remove the overridden `XMLHttpRequest` by reloading the page.

**Comment by ocundale** [comment]
> also had the impression of the project being unmaintained now... meanwhile I switched to Obsidian, which i really love.... Migration is quite easy.

Thank you - great recommendation! :)

**Comment by omerfsen** [comment]
Same here ... Above code snippet worked for me (16.02.2023). I do afraid something happened to this developer. Hope he is alive.

**Comment by houserockr** [comment]
Same here, JS snippet worked for me (16.03.2023)
Also, the fact that I even have to do this is fvking annoying.

**Comment by pamoroso** [comment]
I still get the error despite the [workaround](https://github.com/benweet/stackedit/issues/1755#issuecomment-918949789). Any chances of fixing the issue for good by merging #1724?

**Comment by rx-ted** [comment]
Thank you @mogoe1!

**Comment by R-Rudolf** [comment]
It is clear that it won't be fixed, the maintainer basically left this project.

I switched to using Github itself for note taking, it has great editor features, even on mobile.
But to create new file on mobile, I use this app:
[GitJournal](https://play.google.com/store/apps/details?id=io.gitjournal.gitjournal). The version controll sounds like a nice feature in this flow :)

I tried some free tier of paid software as Obsidian/Notion, but for me is did not fit. In PM I am open for similar free software recommendations.

**Comment by benweet** [comment]
Should be fixed with v5.15.0.

**Comment by ghost** [comment]
> Heads up to other recently-frustrated StackEdit users- From all appearances, the project maintainer is gone. He has had 0 Github activity since March of last year: https://github.com/benweet I've tried searching for any news items about him, checking for career changes/death announcements/ etc, but without success. With 8+ months of silence from the solo maintainer, I recommend people start finding/creating alternatives. I know I would be very happy to support someone forking this and taking it into the future :)

did you end up forking it.?
let me know I can contribute, I love this project.

**Comment by luisacelino** [comment]
> For the time being, I developed a workaround. I know there already is [#1724](https://github.com/benweet/stackedit/pull/1724) that fixes the issue, but I wanted to keep using [StackEdit](stackedit.io) whilst the request is not yet merged.
> 
> Once you are on the screen asking you to "Grant access to your private repositories," open the developer console and paste the following lines.
> 
> window.XMLHttpRequest =  class MyXMLHttpRequest extends window.XMLHttpRequest {
>   open(...args){
>     if(args[1].startsWith("https://api.github.com/user?access_token=")) {
>       // apply fix as described by github
>       // https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/#changes-to-make
>   
>       const segments = args[1].split("?");
>       args[1] = segments[0]; // remove query params from url
>       const token = segments[1].split("=")[1]; // save the token
>       
>       const ret = super.open(...args);
>       
>       this.setRequestHeader("Authorization", `token ${token}`); // set required header
>       
>       return ret;
>     }
>     else {
>       return super.open(...args);
>     }
>   }
> }
> This overrides `window.XMLHttpRequest`, which [StackEdit](stackedit.io) uses to send API-Requests to GitHub, and modifies requests to `https://api.github.com/user`. Specifically, it moves the token from query to header.
> 
> Once the repository is connected, you can remove the overridden `XMLHttpRequest` by reloading the page.

This workaround is not working anymore (2025)
Thanks for your support <3
