### ISSUE TITLE
Your SSL Certificate Might have expired

### ISSUE THREAD

**Issue by tcampbPPU** [benweet/stackedit#1775]
Cannot access `https://stackedit.io/` without insecure connection warning
![image](https://user-images.githubusercontent.com/25044744/151647426-3b3ca37c-0ac2-441c-b0a8-4e8094c83db9.png)

**Comment by IAmAnubhavSaini** [comment]
Came here to create the same issue.

![Screenshot from 2022-01-29 10-53-04](https://user-images.githubusercontent.com/1573771/151648817-bb6a5145-4fd8-498f-9542-09486a26916d.png)

**Comment by Mindstormer-0** [comment]
Indeed, same issue.
![image](https://user-images.githubusercontent.com/49846301/151681491-144dd8a6-79dc-4c68-8bd2-cb470dbfabda.png)

**Comment by tcampbPPU** [comment]
Looks like been resolved
