### ISSUE TITLE
Color theme is not changed in generated HTML file

### ISSUE THREAD

**Issue by yvanblanchard** [benweet/stackedit#1815]
Hello,

I changed the color theme in the settings (dark mode) and it works fine in the online editor (markdown).
But when I export the HTML file (with default styled HTML), the theme is light instead of dark.

Coudl you pleae help ?
thank you.

**Comment by mafgwo** [comment]
![image](https://user-images.githubusercontent.com/46500241/230310312-ac6ba500-3722-404d-8692-cb6db03d9cf7.png)

**Comment by yvanblanchard** [comment]
Wonderful ! thank you, it works fine from
https://stackedit.net/app#
