### ISSUE TITLE
 `HTTP error 400.` error when trying to export pdf.   

### ISSUE THREAD

**Issue by theoryshaw** [benweet/stackedit#1822]
get the following error when trying to export pdf. 

Currently a sponsor. 

`HTTP error 400.`

**Comment by benweet** [comment]
I can reproduce that with documents containing horizontal rules :

```
---
```

The problem is described here : https://github.com/jgm/pandoc/issues/5801
Not sure how to fix it yet but it should work if you remove the horizontal rules from your document.

**Comment by benweet** [comment]
Should be fixed with v5.15.2.
