### ISSUE TITLE
Math button shortcuts for people who don't know TeX

### ISSUE THREAD

**Issue by juzerali** [benweet/stackedit#185]
I was thinking how convenient would it be for people who don't know TeX (yet) to have visual buttons to input mathematical notations and equations. There is a trade off between minimalism and features, I know. But a full GUI based Math editor is required for a full featured text editor.

@benweet Would you like to add that feature, or else, will you accept pull requests that implements these features?

**Comment by victorel-petrovich** [comment]
@akerbos , @benweet , @juzerali 

How about an extension that provides a list of matchig of latex commands, when when user starts typing  a particular latex command. Ex: `$\left...$` (then a popup appears and suggests \leftarror, \leftbracket etc). Then user can navigate with arrow down and select by enter or space.   
I think this could not only help beginners, but speed the work of advanced users too.

**Comment by juzerali** [comment]
My idea for opening this ticket was to assist users who have absolutely no
experience with latex. What you are suggesting is helpful to experienced
users.

**Comment by akerbos** [comment]
@victorel-petrovich That's a non-trivial task in itself. The list of available commands depends on which packages are loaded, what you have defined above, conflict resolution, and so on.

**Comment by victorel-petrovich** [comment]
Yeah, I agree, it's advanced feature. I saw it in [LYX](http://www.lyx.org/).

**Comment by benweet** [comment]
Closing as too old.
