### ISSUE TITLE
Google+ Image importer improvements suggest

### ISSUE THREAD

**Issue by ghost** [benweet/stackedit#189]
**Improvements Suggest**
1. Multi Selection Function.
2. Revert Image Sort Order - Newer First.

**Expected Effects**
1. Reduce click for import many google+ picture import.
2. Reduce Scroll for select latest uploaded picture.
- Reduce click.
  I usually do 4~10 picture per article for people easy accepting. markdown make me happy and 20~50 click makes me unhappy. (5 click for 1 photo - in) 
- Reduce scroll.
  new Stackwrite article with new uploaded photo. it make sense. every time i scroll down per photo. It makes me ... machine.

It will Stackwrite more comfortable. :+1: 

+Plus API

I'm not a programmer but know there's picasa API for [requesting latest photo](https://developers.google.com/picasa-web/docs/2.0/developers_guide_protocol).

```
Listing photos recently uploaded

It is also possible to retrieve the photos associated with a user, but without specifying any particular album. The following request retrieves the last 10 photos uploaded by userID:

GET https://picasaweb.google.com/data/feed/api/user/userID?kind=photo&max-results=10
For more information about the query parameters that can be used with the API, consult the query parameters section of the Reference Guide.
```

**Comment by benweet** [comment]
Closing as too old.
