### ISSUE TITLE
open another document by clicking on link rather than "select document"

### ISSUE THREAD

**Issue by colcord** [benweet/stackedit#195]
I like the current ability to navigate within a document by clicking on links to other headers within a document. 

I suggest the ability to navigate to other documents within the stackedit cache by clicking on the link in the web preview.

For example, I have two files in my stackedit cache: colophon.txt and pandoc.txt. 
I am editing a file colophon.txt which contains the text 

[pandoc](/pandoc/) 

clicking on that link saves the current state of colophon.txt and opens pandoc.txt.

as in quote:

If you’re referring to a local resource on the same server, you can use relative paths:

See my [About](/about/) page for details.   

end quote from http://daringfireball.net/projects/markdown/syntax#link

would it be possible to combine filenames and headers, so, for example to have

[pandoc](/pandoc#links) 

open the document pandoc.txt at the location of the header "links"

I'm not sure if that would need to be:

[pandoc](/pandoc/#links) 

(with a second forward slash)

Another question is whether there could be directory structures, so you could have:

[pandoc](/processing/pandoc#links)

**Comment by breschke** [comment]
The jump to anchor does not work. I have tried to use the original script from @benweet as well as the various modifications suggested in this issue. None of various scripts support anchors. In viewer, the document opens to the document specified, and the anchor appears in the address bar of the browser, but the document opens at the top of the document only.

**Comment by borisbys** [comment]
anyone have any suggestion on how to anchors to work? I can insert the link but it doesnt seem to scroll down to the anchor.
