### ISSUE TITLE
Allow for outliner (toc) to be visible independently of preview visibility

### ISSUE THREAD

**Issue by memeplex** [benweet/stackedit#199]
I tend to work with a maximized editor (the point of markdown is that you don't badly need a preview, although it's great to have one). And I find the outlining facility provided by the toc very convenient while I'm editing. But I'm forced to open the preview each time in order to get advantage of the outline. Would it be possible to move the outline to the toolbar so that it's available both at the editor and at the preview no matter whether this last one is hidden or not.

Related to the above --although I don't care about this at all-- the markdown help window would be more consistently located inside the editor than inside the preview. 

Both concerns are related to my maximized editor use history. Maybe it's just a marginal practice that doesn't deserve to be generally supported at all.

**Comment by victorel-petrovich** [comment]
I also spend most time with the editor side only, and I use the TOC button ALOT to navigate back and forth in my docs. While I am happy with how TOC works/displays, I just wish I could:
*  Access it faster (via keyboard shorcut? or maybe setting the TOC button in the top navigation bar, i.e near `B`, `I` etc)  

and/or:  
* Make it possible for the TOC to stay dispayed after openning it once.

Are these possible?

**Comment by benweet** [comment]
Closing this as v5 got a brand new layout!
