### ISSUE TITLE
How to write reference & citation?

### ISSUE THREAD

**Issue by vanabel** [benweet/stackedit#20]
I try to write some reference as following:
 From `[bao2004zermelo][1]`, we konw that...

The problem is that this can't work when there has some `white space` in the **reference**, then how to solve this problem? 

Maybe integrate [**bibtex-markdown**](https://github.com/kyledewey/bibtex-markdown) into stackedit will be a perfect solution?

`[1]: Bao, David, Colleen Robles, and Zhongmin Shen. "Zermelo navigation on Riemannian manifolds." *Journal of Differential Geometry* 66.3 (2004): 377-435.`

**Comment by retorquere** [comment]
https://github.com/fiduswriter/biblatex-csl-converter/ is actively maintained.
