### ISSUE TITLE
tumblr publishing problem when code includes "~" sign

### ISSUE THREAD

**Issue by IsmailMarmoush** [benweet/stackedit#201]
I tracked this issue for around an hour I had a document that wasn't publishing to tumblr markdown so I kept cutting and trimming until I found that the "~" sign at the end of the following shell code was the cause:

``` shell
sudo rpm -ivh nautilus-dropbox~
```

I guess something goes inside where the character isn't escaped and tumblr has an error which causes "Access to tumblr account is not authorized"

**Comment by benweet** [comment]
Closing as too old.
