### ISSUE TITLE
Collaborative Editing.

### ISSUE THREAD

**Issue by c19** [benweet/stackedit#224]
Will stackedit support Collaborative Editing?
Google Drive support Collaborative Editing, and maybe we can support it via google drive?

**Comment by hadyrashwan** [comment]
# Issue discussion

#### Interface 

    export  interface  InviteOrgUserRequest{
    email:string
    uid:string
    id:string
    orgId:string
    code:string
    claimId:string
    type:'inviteOrgUser'
    permissions?:string
    }

#### Queries 

     await firestoreRef.collection('users').
     where('domain','==',item).get()

### Tasks
 - [ ] part one 
 - [ ] part two
 - [ ] part three
