### ISSUE TITLE
Popup for rename document function

### ISSUE THREAD

**Issue by orschiro** [benweet/stackedit#235]
Hi,

Particularly for long titles the current way of renaming is a bit inconvenient.  It does not show the entire title and requires you to move the cursor to the left and right to see the complete title.

As a suggestion I think it would be nice to have the renaming title function to be displayed in a wider popup dialog that shows the entire title.

What do you think?

**Comment by benweet** [comment]
Hi @orschiro 
Should be fixed in v5.
