### ISSUE TITLE
Dropbox API user limit reached

### ISSUE THREAD

**Issue by magikid** [benweet/stackedit#250]
Tried to link my Dropbox account and reached this error saying that StackEdit has reached its user limit for the Dropbox API.

![image](https://f.cloud.github.com/assets/115515/1818492/160a4510-7008-11e3-9ed3-277d8c9c33af.png)

**Comment by anjigithub** [comment]
Tried to link my Dropbox account and reached this error saying that StackEdit has reached its user limit for the Dropbox API.

**Comment by anjigithub** [comment]
Tried to link my Dropbox account and reached this error saying that StackEdit has reached its user limit for the Dropbox API.
![error](https://cloud.githubusercontent.com/assets/11735906/6917562/5729a5d0-d7c3-11e4-9622-e017319fd67b.jpg)

**Comment by benweet** [comment]
@anjigithub do you still have this error? Are you using stackedit.io or a custom instance?
