### ISSUE TITLE
Display full file path in file selector view

### ISSUE THREAD

**Issue by gtzilla** [benweet/stackedit#255]
Please display entire file path. When opening multiple files of the same name into stackedit, unable to differentiate files with the same name in file selector view.

As you can see in attached screenshot, editing something common, like README.md, becomes confusing when working with multiple projects.

![screen shot 2014-01-05 at 11 48 45 pm](https://f.cloud.github.com/assets/185538/1848515/e9260ae8-768d-11e3-99b2-5cbe83a7ca59.png)

**Comment by benweet** [comment]
Closing as too old.
