### ISSUE TITLE
Support for exporting through pandoc to its various supported formats would be great to have 

### ISSUE THREAD

**Issue by mohanraj-r** [benweet/stackedit#262]
During the course of the day I have to create/edit documents in various formats - including wiki markup. It is a hassle to learn and remember all the markups. What I tend to do is write in Markdown and use Pandoc to convert it to the desired format. 

Stackedit.io is quickly becoming my default editor for markdown. It will be great if there was an export or save option that exported the markdown using pandoc to pandoc's supported export formats. This would save me the trouble of downloading the document in markdown, running pandoc on the command line with the right options and uploading / copying the content.

Thanks for this project btw. Love the work.

**Comment by japhir** [comment]
I would also very much like the pandoc support for superscript (10^3^) and subscript (CO~2~), YAML-headers and possibly citations using bibtex. If StackEdit were then able to export to pdf my mind would be blown: I could work entirely online without needing to download anything to my University working computer ;).

**Comment by the-solipsist** [comment]
+1. Support for pandoc and pandoc-citeproc would greatly extend the usability of StackEdit by the academic community.

**Comment by jflournoy** [comment]
There is a huge opportunity for integrating simple text markdown editors like slackedit and reference management tools like zotero for an academic community that is becoming more enamored of open, collaborative tools (but that doesn't want to learn LaTeX). +1

**Comment by orschiro** [comment]
I agree with @jflournoy. To date, there is no comprehensive cross-platform editor for academic writing in Markdown. 

That would be a huge advancement!

~ Robert

**Comment by benweet** [comment]
Pandoc export has just been added to [Classeur](https://github.com/classeur/classeur).

**Comment by orschiro** [comment]
@benweet 

Thanks for sharing Classeur! I find it very interesting but cannot find much information about the core idea behind Classeur. For example, what makes it different from StackEdit?

**Comment by benweet** [comment]
Fixed in v5.

**Comment by frastlin** [comment]
If we have pandoc support now, why not add the ability to switch from a markdown specific editor to a LaTeX editor? Some of my collaborators like LaTeX, they have not yet seen the amazingness of markdown.
Also, is there documentation for using citeproc, or was just export to all the pandoc document formats added?
I would love if there was a way to upload or link a file of my bibtex citations to my file.
