### ISSUE TITLE
Persistent Word Counter

### ISSUE THREAD

**Issue by Swader** [benweet/stackedit#266]
Suggest implementing persistent word counter. Suggest using same style as implemented by Dillinger.io - that was my PR there - show words all the time, and when you only select some, show "X of Y".

Suggested layout change to accommodate: to the left of the document name, or implement a new "status bar" at the bottom with persistent full stats, that can be turned on and off in settings.

**Comment by dnstanciu** [comment]
I see there is a word count now for partial selections too. This should be closed, right? @benweet

**Comment by benweet** [comment]
Yes, right.
