### ISSUE TITLE
Using it with Chrome in iPad

### ISSUE THREAD

**Issue by frafor** [benweet/stackedit#269]
You might not believe me, but it did work! Just great. But my happiness greatly diminished when I noticed that it was failing.

1) I wrote a document
2) I decided to store it my Google Drive
3) I was successful. The document is now in my Google Drive.

However, a few minutes later, I started another document. That's when things stopped working (I mean, only for the Google Drive part). I was never able to store the second document in my Google Drive.

What kept happening was that the program kept asking me to accept to proceed to pass on to the Google Authorization page. Which it did, but then NOTHING would happen. Nothing. It would stay there waiting for me to tap on the google account under whose drive I would be storing the document. But nothing else ever happened.

I did have my Gmail opened in one of the Chrome opened pages, I knew I was already logged into the Gmail/ Google Drive system.

Remember: I had already successfully stored 1 document (the first one). Hopefully you will be able to fix this. Good piece of work, _StackEdit_. Try to make it work properly under the Google Drive. It's pure HTML5 code. I know it can be done; I've advanced my application and so far it works just fine under all browsers and all environments.

**Comment by benweet** [comment]
Closing as too old.
