### ISSUE TITLE
How to publish markdown to GitHub

### ISSUE THREAD

**Issue by vanabel** [benweet/stackedit#27]
Suppose that I have a user page `vanabel.github.io`, did there any tutor to publish the `markdown` or `html` to the page? I mean to make it looks like a blog? 

The first problem need to solve is that how to publish a markdown or html to GitHub, since I never try succeed.

**Comment by hufflepuffbr** [comment]
How could I change the commit text when I publish via stackedit?

**Comment by joewahler** [comment]
Would like the ability to edit the publish comment message before publishing.

**Comment by kgashok** [comment]
This is sort of related. In the "Advanced" setting there is a "GitHub commit message" dialog. How can I include the actual filename as part of the commit message, so that I can set something like "Updated XXX.md"?
