### ISSUE TITLE
The editor is being slow lately

### ISSUE THREAD

**Issue by bbhenry** [benweet/stackedit#289]
Starting a few days ago, the editor has been slow and not responsive to what I am typing. It would sometimes take a few seconds before it catches up, and the screen would pause for a short second or two before you can type or move the cursor around again.

**Comment by plumSemPy** [comment]
Hey guys, I am experiencing the slowdown again.

**Comment by XericZephyr** [comment]
Slow for me when directly using it with Google Drive files.

Chrome  57.0.2987.98 (64-bit).
