### ISSUE TITLE
Synchronization with Gist

### ISSUE THREAD

**Issue by JosefJezek** [benweet/stackedit#30]
Please add Synchronization with Gist, see this cool project http://www.gistboxapp.com

Could you add Color-Coded Labels?
http://blog.gistboxapp.com/post/47278471382/gists-are-bookmarks-with-context

**Comment by sargeant45** [comment]
I might take a jab at this. I'll probably make a library to sync with Gist, or maybe submit a PR.

**Comment by benweet** [comment]
Fixed in v5.
