### ISSUE TITLE
remoteStorage provider

### ISSUE THREAD

**Issue by almereyda** [benweet/stackedit#321]
I'd like to see a https://github.com/remotestorage/remotestorage.js/ provider for StackEdit

---

The repository mentions Providers:
- https://github.com/benweet/stackedit/blob/master/doc/developer-guide.md#developer-guide
- https://github.com/benweet/stackedit/tree/master/public/res/providers

and Helpers
- https://github.com/benweet/stackedit/tree/master/public/res/helpers

---

Would this be appropriate places to dive in to provide a Connector?
If you want, learn more about it on the [remoteStorage webpage](http://remotestorage.io/).

**Comment by benweet** [comment]
Closing this as too old.
