### ISSUE TITLE
multi-line paragraphs

### ISSUE THREAD

**Issue by wilx** [benweet/stackedit#355]
Please add support to multi-line paragraphs so that the following is considered to be a single paragraph:

```
This is
a paragraph
of multiple lines.
```

This is what [Pandoc](https://github.com/jgm/pandoc) supports.

It would be a convenience (and compatibility) feature. I would not have to go through pasted text to remove line breaks.

**Comment by mogsdad** [comment]
The 2014 response is no longer accurate.

A simple way to get the requested behavior is to change the document's markdown presets. *File Properties > Simple Properties > Extensions*. Change the Preset from `default` to `commonmark`, for example. 

![image](https://user-images.githubusercontent.com/1707731/97714590-ba206080-1a97-11eb-8bb1-6ca37c180237.png)

![image](https://user-images.githubusercontent.com/1707731/97715163-711cdc00-1a98-11eb-9817-566f86aac69c.png)
