### ISSUE TITLE
Double quotes bug in save as html

### ISSUE THREAD

**Issue by j0hnsmith** [benweet/stackedit#357]
Double quotes get converted to angled double quotes so when you save as html the opening one comes out as `â€œ` and the closing `â€`.

**Comment by bane73** [comment]
This is good to know, was driving me crazy.  Seems like disabled should be the default for this feature.

**Comment by TomAuger** [comment]
Save as Template solved the HTML export issue and allowed smart quotes to be rendered correctly. I'll have to check the docs to see where that template is defined and what options we have for configuring it.
