### ISSUE TITLE
Problems with pdf. 

### ISSUE THREAD

**Issue by Artusartos** [benweet/stackedit#377]
I was using stackedit.io to write up a paper, but I'm having problems converting it to a pdf document. I have used this website before and it worked fine, but it's not working anymore for some reason. I tried using different browsers and it's still not working. Whenever I click "open in viewer" and then "save as PDF", a message appears in adobe reader "There was an error opening this document. The file is damaged and could not be repaired." So I was wondering how I could fix this.

**Comment by fopitz** [comment]
Same problem. Too bad. I paid for that feature and then it is not working.
