### ISSUE TITLE
StackEdit 4 beta preview

### ISSUE THREAD

**Issue by benweet** [benweet/stackedit#385]
This is a dedicated ticket for any feedback on StackEdit 4 beta preview (https://stackedit-beta.herokuapp.com/).

Your feedback is much appreciated!

If you like it, say it.
If you don't, or you haven't noticed any difference, say it.
If you have any suggestion, I'm happy to hear it.
If you just found a bug, declare a new issue.

If you like StackEdit, please give it 5 stars on the [Chrome Web Store](https://chrome.google.com/webstore/detail/stackedit/iiooodelglhkcpgbajoejffhijaclcdg)...

Cheers!

**Comment by vennetong** [comment]
Not sure if it is an issue of StackEdit, but if I installed Grammarly extension for grammar and spelling checking, the performance becomes worse. Once I uninstall grammarly, the weird thing is more than thousands empty lines being added.
