### ISSUE TITLE
Time delay for markdown engine

### ISSUE THREAD

**Issue by vanabel** [benweet/stackedit#42]
Can we set the time delay for rendering, naturally, the engine will render all the content again after any single change take place, I am wondering if we  can set some time delay, such that it will rendering not immediately, but at the given period, such as after 30 sec?

Even more, I think if we can do the "local render" then the user experience will improve a lot, only the changed  sentence or paragraph will be rendered, the other stay the same? Could this be possible? What's the main technical difficulties?

**Comment by benweet** [comment]
Closing as too old.
