### ISSUE TITLE
XMLRPC made publish to self-hosted WP possible?

### ISSUE THREAD

**Issue by vanabel** [benweet/stackedit#46]
I still publish the post edited by stackedit through copy and paste. 

I don't know if the xmlrpc will make it possible to public the post with one click, It seems to me that it shall work, the reasons are the following:
1. [WP XML-RPC Web-Client](https://codex.wordpress.org/Weblog_Client) say that: "You can always develop your own. Many scripts in Perl, Python, PHP, Applescript and Java have already been written and are ripe for the picking (and tweaking). "
2. I have tried the [shareaholic](http://www.shareaholic.com/), an [chrome extension](https://chrome.google.com/webstore/detail/shareaholic-for-google-ch/kbmipnjdeifmobkhgogdnomkihhgojep), and it works for my self-hosted WP.

Since your solution Jetpack is of some heavy plugin, I hope this will helpful to improve the publish to WP function.

**Comment by benweet** [comment]
Closing as too old.
