### ISSUE TITLE
YAML Frontmatter is included in published post

### ISSUE THREAD

**Issue by rberteig** [benweet/stackedit#489]
I wrote a short test post with a YAML block at the front, that included both supported and unsupported variables. I posted it to my blog at WordPress with publish: false set so it would be a Draft, and published it as Markdown since my blog is set to use Markdown.

It did publish as a Draft. (I've since changed [that to Published](http://curiouser.cheshireeng.com/2014/08/25/another-stackedit-test-with-yaml/) so it can be linked here.)

But it also included the entire YAML block in the post and WordPress is rendering it.

I suppose that I should stop fighting WordPress about Markdown and have StackEdit render it to HTML when publishing, but I'm stubborn. They claim to support it, but just lack a post editor that actually works. StackEdit works really nicely overall.

**Comment by thomaslevesque** [comment]
@benweet thanks for the template tip! But shouldn't it be the default behavior? I mean, why would one want to publish the YAML Front Matter as part of the article?

**Comment by thomaslevesque** [comment]
Oh, and a stupid question: where do I set the template for publishing to Wordpress?
