### ISSUE TITLE
export to blogger loses icons

### ISSUE THREAD

**Issue by tyrcho** [benweet/stackedit#498]
When I export to a blogger post, the icons are not displayed anymore in the post.

Sample file I used for my test :  https://stackedit.io/viewer#!provider=gist&gistId=52155de3575795ebb3ef&filename=StackEditIcons

**Comment by holroy** [comment]
How can you include the fontello icons in the blog template?!

**Comment by pulkitsinghal** [comment]
Given that this is a predictable issue that everyone publishing to blogger/blogspot will run into, is their merit in making it part of the publish process? Manual steps after a one-click solution are a tad unattractive.

Does this mean I'm volunteering to submit a PR? Aha ... haha ... NO. Just giving my *entitiled* 2 cts.
