### ISSUE TITLE
PDF footer page count ... broken, or undocumented?

### ISSUE THREAD

**Issue by mmatti** [benweet/stackedit#501]
Happily paid for PDF export, but haven't been able to get page counts in a footer. The help link to wkhtmltopdf doesn't show what's needed; it refers to a [sitepage] argument that doesn't work when passed to the PDF options JSON object.

footerCenter will only render a static string value, and footerFontSize doesn't seem to do anything at all.

So, is there a way to get page numbers to appear?

**Comment by theoryshaw** [comment]
Also experiencing the same error...
```
Error when trying to generate PDF: Bad Request
```
Also a sponsor. thanks.

**Comment by benweet** [comment]
@theoryshaw I think it's another problem. Can you open a new ticket?
Thx.
