### ISSUE TITLE
How about add the emoji support ?

### ISSUE THREAD

**Issue by wenerme** [benweet/stackedit#509]
Emoji like this http://www.emoji-cheat-sheet.com/.

Also list all internal support icons ?

When export, also export support icons ?

I think this will make text more colorful.

**Comment by InDieTasten** [comment]
I am also missing them. Count it as vote up :+1: on this enhancement/feature

**Comment by almereyda** [comment]
I would second this request.

**Comment by borekb** [comment]
Aren't GitHub emoji on some CDN already? Would be nice to have them rendered in StackEdit.

**Comment by amitguptagwl** [comment]
Any update?

**Comment by benweet** [comment]
Support for `:+1:` and others has been added in v5. To support shortcuts like `:-)` you have to add this to your files properties:

```
extensions:
  emoji:
    shortcuts: true
```

**Comment by amitguptagwl** [comment]
I've added it in Settings > Custom settings. But it didn't work. Any extra seetings need to be added?

**Comment by benweet** [comment]
That would be in Menu > File properties > YAML properties, or you can add default file properties for all new files in the settings:

```
newFileProperties: |
  extensions:
    emoji:
      shortcuts: true
```

**Comment by amitguptagwl** [comment]
Sorry to bother you

I'm using https://stackedit.io/app# on chrome browser. And usin the settings that you've shared. But it's not working
![screenshot from 2018-06-13 16-02-43](https://user-images.githubusercontent.com/7692328/41346131-429e67c2-6f23-11e8-8133-f81a325314a1.png)

**Comment by benweet** [comment]
This will add properties to newly created files, so I guess it will work if you create a new file.

**Comment by amitguptagwl** [comment]
I've tried it in new file as well. Unfortunately it is not working.
