### ISSUE TITLE
Dockerfile appears to be outdated

### ISSUE THREAD

**Issue by FunTimeCoding** [benweet/stackedit#531]
due to referring to `FROM shykes/nodejs`, I left a comment there: https://registry.hub.docker.com/u/shykes/nodejs - maybe the quantal download servers are gone. Either shykes/nodejs should be updated to a newer base image, or this Dockerfile should refer to an alternative npm image?

**Comment by mitfik** [comment]
@benweet FYI: as I checked https://hub.docker.com/r/benweet/stackedit/ is not updated with this "fix"
