### ISSUE TITLE
TOC should produce an ordered list

### ISSUE THREAD

**Issue by JamellMoore** [benweet/stackedit#538]
At the moment the table of contents extension produces unordered lists. I think by default it should produce an ordered list because a table of contents is essentially an ordered list of the document sections. This would allow users to style their table of contents using the techniques described in this discussion - http://stackoverflow.com/questions/4098195/can-ordered-list-produce-result-that-looks-like-1-1-1-2-1-3-instead-of-just-1 , which is a common format in published documents.

I suggest that an option should be added to the extension which would allow the user to choose either an order list or unordered list for the output but make ordered lists default.

**Comment by tprochazka** [comment]
+1

**Comment by benweet** [comment]
Can be done in a custom template by rewriting the `tocToHtml` Handlebars helper.
