### ISSUE TITLE
Structure: Modularize build of Stackedit

### ISSUE THREAD

**Issue by jesperronn** [benweet/stackedit#542]
Obviously an enhancement. 

Stackedit has grown very big in terms of included javascripts, html, libraries.

As a developer, I want to be able to build only the parts I need. For example, if I don't need Mathjax, I want to be able to create a build without Mathjax.

This will probably require a more clean way to define extensions (or maybe I just have not figured out how to do it the 'right' way).

Let's discuss how the modularity could look. One example could be a /plugins folder with the following structure:

``` bash
plugins
└── mathjax
    ├── core.js        # any code that should be triggered by the main core.js
    ├── constants.js   # any constants that should be available globally
    ├── eventMgr.js    # any global event that should be triggered/subscribed to
    ├── index.js       # any routes that should be defined
    ├── main.js        # require.js loading of modules
    ├── bower.json     #bower dependencies if needed?
    ├── providers      # define providers here
    ├── publishers     # define publishers here
    ├── synchronizers  # define synchronizers here
    └── views          # all dialogs, new pages, etc should go here
```

I got this idea when looking at where hooks are added for example for Mathjax, MonetizeJS and Google Picasa integration. There is probably a thing or too I am missing out. For example, where is the correct place to attach browser events (such as click) to DOM elements?

I would like your feedback on this. Also, I am not aware if this structure is already possible. Furthermore, what do you think it would take to make the structure more modularizable?

**Comment by benweet** [comment]
Closing this as too old.
