### ISSUE TITLE
Feature request: class diagrams

### ISSUE THREAD

**Issue by anibalrivero** [benweet/stackedit#545]
It would be nice to have class diagrams in the same manner as the sequence diagrams.

Maybe, it could be implemented with yuml.me

Example,  this:

``````
```class
// Cool Class Diagram
[Customer|-forname:string;surname:string|doShiz()]<>-orders*>[Order]
[Order]++-0..*>[LineItem]
[Order]-[note:Aggregate root{bg:wheat}]
`` `
``````

would render like this:

![yuml class diagram](http://yuml.me/diagram/scruffy/class/%2F%2F Cool Class Diagram, [Customer|-forname:string;surname:string|doShiz%28%29]<>-orders*>[Order], [Order]++-0..*>[LineItem], [Order]-[note:Aggregate root{bg:wheat}])

Maybe this is possible with a custom user extension but I am not sure how.

**Comment by khatchad** [comment]
Is this not to be fixed (class diagrams)?

**Comment by PanderMusubi** [comment]
Using PlantUML doesn't seem a problem to me as one is only to use stackedit anyway.

PlantUML is available as a JAR and can also be run on the server on which stackedit runs instead of calling en publicly available web service.
