### ISSUE TITLE
Error opening file from dropbox

### ISSUE THREAD

**Issue by ryexley** [benweet/stackedit#558]
I recently encountered what seems to be a bug. I had a README.md document that I created in dropbox in a folder called `advertising-apps-guidance`. Whenever I would try to open that file from dropbox, the file would fail to open, and the app would go into "offline" mode.

I tried changing the file path to `advertising-apps/README.md` instead, and got the same issue. When I finally changed the file path to `ua-string-app-platforms/README.md` it worked fine.

Is there a problem with using the word "advertising" in path names when opening from dropbox, or something like that??

This happened when running from http://stackedit.io.

Thanks for a great tool...really love it.

**Comment by kbilsted** [comment]
I have the same issue only with google drive. I need to pause the plugin in order to open files :-1:
