### ISSUE TITLE
Live collaboration

### ISSUE THREAD

**Issue by kuba-orlik** [benweet/stackedit#560]
It would be awesome if StackEdit incorporated some kind of live collaboration features, for example by using Together.js I would love to be able to collaborate with my friends on a .md file in real time!

**Comment by theoryshaw** [comment]
possible to adopt https://github.com/ether/etherpad-lite for realtime editing?

**Comment by theoryshaw** [comment]
+1

**Comment by kencaron** [comment]
@theoryshaw I have doubts it would be easy to isolate just the collaborating aspect of etherpad-lite, which seems to be a more kitchen sink approach. A more realistic solution might be leveraging a lightweight library like [ShareJS](http://sharejs.org/).
> ShareJS is a simple (~4k LOC) coffeescript server & web client library for OT.

I'd assume most people don't need/want all the features of the Google Drive realtime API, which I assume offers accountability (who edited and when), multiple cursors, and the like. ShareJS seems to handle just what it needs to and nothing else.

Any thoughts on an easier to maintain alternative @benweet? IMO live collaboration would be a killer feature, worth paying for.

**Comment by benweet** [comment]
Yeah I'm working on something. It will probably rely on DynamoDB streams which is not ready for production yet (http://dynamodb-preview.s3-website-us-west-2.amazonaws.com/docs/streams-dg/About.html).
The problem with ShareJS and etherpad-lite is that they don't scale well. As soon as you want to add node workers you have to start doing hacks to route users of the same file to the same node.

**Comment by kencaron** [comment]
@benweet Awesome news, looking forward to it.

**Comment by gautiermichelin** [comment]
+1

**Comment by RoyiAvital** [comment]
Any update on that?
By the way, I paid using MozillaJS, is it for one year or lifetime?
