### ISSUE TITLE
Feature Request: Option to show the TOC in it's own fixed pane to allow for fast document navigation...

### ISSUE THREAD

**Issue by rchrdnsh** [benweet/stackedit#566]
Hi Ben and Co.,

Having the TOC in the bottom right hand corner buried inside a menu is nice, but it would be nicer to give the TOC the option to be displayed in it's own fixed, tall, narrow window pane on the left hand side of the interface, which would allow the user to navigate a large and complicated document with ease.

This feature would coincide with my other request for a combination markdown/HTML preview editor, where the editor would live on the right hand side and the TOC would live on the left hand side. Ideally the editor would take up about two thirds of the screen and the TOC would take up about one third.

Thank you for your work and consideration,

Richard Nash
Los Angeles, CA

**Comment by victorel-petrovich** [comment]
@brasofilo The new toc panel is great, but does not work (does not move the view on click of toc element) in full edit mode (while the usual one works). Only when both editor and preview sides are open, it works... Can it be fixed?..

**Comment by yaronyg** [comment]
Can we just have this as a feature in stackedit? I have to edit specs like [this](https://github.com/thaliproject/thali/blob/gh-pages/presenceprotocolforopportunisticsynching.md) and having a TOC open all the time so I can quickly navigate around the doc is pretty much a requirement.

Markdown, it's not for tiny files anymore. :)

**Comment by yaronyg** [comment]
BTW, I just realized that I can leave the TOC window open and click all I want. It's not quite as beautiful as having a dedicated pane but I have to admit that it does work (even if it interferes with the preview)
