### ISSUE TITLE
Feature Request : Plantuml as UML Diagram provider

### ISSUE THREAD

**Issue by gmarchand** [benweet/stackedit#569]
Hello 

UML Diagrams are not very powerfull. It will be very cool to integrate Plantuml.

Plantuml manages all UML diagrams and it does well.

Plantuml Javascript library exists : http://plantuml.sourceforge.net/codejavascript.html

Best,

Guillaume

**Comment by jldiaz** [comment]
The provided user extension works great as long as you do not use any UTF-8 char in the uml. For example, 

```uml
alice -> bob : foö
bob -> alice: bar
```

produces:

![clipboard01](https://cloud.githubusercontent.com/assets/66145/8617550/26463d0c-2705-11e5-8b11-280916dc14f6.png)

and the following does not produce an image, but an error:

```uml
alice -> böb : foo
böb -> alice: bar
```

**Comment by PanderMusubi** [comment]
Also in favor of having support for PlantUML, albeit with a webservice. Most users will not be using stackedit off-line anyway.

**Comment by PanderMusubi** [comment]
PlantUML is available as a JAR and can also be run on the server on which stackedit runs instead of calling the publicly available web service.

**Comment by mlopezgva** [comment]
There are many optional features, that would be one more.... AND: the "sequence" is buggy or at least incomplete.

**Comment by PanderMusubi** [comment]
What is exactly wrong with the sequence diagrams? In my experience the support for PlantUML is very good. So filing a bug report should help solve it.

**Comment by mlopezgva** [comment]
PlantUML is working fine.

I'm talking about the ```sequence interpreter.
the js-sequence says it supports participant's aliases, but I couldn't get
even the "participant" to work:


​
As you can see, I've created some participants, and it rendered them. But
when I tried to link them, it created NEW boxes, instead of the ones that
already were there.
I thought it was a "special chars ('ó') issue, but changind it to "TDocs"
didn't work either.

Also, since the js-sequence seems limited, I moved to plantUML/graphviz: it
has the most common UML diagrams, it's syntax is "consistent", and I
already have some diagram made with it :D that I can now properly document.
And it's far more customizable.

And, the "offline" issue is not really an issue: I can compose the document
offline, and the diagram later... and export even later...


2016-04-15 11:01 GMT-03:00 Pander <notifications@github.com>:

> What is exactly wrong with the sequence diagrams? In my experience the
> support for PlantUML is very good. So filing a bug report should help solve
> it.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/benweet/stackedit/issues/569#issuecomment-210474520>
>



-- 
Atte.,

*Manuel López*

**Comment by PanderMusubi** [comment]
Ah, good to hear. I can help out with overriding colors and fonts for PlantUML if you need.

**Comment by mlopezgva** [comment]
We're preparing a "default" skinparam file for PlantUML, but for
documentation purposes, I will propose to use a simple and effective:

skinparam monochrome true

and go with it: I'e tested with two diagrams and it looks good enough. :)
As I said, plantUML/graphViz is the best diagrammer I've found. Versatile.

I hope it makes through the StackEdit's mainstream (just to keep the
conversation on-topic! :D).

2016-04-15 11:28 GMT-03:00 Pander <notifications@github.com>:

> Ah, good to hear. I can help out with overriding colors and fonts for
> PlantUML if you need.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/benweet/stackedit/issues/569#issuecomment-210483067>
>



-- 
Atte.,

*Manuel López*

**Comment by mlopezgva** [comment]
We're preparing a "default" skinparam file for PlantUML, but for
documentation purposes, I will propose to use a simple and effective:

`skinparam monochrome true`

and go with it: I'e tested with two diagrams and it looks good enough. :)
As I said, plantUML/graphViz is the best diagrammer I've found. Versatile.

I hope it makes through the StackEdit's mainstream (just to keep the
conversation on-topic! :D).

**Comment by bohwaz** [comment]
I can't find any "custom extensions" setting in the settings?
