### ISSUE TITLE
Google Drive Synchronization does not work

### ISSUE THREAD

**Issue by juanique** [benweet/stackedit#59]
Hi, 

I just started using stackedit, I was looking for a markdown editor for Google Drive. This seems to be exactly what I need.

I was able to setup synchronization with Google Drive, if I open my Drive account I can see the file there. However, whenever I open the file to modify it, there's a sync animation on the side of the Google Drive icon, and after a while it stops with a  the message "a timeout occurred". Then, when I try to open the file from Drive on another computer, I see an empty page, as if all the changes I've done with the file are just stored locally on the computer where I created it. I also see the sync animation and later the timeout error on the second computer.

**Comment by khourt** [comment]
I start using stackedit in Firefox, when try sync have the problem about synchronization does not work...

Then, after read this treat delete the site configuration in my browser (Opera) and then this work. See in the console 1 problem about cookies. May be the problem is absolet configuration
