### ISSUE TITLE
Set margins and line spacing, dim MarkDown elements

### ISSUE THREAD

**Issue by samglover** [benweet/stackedit#63]
I just started using StackEdit, and wow, it's impressive!

Just a suggestion. It would be really nice to be able to edit the margins in the editor. I like to be able to work full-screen, but on a widescreen, that's just too wide. Line-spacing would be great for readability.

I also really like the way ByWord (and probably other editors) dim the MarkDown elements so you can focus on the content, not the markup.

Even without these changes, though, it's a great app. Thanks for building it!

**Comment by flokno** [comment]
Is customizing the line spacing possible as well?
