### ISSUE TITLE
Is it possible to use only the browser part of StackEdit?

### ISSUE THREAD

**Issue by codeablehq** [benweet/stackedit#646]
Hey I'm thinking of integrating StackEdit into a Rails app, so that either MarkDown or Markup (or even both) can be saved to PostgreSQL database. 

So I don't need the whole backend part (node.js and all the modules).

Is that possible?

**Comment by mhingston** [comment]
Should be easy enough, refer to the [dev guide](https://github.com/benweet/stackedit/blob/master/doc/developer-guide.md)

Build the project...

```npm install
bower install
gulp```

Move the contents of the views folder to the public folder.

Everything you need is in the public folder, open editor.html in your browser.

**Comment by hojas** [comment]
@mhingston It's working. But the whole *public* is too large. How to minify the dir ?

**Comment by mhingston** [comment]
If you load up *editor.html* and see what files it is getting from the *public/res* directory, use the dev console in Chrome and look at the Sources tab.

![screen shot 2015-01-19 at 09 30 48](https://cloud.githubusercontent.com/assets/9764437/5798392/88ff6b54-9fbe-11e4-86b4-02ba84eb8aac.png)

Looks like you can delete everything from the *public/res* folder except...

*bower-libs/MathJax*

That's assuming StackEdit doesn't load any other assets on demand from the *public/res* directory.

**Comment by jesperronn** [comment]
I suggest you take a look at https://github.com/benweet/stackedit/pull/640 which refers to my clone with branch https://github.com/jesperronn/stackedit/tree/split_panel_editor 

I tried to isolate the browser functionality in itself, and hope this will make it easier to use the editor part in other projects.

Let me know your thoughts

**Comment by jesperronn** [comment]
@hojas I created pull requests to address the size of the /public folder. See #551, #553, #582

**Comment by hojas** [comment]
@jesperronn Yes, I need a browser side stackedit.

**Comment by hojas** [comment]
@mhingston  @jesperronn  Could Browserify package all the js files into one file ? That will be more easy for only browser side to use stackedit.

**Comment by jesperronn** [comment]
@hojas Requirejs already packages all js and html views into one file. That's what `gulp` does.

I guess you could swap Requirejs for Browserify. But due to the current complexity of the code, there are a lot of changes you have to make (in all files)

**Comment by robpearlman** [comment]
Hi @hojas how did you go with this?
I am hoping to do a similar thing in python; saving and loading data in a postgres db. My javascript is abysmal and I have no experience in Node so while I can get a minimal application running (editor and the contents of res-min as far as I am concerned it is all magic.
Anyone who has any suggestions on how to hack this would be very welcome to contact me; I am certainly trying to avoid learning a whole new framework and will likely end up implementing a sub-optimal solution in python otherwise

**Comment by benweet** [comment]
You could use https://github.com/benweet/stackedit.js.
