### ISSUE TITLE
Charset not set when exporting HTML

### ISSUE THREAD

**Issue by RadixSeven** [benweet/stackedit#656]
When I export to disk, HTML output from StackEdit is UTF-8. I like that. However, IE11, Firefox 34.0.5, and Chrome 39.0.2171.95 m all fail to recognize the encoding without the appropriate headers. 

I have created a [Gist][gist url] with [test input][input url], [observed output][output url], and [expected output][fixed url]

[gist url]: https://gist.github.com/RadixSeven/f69648f6e239d8c9bb8d
[input url]: https://gist.github.com/RadixSeven/f69648f6e239d8c9bb8d#file-resultant-html-from-export-to-disk-html
[output url]: https://gist.github.com/RadixSeven/f69648f6e239d8c9bb8d#file-source-markdown-from-export-to-disk-markdown
[fixed url]: https://gist.github.com/RadixSeven/f69648f6e239d8c9bb8d#file-what-i-think-the-html-should-be

**Comment by benweet** [comment]
Please use "template output" for that. Thx.
