### ISSUE TITLE
dollar sign bug with tables....

### ISSUE THREAD

**Issue by theoryshaw** [benweet/stackedit#657]
![screenhunter_200 jan 09 19 30](https://cloud.githubusercontent.com/assets/507113/5689912/16e2ee90-9836-11e4-8e4a-d27356dfad96.jpg)

**Comment by theoryshaw** [comment]
helps if you escape the character, but not ideal
![screenhunter_201 jan 09 19 35](https://cloud.githubusercontent.com/assets/507113/5689929/afaf0d52-9836-11e4-82d9-a983dcef1489.jpg)

**Comment by benweet** [comment]
You have to disable mathjax extension in the settings.

**Comment by theoryshaw** [comment]
thanks.
