### ISSUE TITLE
This is Amazing!

### ISSUE THREAD

**Issue by sheafferusa** [benweet/stackedit#658]
Hello, I love this application and the fact that it is licensed under a truly open source license (Liberal license). I was just wondering, if I there is a pre-built version of the application, available anywhere. I request the developers to please guide me to the pre-built codebase, if available. 
And, great work! Keep it up! :)

Thanks & Regards

**Comment by sheafferusa** [comment]
Hello!? 
Can anyone help me with this? I am pretty eager to test it out. 

Thanks!

**Comment by benweet** [comment]
Hi @sheafferusa. You have to download the source code and run the app with node. The "getting started" section in the developer guide can help.
https://github.com/benweet/stackedit/blob/master/doc/developer-guide.md#getting-started
