### ISSUE TITLE
Any Keystroke Creates New Lines

### ISSUE THREAD

**Issue by CalculusWarrior** [benweet/stackedit#661]
Whenever I enter characters, StackEdit creates a new line. This rapidly becomes a problem as the document becomes extremely long, slowing down the app to the point of unusability.

I've tried it with and without auto sync on, as well on multiple devices, but I still get the new lines. I also encountered a scenario where the new lines would be generated constantly, without my typing. Fortunately, this hasn't resurfaced.

The new lines in question are all indented, making them a code view line:

    This is one of the lines in question, minus the text.

Hopefully this isn't a serious issue and can be resolved quickly.

**Comment by benweet** [comment]
I can't reproduce this. Can you provide more info and browser/OS versions you are using?
Thx.

**Comment by CalculusWarrior** [comment]
I'm on my Chromebook, so Google Chrome and ChromeOS. I tested it in Incognito Mode and the issue is gone.

However, I've cleared my cache and cookies but the issue persists in the standard browser.

**Comment by benweet** [comment]
I don't really know.. Could be a compatibility issue with one of your extensions.

**Comment by CalculusWarrior** [comment]
It's been resolved. 

The issue was the Grammarly extension, which does modify the text input area, causing the phantom new lines. 

Thank you for your assistance!
