### ISSUE TITLE
Loading bug

### ISSUE THREAD

**Issue by Swader** [benweet/stackedit#676]
More often than not, Stackedit fails to load. Sometimes it's super long cache manifest loads, sometimes it's this:

![stackbug](https://cloud.githubusercontent.com/assets/1430603/5917442/e38a31a8-a61c-11e4-9d7d-16c933178ab7.PNG)

The problem seems to be an oddly misencoded line:

![stackbug2](https://cloud.githubusercontent.com/assets/1430603/5917469/13e23562-a61d-11e4-9697-1f69975fa2de.PNG)

**Comment by 20015jjw** [comment]
Have the same problem on both my chromebook and fresh installed Windows 8 / Ubuntu...

Is it possible that all my chrome is on beta channel?

**Comment by webmink** [comment]
On my Chromebook, Stackedit will not load because of this error since it updated to  41.0.2272.32 this morning (beta channel).

**Comment by benweet** [comment]
I'll have a look ASAP. Sorry about that.

**Comment by vanbilt** [comment]
Experiencing this on Chrome as well. Seems to be working just fine in IE and FF. Thanks for looking into it. Love this application. I live in it daily!

**Comment by 20015jjw** [comment]
Just tested on stable channel and it loads fine.

**Comment by benweet** [comment]
Yeah it might be a bug in chrome beta as it doesn't happen systematically.

**Comment by 20015jjw** [comment]
What happens if you remove the buggy line?

**Comment by 20015jjw** [comment]
The bug is still present on beta channel, tested on both ubuntu (trusty, 64bit), windows 8 (64bit) and Android 5.0.2. Dev channel doesn't work neither. Unless this gets fixed, the local data will be lost as downgrading will erase all the data. _Is there a workaround?_ _Thanks_

**Comment by benweet** [comment]
Fixed in 4.3.9, just pushed to stackedit.io.
