### ISSUE TITLE
Cursor / page position lost during "toggle preview" functionality

### ISSUE THREAD

**Issue by trouxmitch** [benweet/stackedit#677]
When I'm writing in markdown view and have my preview pane closed, upon opening the preview pane the location of the page and my cursor suddenly shifts and I entirely lose my place. Additionally, it's very difficult in longer, more dense documents to find that location again without a bunch of hunting. It would be nice for the position to stay visible based around the cursor, the center of the page, or something somewhat standard...

I also have my page width ratio set to 1.5 in order to have more text visible when writing markdown vs. the more constraining margins...

**Comment by benweet** [comment]
Should be fixed in v5.
