### ISSUE TITLE
MathJax display mode failure in Blogger if "LaTeX mathematical expressions using $ and $$ delimiters" is enabled on upload

### ISSUE THREAD

**Issue by flengyel** [benweet/stackedit#681]
Since yesterday, pages on http://deniallogic.blogspot.com created with StackEdit.io stopped displaying display mode LaTeX. Inline LaTeX functions as expected. Pages not created with StackEdit.io have no problem with displayed math. An example is [this post](http://deniallogic.blogspot.com/2015/01/the-invisible-hand-of-ayn-rand.html), whereas [this post, recently updated with StackEdit](http://deniallogic.blogspot.com/2015/01/the-unbearable-notation-of-logic.html) will display some displayed equations, which then vanish. The same occurs with every page updated, even if updated in place. The difference between the HTML-CSS in the markdown translated pages and the directly edited pages is considerable.

**Comment by flengyel** [comment]
I find that disabling "LaTeX mathematical expressions using $ and $$ delimiters" in Basic Settings, then re-enabling it, and finally re-uploading the document seems to have fixed this trouble--for now.

**Comment by flengyel** [comment]
It seems, after further experimentation, that I must disable both "LaTeX mathematical expressions using $ and $$ delimiters" and "Markdown Extra/GitHub Flavored Markdown syntax" in order for MathJax to work as expected (though backslashes have to be quadruply escaped in XyJax). The HTML-CSS is reduced considerably as well.

**Comment by benweet** [comment]
You need to republish your post with the new StackEdit 4.3.9 (the upgrade should happen in background automatically). Sorry about that.

**Comment by flengyel** [comment]
Seems to happen again in 4.3.11.
