### ISSUE TITLE
Dropbox sync spins and spins, sync doesn't happen

### ISSUE THREAD

**Issue by todgillespie** [benweet/stackedit#684]
Env: OSX Yosemite / Google Chrome
1. Select "Open from Dropbox"
2. Login to Dropbox and select a file
3. Make changes to file
4. Select "Allow" in Dropbox application popup
5. Cursor in Stackedit spins and spins (waited 5 mins for it to stop, it didn't stop)
6. Noticed lots of bandwidth in both directions assigned to Chrome (I use Little Snitch to monitor network connection)
7. Give up. Did the file change in Dropbox? No.

**Comment by benweet** [comment]
May take a while the very first time. It's reading the whole change feed.. I assume you have a lot of files in your account.

**Comment by todgillespie** [comment]
I have a pretty big Dropbox footprint, over 100MB of storage and 398 total files with the .md filename extension scattered throughout the directory tree. I've also had files in this Dropbox account for coming up on 10 years, so I'm guessing the change feed is pretty long? How long do I need to wait?

**Comment by todgillespie** [comment]
OK, I stepped away for a while, and tried again. This time it seems to have worked. Nice looking product by the way. So extremely needed!

Cheers,

Tod
