### ISSUE TITLE
When exporting Markdown to HTML, all footnotes after the first are missing

### ISSUE THREAD

**Issue by rjgotten** [benweet/stackedit#685]
I have a Markdown document that declares multiple blocks of footnotes using the `[^1]: ...` syntax. In the live preview side-panel I can see that the the footnotes collect correctly at the bottom of the document, as one would expect.

However; when exporting the document as HTML, all footnotes but the first disappear from the exported document. This happens with both of the HTML-related export options ("As HTML" and "Using Template").

[EDIT]
This seems to happen when the document itself ends with a fenced code block. Adding something as simple as an HTML comment block at the bottom of the Markdown document triggers the notes to appear correctly.

[EDIT]
Seems this is a problem with partial updates of the document when exporting to HTML
Forcing a full reload/reparse of the document before executing an HTML export fixes the problem.

A very similar issue with out-of-date content occurs with the `[TOC]` tag, which is also fixed by forcing a full reload/reparse before export.

**Comment by benweet** [comment]
Right. That's a regression. Will try to fix this tonight.

**Comment by flengyel** [comment]
Same thing happens to me--had to disable MathJax. Also, the old problem with disappearing MathJax has reared its head again. 4.3.9 jumped to 4.3.11. Could the user specify which version to use?
