### ISSUE TITLE
Dropbox saving fails

### ISSUE THREAD

**Issue by rotatingJazz** [benweet/stackedit#688]
I just cloned and self-hosted `stackedit` on a custom domain (i.e. not `localhost`). When trying to sync to `dropbox`, it fails because after the authorization is given, the token receiving page is `http://localhost/html/dropbox-oauth-receiver.html#access_token...`. 

Is there a configuration option to make `stackedit` aware of the site name that it is being hosted under so that it does not ask to receive the token in `localhost`?

**Comment by benweet** [comment]
You need to setup your own application ID and change the oauth credentials. I don't provide support for that. Sorry.

**Comment by rotatingJazz** [comment]
No problem, thanks for the pointer! :+1:
