### ISSUE TITLE
Single newlines cause line break in Markdown Extra mode

### ISSUE THREAD

**Issue by emlyn** [benweet/stackedit#692]
Not sure if this is intended behaviour or not, but when I enable Markdown Extra mode, then line breaks in the left pane cause a line break in the right pane. I thought single line breaks were supposed to be ignored in markdown?

**Comment by benweet** [comment]
That's "GFM newlines" feature (as here on GitHub). You can disable it in Settings>Extensions>Markdown Extra.

**Comment by emlyn** [comment]
Thanks - I had assumed that GFM was like GitHub README.md files, which don't behave like that, I hadn't realised that markdown in comments behaved differently.

**Comment by fenbf** [comment]
how to disable GFM newlines in v5?
