### ISSUE TITLE
Feature Request: Epub Export

### ISSUE THREAD

**Issue by pastorryanhayden** [benweet/stackedit#693]
Hi, I just discovered stackedit and I'm blown away.  It's the kind of thing I didn't think was possible a couple of years ago.  It's made my even consider switching all of my writing to stackedit and purchasing a chromebook.
My one hangup is ePub export.  Currently, I do all of my writing in Ulysses (for mac).  I then export to ePub and use the ePub on a tablet for speaking notes.  I do this at least three times a week.  
ePub or Mobi export from stackedit would be a great feature and would ease my transition to the new platform.
(By the way, I'm a pastor who does technology consulting for pastors - this is a common usage scenario for us. If this was implemented, I'd immediately start recommending this.)

**Comment by benweet** [comment]
Fixed in the v5.
