### ISSUE TITLE
Feature request: add etherpad-like capabilities for simultanous editing of a document

### ISSUE THREAD

**Issue by funkyfuture** [benweet/stackedit#696]
with [Etherpad](http://etherpad.org/) users on different clients can edit the same document at the same time. any changes by users are streamed immediately to other user's editors where they are marked with colors according to the author.
my experiences with it clearly are, that teamwork on a document is much more effcient. (rather than to wait until someone else finished her changes for review and annotation.)
yet, Etherpad lacks serious markup-features. it's also a pita to use the results in other formats.

imo simultanous editing of a document would be another killer-feature for stackedit.

**Comment by theoryshaw** [comment]
+1

**Comment by patriklindstrom** [comment]
+1

**Comment by todgillespie** [comment]
+1

**Comment by RoyiAvital** [comment]
+1
