### ISSUE TITLE
Can't sign-in as Sponsor

### ISSUE THREAD

**Issue by rlktradewright** [benweet/stackedit#700]
I've signed up as a Sponsor, paid my fee, but I can't find a way to actually sign in in StackEdit. If I try to export my document to PDF, the 'Sponsor only!' dialog appears. If I click the 'sign in' link in the dialog, another browser tab at monetizejs.com appears briefly and then vanishes again, but gives me no opportunity to enter username and password.

I've tried this on both Windows 7 and Windows with 8 with Internet Explorer 11.

However I've just noticed that it does work properly with Chrome.

Please fix for IE.

**Comment by benweet** [comment]
Right, I'll have a look ASAP, probably tonight.

**Comment by benweet** [comment]
Fixed. Sorry about that.
You may have to refresh the page in StackEdit once you are signed in.
