### ISSUE TITLE
Is it possible to override base.css in Settings?

### ISSUE THREAD

**Issue by winstonford** [benweet/stackedit#720]
Is there anywhere in the settings to drop in css rules to override https://stackedit.io/res-min/themes/base.css

For instance, I like the style, but I do not want body copy justified.

I take it could point to my own css, but then I have introduce an editor + ftp app or terminal into the tool chain.

**Comment by benweet** [comment]
Please have a look at https://github.com/benweet/stackedit/issues/137 for custom css.

**Comment by winstonford** [comment]
Thx, done:

In Settings->Extension->User Custom

userCustom.onReady = function() {
    $('head').append('<style>#preview-contents {text-align: left}</style>');
};

**Comment by winstonford** [comment]
Thx, done:

In Settings > Extensions > UserCustom extension

userCustom.onReady = function() {
    $('head').append('<style>#preview-contents {text-align: left}</style>');
};
