### ISSUE TITLE
Is task list of GFM supported as an intrinsic feature?

### ISSUE THREAD

**Issue by PaleNeutron** [benweet/stackedit#727]
I am new to stackedit, I know this topic has been discussed in  #324 .

But it seems the feature does not added to stackedit, people have to use it by a custom extension.

This feature should belong to GitHub Flavored Markdown syntax so why not make it intrinsic?

**Comment by Nikita240** [comment]
+1

**Comment by PaleNeutron** [comment]
Further more, the solution in #324 only works in preview page but export/save.

I have tried other tools like Python-Markdown, they translate task list to `<input type = "checkbox">` tag and looks well

**Comment by eikelben** [comment]
+1

**Comment by technobly** [comment]
+1

**Comment by theminor** [comment]
+1 - UserCustom extensions don't seem to be supported in version 5, so the solutions mentioned above can't be implemented. More information here:
https://github.github.com/gfm/#task-list-items-extension-

**Comment by benweet** [comment]
Fixed in v5.11.
