### ISSUE TITLE
Images alignment and (re)size quality

### ISSUE THREAD

**Issue by CieNTi** [benweet/stackedit#734]
Hi,

First of all, thanks for this awesome editor.

Second, I'm a proud supporter who now have the nice pdf output. Improved with header and footer throw a very good looking documents, but this is broken when the images are:
- Not centered
  - Tried with &lt;img style="nomatterwhat" /&gt; but _style_ param is deleted
  - Tried postProcessing it with no luck

How can I align an image?
- Bad sized
  - Tried adding a G+ image with =sSIZE: Perfect look on stackedit, pixelized results on pdf output. This is not hgappening if you left automatic size

How can I get right image quality?

Thanks in advance and best regards,
CieNTi

**Comment by RoyiAvital** [comment]
Have you managed to align images to the center?

Thank You.

**Comment by RoyiAvital** [comment]
Anyone managed to control the alignment of Photos?

**Comment by RoyiAvital** [comment]
?

**Comment by lovemyliwu** [comment]
@RoyiAvital Not support.

**Comment by benweet** [comment]
Added image size support (see https://github.com/benweet/stackedit/issues/164). Align is via the `align` HTML property.
