### ISSUE TITLE
What happened with aceEditor ?

### ISSUE THREAD

**Issue by CieNTi** [benweet/stackedit#735]
I tried to follow some examples based basically on:

```javascript
var aceEditor = undefined;

function(editor){
aceEditor = editor;

aceEditor.method(foofoofoo);
```

But never works. I read somewhere in near past that aceEditor was removed ... but I didn't find any official sign of that, so ..

¿Is that method broken or definetively aceEditor was removed?

Thanks in advance,
CieNTi

**Comment by jesperronn** [comment]
As far as I can tell, ACE editor is long gone. I updated the developer doc in a pull request (#728) to reflect that.

**Comment by CieNTi** [comment]
>.<

Why that is not documented? Or if it already is, why so hard to find?

Thanks for the information, spent many time without sense hehehe
