### ISSUE TITLE
TOC anchors - Generate Unique IDs while generating anchors for TOC

### ISSUE THREAD

**Issue by santosh-d3vpl3x** [benweet/stackedit#742]
Hi there,

I have started using stackedit for writing my blog posts. It is awesome! BTW , I have found an issue. TOC generated by stackedit is little buggy when it comes to posting to blogger from stack edit. 

As you might know blogger shows around 7 posts on home page by default. As per my observation, TOC is generated from header tags in HTML/MarkDown. I always have `References` as a header `h2` in each of the post. So there would be 7 References headers on homepage. When I click on References link from TOC of 7th post, it brings me to References anchor of first post. That is how DOM selectors work. A good way to tackle this problem would be to make these IDs unique.

As per my guess, other blog engines might be having same issue. 

Do we already have an option to introduce unique IDs to these anchors? I have removed the post temporarily from the blog but you can easily verify this issue. If you need any kind of help while reproducing the issue, please let me know.

Thanks again for such an awesome tool and I would love to see it for desktop and tablets as well.

**Comment by santosh-d3vpl3x** [comment]
Well, I have used anchor syntax as mentioned by MarkDown Extras.
`## References ## {#1234-references}` seem to have solved this issue. But doing this automatically, I mean, providing an option to prepend/append a random alpha numeric string to anchor would be a nice addition.

**Comment by benweet** [comment]
Closing this as `[TOC]` markers are not supported anymore. You can write a custom template though to convert them as described here:
https://community.stackedit.io/t/replace-toc-markers-with-tables-of-contents-in-your-exports/33
