### ISSUE TITLE
Cannot synchronize nor save

### ISSUE THREAD

**Issue by d4nyll** [benweet/stackedit#743]
Since yesterday, I have not been able to synchronize nor save anything from StackEdit to Google Drive. I have tried synchronization to Dropbox neither.

The error message I get at the bottom of the screen is `A timeout occured`.

In the console, I also get the error:

```
Failed to load resource: the server responded with a status of 401 (Unauthorized) https://monetizejs.com/authorize?immediate=true&response_type=token&client_…8iLhhO&redirect_uri=https%3A%2F%2Fstackedit.io%2Feditor%23&q=1425716993634
```

**Comment by tgirardi** [comment]
Same for me

**Comment by benno208** [comment]
+1

**Comment by knight9999** [comment]
Same for me. Everytime I reset application.

**Comment by benweet** [comment]
Closing as too old.
