### ISSUE TITLE
Google Drive Non-Root Folder Does Not Sync

### ISSUE THREAD

**Issue by arbourd** [benweet/stackedit#750]
Google Drive Open, Save and Sync all work as intended when using the root directory of an account.

When you change the root directory for Stack Edit, the files no longer sync and timeout.

There are no console errors or other warnings.

I am able to reproduce this on different computers, on different networks between 2 different Google Accounts. Tested on Chrome in incognito mode (no addons), and without.

**Comment by apetherick** [comment]
+1, also having this problem.
