### ISSUE TITLE
Comments broken

### ISSUE THREAD

**Issue by carter-lavering** [benweet/stackedit#759]
I'm using StackEdit in Chrome on Windows 8.1 and when I post comments they seriously slow down my browser. Since Chrome is sandboxed it doesn't affect the rest of the browser, but the tab is frozen for about 15 seconds before it decides to respond to anything. Then that triggers other bugs like the cursor always wanting to go back to the same place once you start typing or the screen moving up a half line every time you type a character and then going back down again and generally being really annoying.

Other than that, great tool. Thx!

**Comment by benweet** [comment]
Closing as too old.
