### ISSUE TITLE
PDF layout/design questions

### ISSUE THREAD

**Issue by Slind14** [benweet/stackedit#761]
Hey,

I really don't like the pdf export look. I know that I can edit the template, but is there any documentation on it? I kinda tried to use the html template but it looks just the same, with huge `<h1/h2/h3>` head-lines..

What bugs me the most is that there is no page break control. E.g. a setting like "do a page break if the lines after the headline is landing on the new page"..

Do you have any tips for me?
(I really love the look inside the editor and html export :))

**Comment by ddoyon** [comment]
I had the same gripe about the margins around the headers.  I added this code to the default template to quickly cut down on the margins:
<style>h1,h2,h3 {margin-top: 21px;margin-bottom: 10.5px}</style>

You can add this line to the custom extensions so that it renders the same in the editor:
userCustom.onReady = function() {
 $('head').append('<style>h1,h2,h3 {margin-top:21px;margin-bottom:10.5px</style>');
};

**Comment by technobly** [comment]
I fixed the missing page break functionality by doing a Google search that turned up a sweet trick that works great!
https://github.com/benweet/stackedit/wiki/Templates#export-to-pdf-with-page-breaks

You still have to export, look at it, edit, export again... but it's pretty nice.

**Comment by Slind14** [comment]
hmm ok thanks. would be great those in by default to save the extra work. I kinda do prefer reStructuredText atm, cause of these issues. (ofc, it is not stackedit related but this issue let me switch, kinda sad, as I really like the editor, its pdf export is just not worth it atm)

**Comment by NikoKatich** [comment]
Hi there
I have the same trouble with marigns in PDF.
Pagebrake hint that @technobly use works fine. But when I try to set headers margins with the same way (Settings->Advanced->PDF Template settings) it doesn't work in exported pdf document (margins doesn't chenges).
````
Here is my <style> section from PDF Template:

<style>
.pagebreak
{
    page-break-after: always;
}
h1
{
    margin-bottom: 10px;
}
</style>
````

I also try to set margins in custom extension as @ddoyon do, but this works only for html output document, nor for pdf.

What I'm doing wrong?

**Comment by benweet** [comment]
Now in the v5, you can use `<div class="page-break-after"></div>` to insert a page break in your file.

**Comment by sidneydemoraes** [comment]
Unfortunately, `<div class="page-break-after"></div>` is not working neither in editor or app versions.

**Comment by mikpin** [comment]
Still the same problem.

> Unfortunately, <div class="page-break-after"></div> is not working neither in editor or app versions.
