### ISSUE TITLE
Can't see google docs

### ISSUE THREAD

**Issue by khatchad** [benweet/stackedit#763]
When I try to synchronize from google drive, it only shows my folders. I was expecting to see my google docs for which I may import.

**Comment by benweet** [comment]
You're probably trying to select a folder in the "save on Google Drive" dialog. Use the "Open from Google Drive" dialog instead.

**Comment by khatchad** [comment]
Nope, I'm clicking "open."

**Comment by khatchad** [comment]
OK I think I misunderstood. It only works with text files?

**Comment by purldator** [comment]
To my knowledge from what I've seen, StackEdit only manages .txt and .md/.markdown
