### ISSUE TITLE
Can't sync to GDrive

### ISSUE THREAD

**Issue by carter-lavering** [benweet/stackedit#768]
When I try to sync a document to Google Drive, it works at first but then doesn't sync any updates. I get this notification:

![screenshot 45](https://cloud.githubusercontent.com/assets/8867205/6930516/de102a66-d7b8-11e4-8c56-f219ddd5cc53.png)

**Comment by justinstern** [comment]
I don't get this particular error, though when I open up the Synchronize > Open from Google Drive menu, although all my google drive folders are listed, they are empty of all documents.  Can't seem to get any files to synchronize over for opening

**Comment by Kensai** [comment]
I find the same error. Have been able to do the first sync, but thereafter it doesn't work. Also happening on Dropbox.

**Comment by Dzenly** [comment]
The same. Only the frist saving to GDrive works correctly.

**Comment by jpaugh** [comment]
@Dzenly Versioning is a part of the way Google Drive functions. (You can always access previous versions of a file, and whenever you upload a new document with the same name & type as a previous file, it will replace the existing as the latest version.)

**Comment by benweet** [comment]
Closing as too old.
