### ISSUE TITLE
Sync Cookie or local cache to Google Drive or DropBox

### ISSUE THREAD

**Issue by bbhenry** [benweet/stackedit#77]
I have several articles in local storage and are synced with Blogger and Google Drive at the same time. There was this incident that I need to clear my cookies and later found out it also cleared all my hard work in StackEdit.

I was fortunate that I have synced 90% of my Markdown files to Google Drive and I was able to import them back. But then I had to manually associate each one of them back with the Blogger posts. This let me wondering if it's possible to allow backup/sync of your local setting together with all the cookie and cache to Google Drive so there is this extra protection and when you move to another computer and wanted to work on the same thing. You just need to import the cookie and cache, and voila - you have everything you need to work from a new environment.

**Comment by benweet** [comment]
Workspace synchronization in v5 covers that.
