### ISSUE TITLE
Escaped characters are incorrectly highlighted in the code view

### ISSUE THREAD

**Issue by KrofDrakula** [benweet/stackedit#770]
When editing a document, I noticed that using asterisk symbols to mark text as bold confuses the highlighter when using escaped asterisk characters:

```
for example, multiplication: **\***
```

We expect the highlighter to parse the first and last two asterisks as metacharacters while the middle escaped one is presented as plain text, but the highlighter decides to mark the last asterisk as plain text, which is incorrect:

![capture](https://cloud.githubusercontent.com/assets/112161/6986263/507fefe4-d9f0-11e4-87ef-9fa4093f91bf.PNG)

**Comment by benweet** [comment]
Fixed in v5.
