### ISSUE TITLE
Sharing does not work: cannot access the shared link, 404

### ISSUE THREAD

**Issue by 5nizza** [benweet/stackedit#784]
I set up the couchDB instance in smileupps, then set the link to my couchDB on stackedit.io. 
It seems that it works fine (no errors, it synchronizes periodically).

But sharing with others does not work -- I put the link into another browser (firefox), and it cannot load it, complains "404".

Here is the link i share:
https://stackedit.io/editor#!provider=couchdb&id=hOvsj1PjYkhlyAsQjcJwylcN

Guys, can anyone access it?

**Comment by benweet** [comment]
The custom instance URL has to be configured for every user you want to share file with. See https://github.com/benweet/stackedit/issues/707.

**Comment by 5nizza** [comment]
If I save a document to the public couchDB of stackedit.io, 
can people who do not have the shared link read/edit the document? 
(and find it via google search, etc.)

**Comment by benweet** [comment]
Yes. There is an API to list all the documents in CouchDB which is accessible to anyone.
