### ISSUE TITLE
Weird text justification (not just for titles)

### ISSUE THREAD

**Issue by ghost** [benweet/stackedit#797]
The issue discussed [here](https://github.com/benweet/stackedit/issues/392) seems to apply to all text in the document, not just titles. Periodically throughout my document, there will be lines of otherwise normal text that appear very stretched out, with the equivalent of a hundred or more spaces between words.

Is there a workaround for this? I'd be content with just disabling justification completely.

**Comment by jclark-dot-org** [comment]
+1 for Option to disable completely.  Never want full justification.

**Comment by benweet** [comment]
Closing this. Text justification is disabled in the v5 (https://stackedit.io/app)
