### ISSUE TITLE
Expand on Dropbox Permission Request

### ISSUE THREAD

**Issue by diego898** [benweet/stackedit#80]
Hello, 

When I tried to import a file from dropbox a popup opened up and I logged in. It then had me choose the file I wanted to open. It then asked me to authorize stackedit to access and edit all of my files. Is it possible to just grant access to one file at a time? 

If not, perhaps add a section the "Welcome Document" explaining the permissions required and why?

**Comment by mvayngrib** [comment]
+1 for limiting permissions. I love the interface (awesome job guys!) but I don't want to give StackEdit access to all my files, to the extent of not using StackEdit. There's plenty of granularity to explore in permissions: https://www.dropbox.com/developers/reference/devguide  I don't see any reason to ask for access to all files. Come on guys! I want to use your app!

**Comment by robsonsobral** [comment]
Since everything is executed on the user's browser and never transmitted to anywhere, I don't see reasons for concerns. At the end, you're giving permission to yourself or like to a desktop app.

**Comment by mvayngrib** [comment]
i believe you, but you're basically saying to me: give us everything you have, and trust that we won't abuse the privilege. I don't see why I should do that when I know for a fact you can ask for much less and perform the same functionality.

**Comment by benweet** [comment]
@mvayngrib permissions can be changed in Settings>Advanced>Permissions.

**Comment by mvayngrib** [comment]
@benweet awesome, thanks for pointing that out. And props, you've made a beautiful app
