### ISSUE TITLE
Can StackEdit be used as a front-end editor for Jekyll?

### ISSUE THREAD

**Issue by erlend-sh** [benweet/stackedit#801]
I've posed this question on the Jekyll community forum. I would greatly appreciate your input:

https://talk.jekyllrb.com/t/an-idea-for-front-end-editing-in-jekyll-via-the-github-api-and-web-based-markdown-editors/737?u=erlend_sh

**Comment by jspizziri** [comment]
+1 

I'm actually looking into using stackedit as a frontend for [mkdocs](https://github.com/mkdocs/mkdocs). Currently you can sync to google docs and dropbox, but I think it would be great to be able to just commit directly to a git repository.

I think that would be the first step in achieving both desired features (and honestly that might be it).

**Comment by Greg-Boggs** [comment]
+1 for this. Not so much for Jekyll, but for adding better support for Github. It can publish markdown to Github, but it would be awesome if it could also browse and open preexisting files.

**Comment by erlend-sh** [comment]
Pretty much the exact use case I described in the link above is easily doable with [wikihub/wiki-hub](https://github.com/wiki-hub/wiki-hub).

**Comment by ShikherVerma** [comment]
+1

**Comment by benweet** [comment]
In short, yes it can.
