### ISSUE TITLE
ACE ? 

### ISSUE THREAD

**Issue by mc007** [benweet/stackedit#802]
hi,
looks there is no ACE editor being used anymore in stackeditor. The docs mention a callback "onACEReady" or so...

However, which version or tag was actually using ACE? 

thank you, 
awesome tool, love it!

**Comment by jesperronn** [comment]
I updated teh developer guide in pull req #728, which is apparently not merge in yet.

**Comment by mc007** [comment]
hi,
thanks, but was there ACE ever in place or not, and which version more or less?

I am trying to get auto-completion and other things for the left side, 
thanks!

**Comment by jesperronn** [comment]
I am sure you can find the ace editor in the git history somewhere.

On Thu, May 14, 2015 at 2:00 PM, mc007 <notifications@github.com> wrote:

> hi,
> thanks, but was there ACE ever in place or not, and which version more or
> less?
>
> I am trying to get auto-completion and other things for the left side,
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benweet/stackedit/issues/802#issuecomment-102012747>.
>



-- 

Jesper Rønn-Jensen
Nine A/S
Mobile: +45 2989 1822
Blog http://justaddwater.dk/
jesperrr@gmail.com (Private e-mail and Google Talk IM)

**Comment by mc007** [comment]
ok, no biggy, thanks.
