### ISSUE TITLE
Add "App folder" access for dropbox

### ISSUE THREAD

**Issue by pulkitsinghal** [benweet/stackedit#815]
What is the reason behind the need for full access to dropbox? There are other apps that make it work with "App folder" access which gives them full control of a folder I created just for them inside dropbox.

Is it time that needs to be spent or is it a technical impossibility? Please let me know, keeps me up at night.

**Comment by MidnightLightning** [comment]
This is possible through the Settings menu; there's a checkbox to enable restricted access to Dropbox.
