### ISSUE TITLE
checkbox not work in stackedit

### ISSUE THREAD

**Issue by zhangjg** [benweet/stackedit#816]
I  write the html tag like this:

``` html
<input type="checkbox"></input> hello
```

That is not work in stackedit.

**Comment by orschiro** [comment]
I am interested in this, too. Is task list/checkbox support planned for the future? 

Thankfully,

Robert

**Comment by benweet** [comment]
Use GFM task list in v5.11.

**Comment by chilismaug** [comment]
I have checkbox items working in my document using the Chrome app which appears to be StackEdit 4. The uri for that app is https://stackedit.io/app# 
When I imported and opened up the same document using StackEdit 5 web app https://stackedit.io/editor , the checkboxes are lost in render panel.



![stacked4](https://user-images.githubusercontent.com/1030122/89127412-3916f480-d4bb-11ea-9bea-291e83cb72c9.png)


![stacked5](https://user-images.githubusercontent.com/1030122/89127469-acb90180-d4bb-11ea-9c25-40c921c31f95.png)
