### ISSUE TITLE
Stackedit Chrome app like the default application?

### ISSUE THREAD

**Issue by in-in** [benweet/stackedit#817]
Is there a way to add _Stackedit Chrome app_ like the default application for files _.md_ on my Linux Mint system?

**Comment by WesternGun** [comment]
Yes, there is a way.

1. You should install the app from Chrome App Store(but it seems impossible already).
2. You now can see in `chrome://app` StackEdit. You open it and it just loads another tab with StackEdit.io as URL.
3. At this moment, you can right-click on the icon of StackEdit in the app page, and "create direct link". You can create in desktop or in start menu.
4. Checking the direct link created, you will see the destination is:

    "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  --profile-directory=Default --app-id=iiooodelglhkcpgbajoejffhijaclcdg
