### ISSUE TITLE
Paste changes cursor position

### ISSUE THREAD

**Issue by liteserver** [benweet/stackedit#818]
First of all, Congratulations for the good work! It's nice! :smile:

When I paste a text **that contains line feed** in the editor the cursor is placed one character after the pasted text.

Try to paste a copied line (including the line feed) twice between other 2 lines (pressing Ctrl+V twice).

**Comment by liteserver** [comment]
I noted now that it moves 1 additional character for each line feed included in the copied text.

**Comment by benweet** [comment]
Should be fixed in v5.
