### ISSUE TITLE
Fenced code block syntax

### ISSUE THREAD

**Issue by nice-shot** [benweet/stackedit#822]
Can you add support for GFM's fenced code block syntax? i.e:
<pre lang="no-highlight"><code>```python
print "my code!"
```</code></pre>
I'm not asking for smart syntax highlighting but just the ability to write code blocks this way will be very convenient.

**Comment by Mindstormer619** [comment]
Um, it exists. You can already do exactly this.

![image](https://cloud.githubusercontent.com/assets/441849/9728463/9c90ddce-5625-11e5-8f13-8dbce5a33716.png)

**Comment by nice-shot** [comment]
I'm almost positive I couldn't do it at some point. Anyway you can close this issue now. 
Thanks
