### ISSUE TITLE
Open all notes from a folder

### ISSUE THREAD

**Issue by caspyin** [benweet/stackedit#875]
I have a notes folder in Google Drive. I want access notes from both desktop and mobile. Currently it looks like I have to open an individual note on my desktop and then do it again on my phone. Which is pretty tedious if I want to access a lot of notes. Is there a way to just open all the notes in a folder?

**Comment by caspyin** [comment]
Update: I just discovered that I can do a multi-select for both Google Drive and Dropbox when selecting files.

**Comment by benweet** [comment]
You can use a Google Drive workspace for that.
