### ISSUE TITLE
Narrower permissions for Google Drive

### ISSUE THREAD

**Issue by vermorel** [benweet/stackedit#878]
I am usually worried about granting full-account permissions on apps for services like Google Drive. Considering the nature of StackEdit, I would be much more comfortable if the app was only requesting [Per-file access to files created or opened by the app](https://developers.google.com/drive/web/scopes). Indeed, there is little reason to request access for more than one file at a time. Then, if something goes wrong on StackEdit side, the damage is limited to the files actually handled by the editor itself.

**Comment by RoyiAvital** [comment]
+1
Very very important in my opinion.
The narrower, the better.

**Comment by jlapenna** [comment]
Yeah, this would be really nice to have.

**Comment by RoyiAvital** [comment]
I don't think anyone still developing it.

**Comment by mtrienis** [comment]
+1

**Comment by benweet** [comment]
Fixed in v5.
