### ISSUE TITLE
Publishing the Document to Google Drive results in broken TOC.

### ISSUE THREAD

**Issue by mirzu** [benweet/stackedit#880]
Publishing a document results in a broken TOC. Only the first letter of the first line is published. 

Resulting TOC:
<img width="133" alt="frontline_medical_architecture_-_google_docs" src="https://cloud.githubusercontent.com/assets/251658/10056627/8c525004-6201-11e5-94df-4cbb5507129f.png">

TOC in preview:
<img width="295" alt="stackedit_ _editor" src="https://cloud.githubusercontent.com/assets/251658/10056646/a4418568-6201-11e5-9c8e-4198745bdbd3.png">

**Comment by benweet** [comment]
I guess that would depend on the template you use.
