### ISSUE TITLE
does stackedit is still in active development?

### ISSUE THREAD

**Issue by vladejs** [benweet/stackedit#889]
Hi, iam wondering if stackedit will continue its development and fix new issues. I see new ones everyday, but last commit was made several months ago.

**Comment by benweet** [comment]
Yes, it is.

**Comment by jesperronn** [comment]
@vladejs My branch /jesperronn/stackedit has a lot of updates and also an attitude towards a more independent, standalone, embeddable version of Stackedit.

Unfortunately, I have made almost no updates for the last months. But I am very willing to take in Pull-requests, so please contribute :+1: 

https://github.com/jesperronn/stackedit/

**Comment by vladejs** [comment]
@jesperronn , it seems like you stripped down almost every feature i need from Stackedit. My needs for stackedit right now are:

1. extend image sintax with new capabilities: assign class, width, height and  target attributes directly from markdown. Something like:

![image description](http://the/url/name.jpg "title" "width:800,height:300,class:'aligncenter image',target:'_blank'")

That should be translated to <img src="url" width="800" height=300 class="aligncenter image" target="_blank" />

2. Insert code snippets and shortcuts. I want this feature in stackedit 4 because issue [92](https://github.com/benweet/stackedit/issues/92) is no longer working.
