### ISSUE TITLE
monetize.js sucks....

### ISSUE THREAD

**Issue by stratosgear** [benweet/stackedit#890]
Just wanted to let you know that the user experience from monetize.js makes me "hate" your product...

Although I was impressed by the product enough so, that I subscribed for a year, once I tried to stop my subscription at year's end, monetize.js insisted on keep charging my card. Luckily the card I had on file has expired, but monetize.js insisted to keep trying charging the card every other week or so. I kept getting these email notifications that ```"Your payment has failed"``` although I had unsubscribed.

There is no contact point to get in touch with any monetize.js people (although their emails appear to be sent from them, ending with:

    Sincerely,

    The MonetizeJS team

and my emails to the app creator were unanswered.

So after 3-4-5 attempts to charge my card  I just closed/canceled my whole monetize.js account in the hopes that this will actually stop the attempts to charge my card!

Sorry, no other way to inform you of the sour taste in my mouth from this experience since I cannot get in touch with the "app creators" or "contact developer" option as suggested from the monetize.js email as I do not have an account with them anymore.

That was a very frustrating user experience and I think it has nothing to do from your part, but nonetheless it's still a negative experience from using your product.  In all honesty I would actually warn people that want to subscribe to this service regardless of how good your overall product is, based on my experience with monetize.js. But maybe that's just me!

**Comment by benweet** [comment]
Yes, I've seen your message this morning. I checked with Stripe, it looks like they attempted to charge you 4 times which is excessive. Sorry about that. I think the subscription was cancelled at the beginning of the second year, that's why it was still trying to charge you for another year.
I'll try to check with MonetizeJS to fix the issue. Sorry again.
