### ISSUE TITLE
Rendering causes headache inducing jumping that makes stackedit unusable

### ISSUE THREAD

**Issue by yaronyg** [benweet/stackedit#900]
I'm working on a document in stackedit.io and as I type the entire window both the original and preview text jumps up and down. I tried to move the window to a position that was both higher and lower but it didn't work. The window would jump back to the same point and start jumping up and down every time I typed anything. The behavior is so bad it has rendered stackedit unusable with preview.

I turned off preview and it fixed nothing! The screen still jumps!

What's odd is that the problem only appears to happen at the end of the document. You can see the document [here](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/presenceprotocolBindings.md). If I edit near the top or middle of the document there is no problem. But if I start editing around [here](https://github.com/thaliproject/thali/blob/yaronyg-patch-4/presenceprotocolBindings.md#local-wi-fi-binding) then the jumping starts. Specifically around the sentence "When a Thali application is in the foreground and connected to a Wi-Fi network it MUST issue a ssdp:alive request as defined below every 500 ms."

Note that the document has a big section at the end filled with the word "junk" this is there because it makes the bug go away. So if you want to repro you need to delete that section.

**Comment by barisdemiroz** [comment]
Having the same problem here. If the document you are writing gets long and contains math it seems that it is rendering the editor and view from scratch. And it starts jumping up and down every time you type a letter.

**Comment by yaronyg** [comment]
And just for fun I just replicated this again right now. Please, fix?

**Comment by BigBlueHat** [comment]
:cry: yeah...just found this one too. Guess I hadn't written long enough stuff when I first tarted using it. :grin: 

@yaronyg @barisdemiroz what browsers are you using? I'm in Firefox 41.0.2 at the moment.

**Comment by barisdemiroz** [comment]
@BigBlueHat I was using latest beta Chrome back then and Firefox too (I don't remember the exact version but the very recent one in Windows).

**Comment by BigBlueHat** [comment]
@barisdemiroz I just tried it in Chrome 48 and it seems to not be jumping about at the moment.

I was also have weird "race condition" scenarios if I used the "link" button and started typing before it opened--I'd replace the highlighted item rather than type in the URL field... If I was patient...it'd work. :wink:

It feels a bit like the cursor is jumping to the top of the text area on each character typed.

I can't prove that at the moment--'cuase I"m busy writing an article in StackEdit :wink: but it's something to dig into maybe.

**Comment by yaronyg** [comment]
@BigBlueHat I'm always using whatever the latest. It got so bad for me that I eventually had to stop using StackEdit all together and instead switched to using IntelliJ with MD support. Even my trick of shoving a bunch of text at the end had stopped working. I just repro'd it on a fairly small document (see [here](https://gist.github.com/yaronyg/9ff7a619958691504698)) in FireFox 44.0.2.

**Comment by barisdemiroz** [comment]
@BigBlueHat You are right! It doesn't jump around crazily in Chrome 49.0.2623.75 beta-m. Thanks for bringing this up, I can continue writing long texts with lots of math in StackEdit. What a great tool this is.

**Comment by benweet** [comment]
Latest version should be fine.
