### ISSUE TITLE
HTML to MD bug: list won't render with text before it

### ISSUE THREAD

**Issue by Daniel-Hug** [benweet/stackedit#911]
Try converting the following HTML to Markdown using the stackedit app. The list won't render as a list because the converter doesn't put a new line between the intro text and list.

``` html
Some text before list
<ul>
<li>list item</li>
</ul>
```

Markdown output:

``` md
Some text before list
*   list item
```

**Comment by benweet** [comment]
Sorry, this feature is not supported anymore.
