### ISSUE TITLE
HTML to MD bug: spaces inside inline formatting elements (em, strong, etc.) should be put outside

### ISSUE THREAD

**Issue by Daniel-Hug** [benweet/stackedit#912]
The italics are not rendered in the Markdown below because of a bug in the HTML to Markdown converter:

``` HTML
<p>text with<em> italics</em></p>
```

Markdown output:

``` md
text with_ italics_
```

What the Markdown output should be:

``` md
text with _italics_
```

**Comment by benweet** [comment]
Sorry, this feature is not supported anymore.
