### ISSUE TITLE
Missing the last column in ASCII table

### ISSUE THREAD

**Issue by yamire** [benweet/stackedit#914]
```
|   |   |   |
|---|---|---|
| 0 | 1 | 2 |
```

The column 2 is missing,  appears after having some content in the 0th column.

```
|a  |   |   |
|---|---|---|
| 0 | 1 | 2 |
```

**Comment by shark-oxi** [comment]
A proper array look like [this](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables)
```markdown
Colons can be used to align columns.

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

There must be at least 3 dashes separating each header cell.
The outer pipes (|) are optional, and you don't need to make the 
raw Markdown line up prettily. You can also use inline Markdown.

Markdown | Less | Pretty
--- | --- | ---
*Still* | `renders` | **nicely**
1 | 2 | 3
```
you can't have empty header title and it's better to left space between dashes and pipes.

So this will work : 
```
| a | b | c |
| --- | --- | --- |
| a | b | c |
```
This is not a bug this is only you not writing godd markdown, here is official doc : https://daringfireball.net/projects/markdown/syntax

**Comment by shark-oxi** [comment]
PS : table are not pure markdown but a GMF feature

**Comment by noraj1337** [comment]
@benweet closing without any comment?

**Comment by benweet** [comment]
Yeah I liked your last one.

**Comment by benweet** [comment]
@noraj1337 thanks for your help by the way.
