### ISSUE TITLE
Left side scroll bar overlay over the setting modal

### ISSUE THREAD

**Issue by kuzyn** [benweet/stackedit#918]
Could reproduce it a few time, but it seems to be a weird timing thing.

Chrome 46.0.2490.80
OSX 10.10.5

![capture d ecran 2015-12-02 a 17 02 28](https://cloud.githubusercontent.com/assets/1139068/11545752/063bc94e-9917-11e5-8fac-597e6aff9f86.png)

**Comment by benweet** [comment]
Should be fine now.
