### ISSUE TITLE
Custom keyboard shortcuts

### ISSUE THREAD

**Issue by ghuba** [benweet/stackedit#92]
Hi,

Is there a way to create new keyboard shortcuts to insert snippets of text? This would be useful for the equation editor. Can the "UserCustom extension" be used for that? Thanks for the help.

**Comment by victorel-petrovich** [comment]
Looks like all above extensions make use of Ace component. But I understood that now is removed? Will then they still work, or what's the workaround?...

**Comment by victorel-petrovich** [comment]
@ghuba  , @benweet , @jbaum98 

How about an extension that provides a list (of recently used) matching latex commands, when when user starts typing a particular latex command. Ex: $\left...$ (then a popup appears and suggests \leftarror, \leftbracket etc). Then user can navigate with arrow down and select by enter or space.

I think this could not only help beginners, but speed the work of advanced users too.

**Comment by vladejs** [comment]
The shortcuts above aren't working on StackEdit 4.0
