### ISSUE TITLE
Feature request: add a table formatter plugin

### ISSUE THREAD

**Issue by rbondi** [benweet/stackedit#920]
Like https://github.com/wooorm/markdown-table (just an example).

This would format a selected Markdown table to make it look nice in ASCII.

Thanks, /rb

**Comment by jadedevin13** [comment]
+1

**Comment by benweet** [comment]
Fixed in the v5.

**Comment by rbondi** [comment]
Awesome! You and stackedit rock!!!
Thank you, |r:b:

**Comment by rbondi** [comment]
Hi Ben,

I can't figure out how to trigger the table formatting in the version 5 beta, v5.4.1: how do I format a table?

Thanks, |r:b:
