### ISSUE TITLE
Bug: trailing pound symbols in headers not displayed

### ISSUE THREAD

**Issue by lilred** [benweet/stackedit#921]
Just put this in a new file:

```
#A#
```

It shows a big A. Should show A#.

**Comment by notpeter** [comment]
I don't know what which markdown spec stackedit follows, but in most, trailing hash symbols (of any quantity) following headers are allowed.
http://spec.commonmark.org/0.22/#example-36

If you need a literal trailing hash just use a backslash:
````markdown
#A\#
````

**Comment by MidnightLightning** [comment]
And by "are allowed", you mean "is part of the markup that defines that row as a headline". Just clarifying why that hash isn't shown; it's being interpreted as part of the way a headline is delimited (i.e. this isn't a bug).
