### ISSUE TITLE
Code block can show line number when being converted to an HTML

### ISSUE THREAD

**Issue by hawkhero** [benweet/stackedit#922]
Line number in a code block is very useful when writers explain the code. A writer usually needs to mention a specific line to explain it in detail.

I know now we can add javascript code in the default template to achieve a similar effect. But this will require loading extra javascript files like run prettify.js in the target blogger which slows down the loading. So a static HTML page converted by stackedit is better than adding line number with javascript in the target blogger.

**Comment by hawkhero** [comment]
Found the solution by myself, refer to http://michelf.ca/projects/php-markdown/extra/#spe-attr
To add line number on a code block
1. select setting / extension / markdown extra / syntax highlighter / prettify
2. add css class `linenums` with special attribute
So the markdown syntax is:
<pre>
```java {.linenums}
public class Myclass{
private int a;
private int b;
protected String str;
public void method(){
}
```
</pre>

then the line number will appear on a code block. Thanks for stackedit.

**Comment by riezebosch** [comment]
For me it only add a number to the last line of the code block.
