### ISSUE TITLE
Code syntax highlighting not working

### ISSUE THREAD

**Issue by simon-zhu** [benweet/stackedit#924]
Code syntax highlighting is not working for me. I have chosen Prettify as the syntax highlighter, and I have enabled GFM Fenced code blocks as well. Do I need to install anything in my browser?

**Comment by MidnightLightning** [comment]
What is the markdown source you're inputting that doesn't highlight properly?

**Comment by benweet** [comment]
Please provide a markdown sample to reproduce the issue.
