### ISSUE TITLE
Please provide additional app for view markdown files in google drive.

### ISSUE THREAD

**Issue by vskubriev** [benweet/stackedit#926]
**FEATURE REQUEST.**

Be right mouse click in drive.google.com you can select application which should open(edit) a file. 

I successfully installed stackedit and use it for md files editing to test it workflow.

Stackedit has two modes (edit and preview).

It would be convenient if you split stackedit in two apps: editor and viewer. Or write a new one tool for preview.

Then it would be possible to view existing documents rather then edit them.

Editing is not always necessary. And there is no existing extensions for preview markdown directly from google drive "open with" file context menu.

Our use case is to use shared with all developers google drive folder for wiki in markdown format. Therefore we need preview app, when we use wiki as online document. I hope you understand me.

Another possible solution is to publish all google drive folder with a wiki (name wiki) to some sort of web hosting engine. I know that application already supported some online platforms. But all of them cannot provide our required publishing level. This level supposes syncing a folder rather than one document. 

But without fastest preview, we cannot migrate to it. We are not registered stackedit users still. If we decide to use it - we'll make a donation to project.

Anyway thank you for developing stackedit.

**Comment by RoyiAvital** [comment]
I'm not sure this project is still alive.

This is a shame as a I'm a paying customer and I thought at some point Real Time Collaboration will be added.

**Comment by vskubriev** [comment]
@RoyiAvital Thank you for additional info about project. We not sure in this project now.

**Comment by benweet** [comment]
Sorry, this doesn't look like a feature request.
