### ISSUE TITLE
Connect stackedit in Google Drive to other text file types like *.tex

### ISSUE THREAD

**Issue by phaase** [benweet/stackedit#928]
Stackedit would be great for offline editing of (la)tex files stored in Google Drive. However, open a *.tex file with stackedit is not possible before renaming the file to a *.txt file. 

I'm not really in programming of chrome web apps but I assume modifying the Google Drive mime type list in manifest file (as explained here: https://developers.google.com/drive/v2/web/listing) should be an easy solution.

**Comment by benweet** [comment]
Closing this. StackEdit being a Markdown editor, why would it open some other formats, and why Tex more than another ?
