### ISSUE TITLE
Can't publish to WordPress site (URL validation)

### ISSUE THREAD

**Issue by khatchad** [benweet/stackedit#931]
My self-hosted wordpress site is http://openlab.citytech.cuny.edu/khatchad. However, I can't get passed the validation portion of the site name. The '/khatchad' seems to be the problem, but this is the address of my site.

Related to https://github.com/benweet/stackedit/issues/12 and https://github.com/benweet/stackedit/issues/718.

**Comment by barichan35** [comment]
I having this problem too.
We need remove validation of '/' charactor.

**Comment by benweet** [comment]
The site has to on wordpress.com I'm afraid. Have you tried the Jetpack plugin?
