### ISSUE TITLE
published post looks different in blogspot

### ISSUE THREAD

**Issue by sterding** [benweet/stackedit#932]
hi, 

I found the stackedit is very useful and helpful. Thanks.

I have a question: why the post published to blogspot.com looks different from what I see on the right ride in stackedit.io? 

Below is what I just posted:
http://onetipperday.blogspot.com/2016/01/calculate-odd-of-winning-powerball-in-r.html

As you can see, I lost code syntax highlight, font etc.. 

Thanks,
-Xianjun

**Comment by benweet** [comment]
You should customize your blog template with some css.
