### ISSUE TITLE
StackEdit goes into offline mode when trying to save to Dropbox

### ISSUE THREAD

**Issue by ScottWNesbitt** [benweet/stackedit#933]
After writing a draft of a document in StackEdit 4.3.12 on my Chromebook, I tried to synchronize it with Dropbox by selecting **# > Synchronize > Save on Dropbox**. I typed the path to the folder on Dropbox where I wanted to save the document but when I clicked OK, a messaging saying **You are offline** displays. 

My Chromebook is still connected to the internet (I can access other sites in other tabs). This only happens with Dropbox. I can save and sync with Google Drive.

**Comment by matthiasmeier** [comment]
Same issue here. Thought I move to Dropbox after the sync issues that StackEdit has in the last time with Google Drive. But this seems to be even worse (read: not work at all).

Any update on this?

**Comment by kevinwkc** [comment]
same issue here, "You are offline" , but I can go to internet

**Comment by matteobrusa** [comment]
Same here. 
"open from Dropbox" returns a 404 error.

**Comment by neumaneuma** [comment]
I'm also getting the same error with both Dropbox and Google Drive sync

**Comment by benweet** [comment]
Please open a new ticket if not fixed in the v5.
