### ISSUE TITLE
Sync with Disk

### ISSUE THREAD

**Issue by lagerenas** [benweet/stackedit#934]
When I open a markdown file from disk it would be nice to be able to save it back to the same location with one click. Currently I have to export it and then move the file to the original location.

**Comment by dimbula2000** [comment]
+10
Enabling select location when exporting to disk is very handy.

**Comment by g33kdad** [comment]
Having this feature would enable me to save my docs to a local sync folder (syncthing, nextcloud, etc)

**Comment by benweet** [comment]
Sorry that's not feasible within a browser.
