### ISSUE TITLE
Error in Chrome: Mismatched anonymous define() module

### ISSUE THREAD

**Issue by Schweinepriester** [benweet/stackedit#936]
```
Uncaught Error: Mismatched anonymous define() module: function (){return $}
http://requirejs.org/docs/errors.html#mismatch
```

![image](https://cloud.githubusercontent.com/assets/2644614/12392751/9cdb51c2-bdf1-11e5-8c2f-cd1e0edc7422.png)

Chrome

> Version 47.0.2526.111 m

Tried flushing cookies and localStorage.

Works fine in Firefox.

**Comment by ekae** [comment]
I'm also have this problem
Chrome Linux
>47.0.2526.111 (64-bit)

**Comment by Schweinepriester** [comment]
@benweet please help/fix? :)

**Comment by benweet** [comment]
@Schweinepriester can you try with an incognito window?

**Comment by Schweinepriester** [comment]
Yes:

![image](https://cloud.githubusercontent.com/assets/2644614/12536843/3b17c4ce-c2b1-11e5-85fc-744c82c0d2a9.png)

If I can be of further help, just let me know.

**Comment by benweet** [comment]
Can you try to clean the application cache in chrome://appcache-internals/

**Comment by Schweinepriester** [comment]
No change, sadly.

Just in case, the stack trace points to line 28297 in main.js, the one with "rangy-cssclassapplier".

```
  isEditable: m
 }, e.CssClassApplier = C, e.createCssClassApplier = _;
}), define("rangy-cssclassapplier", function() {}), requirejs.config({
 waitSeconds: 0,
```

**Comment by benweet** [comment]
Your logs shows that the new version of https://stackedit.io/res-min/main.js is not being downloaded. That would be the issue. The file is available though.

Must be a cache problem. Try to uncheck `Disable cache` or maybe wipe your cache fully (you can try "Cookies and site data" in the settings).

**Comment by Schweinepriester** [comment]
While i tried fiddling with the cache in chrome (unchecked `Disable cache`, hard reload, open the file directly), i then moved to firefox, flushed everything i could find and compared both main.js from chrome and FF => exact same file…

**Comment by Schweinepriester** [comment]
Just in case anybobdy stumbles upon this: <http://requirejs.org/docs/errors.html#mismatch>

**Comment by benweet** [comment]
Well, I can't reproduce the problem with same version of Chrome. May be an issue with one of your Chrome extensions.

**Comment by Schweinepriester** [comment]
Technically its now

> 48.0.2564.82 m

but yeah, you're probably right.

Tried chrome without any plugins in a VM, works.

@ekae do you have extensions installed in chrome? if yes, which?

**Comment by ekae** [comment]
Just come back to testing today. I'm did not do anything from @benweet  advices but I'm uncheck the "Prefetch resources to load pages more quickly" and hard reload the page seem to fix the problem

**Comment by ekae** [comment]
After several page reloaded, Its happen again so I disable extension one-by-one and found that [EXIF Viewer](https://chrome.google.com/webstore/detail/exif-viewer/mmbhfeiddhndihdjeganjggkmjapkffm) is the problem

**Comment by Schweinepriester** [comment]
Which i have installed, too.
Can confirm that it works without EXIF Viewer.

After some searching: <https://code.google.com/p/exif-vewer-extension/>, we could open an issue there, but first i'd like to try to summon him directly.

@andry-virvich: It appears EXIF Viewer (really awesome btw.) conflicts with stackedit, can you look at this issue, please? :)

**Comment by andry-virvich** [comment]
hey @Schweinepriester sorry I no longer work on that extension, try to contact current owner

**Comment by Schweinepriester** [comment]
Thanks for the reply @andry-virvich. Who is the current owner? Do you have any information for us?

<https://chrome.google.com/webstore/detail/exif-viewer/mmbhfeiddhndihdjeganjggkmjapkffm> states 'Aruna', but there is no way to contact him? A longer search didnt yield anything. Should we write a review as issue, possibly linking here? ...?

Slighty related, stackedit is not the only thing conflicting, e.g. <https://github.com/jupyter/notebook/issues/1302> or see the reviews (PDF, paypal, mailbox.org, …).

**Comment by andry-virvich** [comment]
@Schweinepriester try to contact this guy: vdsowner at gmail.com

**Comment by Schweinepriester** [comment]
Thanks @andry-virvich, i have sent a mail.

```
Hi,

please have a look at https://github.com/benweet/stackedit/issues/936.

In short: Sadly it appears the EXIF Viewer plugin for Chrome now breaks things, e.g. https://stackedit.io or the integrated PDF viewer in chrome.

A fix would really be appreciated, as EXIF Viewer is a great tool and would be missed.

Thanks, greetings,

Kai
```

**Comment by Schweinepriester** [comment]
FYI:
He responded on 2016-05-11, i just answered his mail.
I asked for permission to post his mail(s) here.

@benweet I hope its okay for you that we somewhat hijack this issue on your project for trying to solve this issue of EXIF Viewer openly, although it only relates to stackedit? :)

**Comment by drveresh** [comment]
I just verified that Exif Viewer's latest updates addresses some of these issues and it is no longer causing/blocking any aspects of some of those websites.  It seems the root cause was with Google Fonts while loading them.

**Comment by Schweinepriester** [comment]
Can confirm stackedit works again with EXIF Viewer (had it disabled in the meantime), therefore closing this issue.
