### ISSUE TITLE
How do I log out?

### ISSUE THREAD

**Issue by nizamsp** [benweet/stackedit#938]
I don't see any way to logout of stackedit.io
I want to see the sample editor you show up for new user. It has all the syntax I want.
If I am logged in, I couldn't see that default editor.
To logout, I don't see a legible button anywhere :(

**Comment by hoto** [comment]
menu (on the left side) => synchronization => remove synchronization
thats obvious, isn't it? ;)

**Comment by hoto** [comment]
then you can remove documents (on the right side), because they are stored in the localStorage

**Comment by hoto** [comment]
but you cannot synchronize again, looks like a bug to me
to synchro again (with different account) clear localStorage and sessionStorage

* Open console in chrome (F12)
* in console paste

    localStorage.clear(); 
    sessionStorage.clear();

**Comment by hoto** [comment]
anyway love the product, great job guys, thanks
I love my notes now, they look so clean and professional when i print them
