### ISSUE TITLE
can't c-c c-v or copy/past in edit mode ?

### ISSUE THREAD

**Issue by fanicy** [benweet/stackedit#939]
firefox 43,can't c-c c-v or copy/past in edit mode,and can't use any hotkeys in windows.
Only insert something in type?

**Comment by fanicy** [comment]
test again,
when i past a paragraph  in code  format,like:
@echo off
@echo test
@echo test3

There is only first line add to the code area.

**Comment by benweet** [comment]
Please try again with the v5 and open a new ticket if it's not fixed.
