### ISSUE TITLE
No automatic update in ordered list in the editor

### ISSUE THREAD

**Issue by plumSemPy** [benweet/stackedit#941]
If we start an ordered list, say 1. Foo 2. Bar, and then add another item in between say: 1. Foo 2. Baz 3. Bar, then in the editor we will have : 1. Foo 2.Baz 2.Bar while in the preview 1. Foo 2. Baz 3.Bar.  The automatic update does not function for the editor.

![github stackedit](https://cloud.githubusercontent.com/assets/8195422/12780917/cbabdb94-ca25-11e5-945b-d643c29ae219.png)

**Comment by benweet** [comment]
Fixed in the v5.
