### ISSUE TITLE
LaTex expressions all end | when rendered

### ISSUE THREAD

**Issue by nmcr01** [benweet/stackedit#942]
Problem started about 1 week ago.

**Comment by pkra** [comment]
I'm guessing this is due to https://github.com/mathjax/MathJax/issues/1300 which has been fixed in MathJax v2.6.

**Comment by edwinksl** [comment]
MathJax 2.6 has been officially released for a while now. Seems like it is time to upgrade to 2.6.

**Comment by nmcr01** [comment]
Expressions identified by $$...$$ now free from |, but inline expressions identified by $ ...$ not being rendered at all

**Comment by dayanl** [comment]
I have been experienced the same problem for a while. $$...$$ also has the | at the end.

**Comment by pkra** [comment]
You can manually switch to MathJax's SVG output via the MathJax context menu to work around this issue (which only affects the HTML-CSS output).
