### ISSUE TITLE
Unnecessary permission for Github/Dropbox/Drive?

### ISSUE THREAD

**Issue by sahilshekhawat** [benweet/stackedit#945]
I was wondering why do we need permission to access all files on Dropbox/Drive/Github by default? And if we do need that, we can give users an option to reduce those permissions for those who love this product but don't want to give access to all files.

**Comment by naarkhoo** [comment]
I noticed stackedit ask for the permission to the whole dropbox instead of the selected folder.

**Comment by benweet** [comment]
Fixed in the v5.
