### ISSUE TITLE
Can't gulp properly!

### ISSUE THREAD

**Issue by lovebdsobuj** [benweet/stackedit#947]
I following installation command line clearly 
but after `gulp` command I got long error screen.

Can you tell me whats wrong here...?

> https://gist.github.com/lovebdsobuj/0db5b3ea6ba354c6aec4

**Comment by ludberg** [comment]
Same for me

**Comment by kainecy** [comment]
Same for me

**Comment by infinite2009** [comment]
Same for me

**Comment by tomleo** [comment]
Same for me

**Comment by youngluo** [comment]
Same for me

**Comment by benweet** [comment]
Should be fixed in the v5.
