### ISSUE TITLE
Bullet list item deleted

### ISSUE THREAD

**Issue by TomAuger** [benweet/stackedit#948]
I have seen this 20+ times, but not sure I can reproduce it every time:

Open a doc that already has a bulleted list in it
Place cursor at the end of a bulleted list item
Press Enter (to drop down a line and start a new bullet)

Result: The line you're on is completely deleted.

Note: The line is NOT highlighted / selected.

**Comment by benweet** [comment]
Should be fixed in the v5. If not, please open a new ticket.

**Comment by TomAuger** [comment]
Sweet. Keep up the great work. Looking forward to V5
