### ISSUE TITLE
Ad-hoc enable styles for Highlight.js in a StackEdit document?

### ISSUE THREAD

**Issue by benjamin-rood** [benweet/stackedit#949]
I'm trying to do a `<pre>` block that uses one of the styles ad-hoc. Is that possible, or do I have to create my own SE theme and import it?

p.s. I absolutely love SE and am very happy to be contributing with the yearly US$5 donation for a long time to come

**Comment by benweet** [comment]
Highlight.js is not supported anymore in the v5, I'm afraid.
