### ISSUE TITLE
Save to Cloudant is broken / throws error

### ISSUE THREAD

**Issue by BigBlueHat** [benweet/stackedit#951]
I'm attempting to use StackEdit with Cloudant, and have tried both a publicly writable and a private (API key/secret) database, but I get this same error regardless.

> Error 0: [Exception... "<no message>" nsresult: "0x805e0006 (<unknown>)" location: "JS frame :: https://stackedit.io/res-min/main.js :: .send :: line 2480" data: no]

I'm hoping to get this setup, so I can keep my various browsers on various machines in sync...because CouchDB. :smile_cat: 

Thanks!
:tophat:

**Comment by benweet** [comment]
I think the CouchDB of Cloudant is somehow not standard or too old.

**Comment by BigBlueHat** [comment]
@benweet hmm...I'm digging into the code now. The Cloudant code is based on CouchDB 1.0.2, but it also includes some "up ported" changes.

@willholley any thoughts?

**Comment by BigBlueHat** [comment]
@benweet it looks like `couchdbUrl` is just being passed straight on to jQuery's `ajax()` rather than being parsed for username / password pairs.

It's been years since I've used jQuery, so I've no idea if that's required, but that's where I'd start looking...

Cloudant does fully support HTTP Basic Authentication (as CouchDB always has), so that shouldn't be the issue.

**Comment by willholley** [comment]
Google suggests `0x805e0006` could be CORS related. Have you configured CORS in your Cloudant account?

**Comment by BigBlueHat** [comment]
Yep. Using the Cloudant Dashboard.



On Mon, Feb 29, 2016 at 8:51 AM -0800, "Will Holley" <notifications@github.com<mailto:notifications@github.com>> wrote:


Google suggests 0x805e0006 could be CORS related. Have you configured CORS in your Cloudant account?

-

**Comment by willholley** [comment]
ah - Cloudant doesn't support `POST` to `_changes` or `_doc_ids` filter yet. This will work when the CouchDB 2.0 builds land (currently blocked on CORS issues with CouchDB 2.0 but we're getting close).

**Comment by BigBlueHat** [comment]
Hrm. @benweet guessing this is done to avoid long URL situations caused by a long list of `syncLocations`?

Seems this is where it happens:
https://github.com/benweet/stackedit/blob/a5ed5bf644987b05ca54e9a9f8122d12f74c330e/public/res/providers/couchdbProvider.js#L166-L174

Wonder if `syncLocations` could be limited in scope? or just not sent and filtered locally?

Given that most folks are going to only have StackEdit editing this DB, then I'd think the "risk" of massive change set having to be filtered locally would be fairly low.

Seem reasonable? :stuck_out_tongue_winking_eye:

**Comment by benweet** [comment]
Support for CouchDB has been removed in the v5. It may come back but in a different way.
