### ISSUE TITLE
Fix gulp-inject entry protocol in package.json

### ISSUE THREAD

**Issue by tlperkins** [benweet/stackedit#953]
"gulp-inject": "git://github.com/benweet/gulp-inject.git#8bd702d143a578e3b44290d82612ab808ee17281"

to 

"gulp-inject": "git+https://github.com/benweet/gulp-inject.git#8bd702d143a578e3b44290d82612ab808ee17281"

**Comment by benweet** [comment]
Should be fixed in the v5.
