### ISSUE TITLE
Plugin support for custom sections:  ```<name> ... ``` (more of a feature resquest than an issue)

### ISSUE THREAD

**Issue by Aurel74** [benweet/stackedit#954]
Kudos on an excellent app!  I was building a very similar app because I needed the functionality and found this.  Awesome.  I was doing the same thing with adding sequence diagrams and flow charting.  I was also working on class diagrams.  What I didn't do yet, was tracking between the editor and rendering windows!  Nice.

Any chance of adding an interface to allow user defined ```<name> sections, maybe as plugins?

I'd like to make three section types:  encrypted, class diagram and foldable

Or maybe you have plans for these?

**Comment by benweet** [comment]
This won't be possible unless you fork the project.
