### ISSUE TITLE
apostrophes and export to disk as html

### ISSUE THREAD

**Issue by blitz-research** [benweet/stackedit#966]
Hi,

When I export to disk as html, apostrophes are converted to a weird sequence of chars, eg:

<pre>
Modules and applications 
Namespaces and â€˜Usingâ€™ 
Operator overloading 
The build system and â€˜Importâ€™ 
Native code and â€˜Externâ€™ 
The mx2cc tool
</pre>

I tried disabling the html sanitizer but that didn't work.

It's fine if I export to disk using template though, so I can work around it for now.

Bye,
Mark

**Comment by Doron-Behar** [comment]
Try using `Export Using Template` instead

**Comment by almereyda** [comment]
It's a pity the aforementionned is not self-contained and loads third party JS + CSS.

**Comment by benweet** [comment]
I guess you can create your own template for that.
