### ISSUE TITLE
Allow text formatting by text selection in the preview/WYSIWYG pane

### ISSUE THREAD

**Issue by hi2u** [benweet/stackedit#967]
Currently we can select text in the source code editor pane (on the left) and click the formatting icons on the toolbar to modify that text selection.

But the same cannot be done by selecting text in the preview/WYSIWYG pane (on the right).  

It would be awesome if it could be done in both panes.

Ideally you would always be able to format selected text in both panes at all times.  i.e. Rather than there being a setting to only use one or the other.

Additionally to this, it would be amazing if we could both **type** and **format** in both panes.  But just formatting would be a great start.

All of the above, with a button to hide either of the panes would make stackedit suitable for every scenario/site/technical-ability-level imaginable:
- Programmers like us can continue to use it as is
- Some technical people might not feel they even need the preview pane
- Non-technical people can ignore the source code editor pane, or hide it
- People in the middle can swap back and forth in how they use it

**Comment by benweet** [comment]
I'm afraid it will be difficult to add editing capabilities without an actual editor. Though in the v5 you can now create discussions and add comments with both the editor and the preview pane.
