### ISSUE TITLE
PDF generated cannot be opened

### ISSUE THREAD

**Issue by handytan** [benweet/stackedit#968]
Hi I've sponsored StackEdit to enable the Export to PDF function. However, the PDF generated a "Failed to load PDF document" error when opened in Chrome. 

What's the issue?

**Comment by hailg** [comment]
Anything about this issue? I have it also. Please!

**Comment by benweet** [comment]
Please open a new ticket if the problem still exists in the v5 and share a markdown sample to reproduce it.
