### ISSUE TITLE
GitHub Authorization Page (Small, Can't scroll to authorize button)

### ISSUE THREAD

**Issue by jakirkham** [benweet/stackedit#969]
When trying to do GitHub authorization after selecting export, it brought up a small authorize window. It also had no scroll bar and refused to scroll via other means. I was able to work around this by zooming out and clicking the authorize button. Would be nice to fix this as it make it hard to try, though everything else seems pretty nice so far.

**Comment by benweet** [comment]
Should be fixed in the v5.
