### ISSUE TITLE
'Find and Replace' Functions

### ISSUE THREAD

**Issue by TonyJB** [benweet/stackedit#970]
**Me:** I'm a copywriter with limited experience of GitHub and StackEdit.

**My issue:** StackEdit's _Find and replace_ seems, to me, very basic and I'm having trouble with it. For example: replacing single asterisks with X but not replacing double asterisks (which would result in XX). My job involves adding HTML and editing work from many non-HTML-fluent  writers, so find and replace is a big thing for me.

Is there functions I can use when finding and replacing, much in the same way that using quotation marks in Google forces the search term? I miss MS Word & Excels advanced find and replace, but copy and pasting back and forth adds up to too much time wasted. 

**So, is there anything I can do to improve the utility StackEdits 'find and replace' feature?**

**Comment by benweet** [comment]
You could use regular expressions for that.
