### ISSUE TITLE
Support for Onedrive

### ISSUE THREAD

**Issue by levythu** [benweet/stackedit#971]
There're supports for Google Drive and Dropbox for synchronization but Microsoft OneDrive seems to be omitted. 
Since OneDrive is already a built-in in Windows 10, the number of users will increase. And there's every reason to add support for it.

**Comment by RoyiAvital** [comment]
That would be great.

Though I think the project is dead now.

**Comment by lilred** [comment]
@benweet close as duplicate? (#211)

**Comment by benweet** [comment]
Right.
