### ISSUE TITLE
Hide elements in an accessible fashion

### ISSUE THREAD

**Issue by parhamdoustdar** [benweet/stackedit#972]
A lot of icons (like the menu, the preview, and so on) are hidden and shown based on what the user clicks on. However, this is not reflected to screen reader users.

Here are two things that can be done:
- Set the `display` attribute to `none` in CSS to hide elements, or
- Set the `aria-hidden` attribute on HTML elements that are hidden to `true`.

I would really appreciate it if you could pick the easier solution and fix it, as StackEdit is almost 100% accessible to me as a screen reader user, and that's a huge deal.

Thanks.

**Comment by benweet** [comment]
Hi, can you try with the v5 and open a new bug if it's not fixed?
