### ISSUE TITLE
Can I add pics from local?

### ISSUE THREAD

**Issue by choushishi** [benweet/stackedit#975]
Greetings.

I am trying to add a picture to my notes but I do not see to option to choose the picture locally. I wonder if it is true that we can only add picture with a url?

If it is the case, I think it is reasonable if you can allow us to add picture locally because after all, the file are stored locally and they don't take up your server resources. :D

**Comment by shark-oxi** [comment]
Your question is a markdown question not a stackedit one.

Here is how you can add pictures : 
```markdown
Inline-style: 
![alt text](https://url "Logo")

Reference-style: 
![alt text][logo]

[logo]: https://url "Logo"

Local file (same folder as markdown) :
![alt text](file.png)

Local file (other folder as markdown) :
![alt text](oterfolder/file.png)
```

You can even change url and put a base64 string image.
