### ISSUE TITLE
Standalone editor/viewer module

### ISSUE THREAD

**Issue by cadavre** [benweet/stackedit#977]
Stackedit as stackedit.io is a great tool. It's also awesome you open-sourced this solution as it is, but it doesn't give any integration possibilities as editor/viewer that can be implemented.

Currently I'm developing another open-source project where I'd love to use editor and viewer from Stackedit – markdown based with GitHub flavors and extensions. The problem is Stackedit is a huuuge ship that is difficult to maintain and not even mentioning about keeping it on track with git.

Is it possible to create minified version that can be loaded into any `<div class="stackedit">` and having external basic API like `loadDocument()` and `getDocument()`? Without node server etc.

**Comment by cadavre** [comment]
Just to add: no need of local storage, synchronization, publish modules, extremely customizable settings and extensions...

**Comment by leotiger** [comment]
With some effort it's possible:

<img width="1868" alt="screen shot 2017-01-02 at 22 31 21" src="https://cloud.githubusercontent.com/assets/137951/21596424/5275c7bc-d13b-11e6-85da-8a936055f860.png">

That's my StackEdit implementation for [GRAV](https://getgrav.org/). Still not production ready, but probably I will release a spin-off these days.

Regards.
uh

**Comment by exnihilo-creatio** [comment]
@leotiger Did you ever release the spin-off? Or have the files stored somewhere? I'm also interested in a standalone version.

**Comment by leotiger** [comment]
@exnihilo-creatio. No I haven't. I'm and I was busy with other things. I will see if I can offer this as a component, but it will take some weeks as I haven't been working with GRAV for some time.

**Comment by benweet** [comment]
You can now use https://github.com/benweet/stackedit.js.

**Comment by leotiger** [comment]
Great, thanks!

**Comment by drzraf** [comment]
@leotiger did you succeeded in getting Grav admin's textarea nicely integrated with stackedit.js?

**Comment by slikts** [comment]
`stackedit.js` is essentially just an `iframe` and has a reduced user experience due to [network delay](https://github.com/benweet/stackedit.js/issues/31). A proper standalone version that could be embedded locally would still be appreciated.
