### ISSUE TITLE
Embedded fonts in PDF look a little ugly

### ISSUE THREAD

**Issue by chaosink** [benweet/stackedit#978]
May I customize the fonts in PDF?

**Comment by mlopezgva** [comment]
Looking for another "hack", I found a gist that may help you.
https://gist.github.com/mrpatiwi/091f6cb4d41165c431a1

**Comment by betweenthieves** [comment]
I believe it is the kerning that makes the font look so bad in exported PDFs. See issue #902 .

**Comment by benweet** [comment]
That would be an issue with wkhtmltopdf.
