### ISSUE TITLE
stackedit freeze when edit markdown under firefox

### ISSUE THREAD

**Issue by lvii** [benweet/stackedit#979]
Hello , 

From last month [stackedit.io/editor](https://stackedit.io/editor) always **freeze** when I edit markdown file under firefox.
I have tried to edit markdown files in firefox under Fedora and Mac OS X. 
When I load stackedit page, there is alway puping up a note about `main.js` file unresponsive message.

![Imgur](http://i.imgur.com/0MpfyZ1.png?1)

Please help to find this problem and solve it .

thanks very much.

**Comment by lvii** [comment]
When I use "```" for code block, page render will freezed for seconds.

**Comment by shark-oxi** [comment]
I also use Firefox and use "```" for code block and that never freeze for me.

**Comment by lvii** [comment]
@shark-oxi I use Firefox 46 under Fedora 24 x86_64.

**Comment by shark-oxi** [comment]
@Ivii i'm sorry I can't help you more, you should ask @benweet

**Comment by benweet** [comment]
Please try again with the v5 and open a new ticket if it's not fixed.
