### ISSUE TITLE
Publishing to Github

### ISSUE THREAD

**Issue by noraj1337** [benweet/stackedit#982]
Hi,

I installed and self-hosted stackedit on my VPS. When trying to publish on GitHub, it fails because after the authorization is given, the token receiving page is http://localhost/html/dropbox-oauth-receiver.html#access_token

I changed constants.js to 

```
 // Site dependent
        constants.BASE_URL = "http://localhost/";
        constants.GITHUB_CLIENT_ID = 'my_id';
```

and made a OAuth GitHub devel app setup to : 
- Homepage URL = http://MY_IP:3000/editor
- Authorization callback URL = http://MY_IP:3000/editor

And as you said : 

> As stated in https://github.com/benweet/stackedit/blob/master/doc/developer-guide.md:
> 
> ```
> OAuth authorizations work out of the box for address http://localhost/ except for WordPress. To allow another address, you have to add specific keys at the end of constants.js and eventually to set up specific proxies with the corresponding key/secret pairs.
> ```
> 
> It's supposed to work only with standard port 80.

But it don't work out-of-the-box for me.

**Comment by shark-oxi** [comment]
PS : I saw this [issue ](https://github.com/benweet/stackedit/issues/688 )and this [issue](https://github.com/benweet/stackedit/issues/589).

**Comment by benweet** [comment]
V4 should work out of the box on port 80 (http://localhost/).  
V5 should work out of the box on port 8080 (http://localhost:8080/).

You don't have to change anything like CLIENT_ID.
