### ISSUE TITLE
Highlight.js

### ISSUE THREAD

**Issue by noraj1337** [benweet/stackedit#983]
Hi,

1) On the [wiki ](https://github.com/benweet/stackedit/wiki/Templates#html-export-template-with-highlighting) it's said that wa can use custom css but on `Settings > Extensions > Markdown Extra > Syntax Highlighter` we can only choss between `none`, `petriffy` and `highlight.js`. So there is no way to use custon css.

2) Normally [highlight.js](https://highlightjs.org/static/demo/) support assembler code like _Intel x86 Assembly_ with the markdown tag `x86asm`. For example [dillinger.io](http://dillinger.io/) use highlight.js and this work but on stackedit.io it doesn't. So may be you use an old version wich doesn't support all 152 languages ?

3) [highlight.js](https://highlightjs.org/static/demo/) support 72 styles so it would be cool if you could add a features to allow user to switch of style.

**Comment by benweet** [comment]
Highlight.js is not supported anymore in the v5. [Prism](http://prismjs.com/) is.
