### ISSUE TITLE
[Feature Request(s)]: MediumProvider (decouple publishing?)

### ISSUE THREAD

**Issue by RobertDiebels** [benweet/stackedit#984]
Hi everyone,

So a week ago I started building a library with the sole intent of publishing Markdown to certain target websites/clients.
When today I was looking for some integration with Google Drive I stumbled across your editor.
I was happy to see that I wouldn't have to spend a great deal of time on something that already has been created.

However I have some questions or requests which I can (if thought of as a useful addition) build and integrate with your library.
1. I would like to publish my Markdown to Medium. They have recently opened an API [ https://github.com/Medium/medium-api-docs ] which excepts Markdown.
2. Would you consider decoupling the publishing mechanism and pushing it into a separate library? As I see much value in a headless publishing mechanism.

Like I said I've just encountered your library today. So I would like to know how to build a correctly functioning Provider. I've taken a quick glance at the developers guide, however I found little on building a provider.

Is there anything I should pay specific attention to when writing a provider?

Either way I'm excited about possibly contributing and using the library. 

Thanks in advance for any responses, Robert.

**Comment by benweet** [comment]
As for as I know the medium API only supports creating a blog post, but not updating a publication which is needed by StackEdit.
