### ISSUE TITLE
Hyphens

### ISSUE THREAD

**Issue by bibiphone** [benweet/stackedit#985]
Regarding paragraph justification, the use of the hyphen is sometimes necessary. Unfortunately css hypens function is not supported by Chrome. The Hyphenator script does allow the use of the hyphen. But is it possible to use a local script for example in UserCustom extension ? If so, what would be the syntax ? On the other hand , for the dash to be effective function is to determine the lang attribute of the html tag , but is it possible? (Translated from French by Google translator « ^^’ »)

**Comment by benweet** [comment]
What's that about? Please open a new ticket with a proper title and description. It should describe a feature request or a bug.
