### ISSUE TITLE
Suggestion: More top padding in editor

### ISSUE THREAD

**Issue by fgimian** [benweet/stackedit#988]
Hey guys, thanks so much for StackEdit.

One minor gripe I have with it is that the top line of my editor is just about touching the formatting bar:

![screen shot 2016-05-25 at 5 27 04 pm](https://cloud.githubusercontent.com/assets/1811813/15531488/ef364f42-229d-11e6-8429-119f94166ebc.png)

Would you consider adding some more top padding so that this looks a little nicer:

e.g. here's what 30px looks like

![screen shot 2016-05-25 at 5 26 12 pm](https://cloud.githubusercontent.com/assets/1811813/15531466/d3ed2904-229d-11e6-867e-c907ff7547ed.png)

Thanks!
Fotis

**Comment by benweet** [comment]
Fixed in the v5.
