### ISSUE TITLE
Footnotes keep last note's text

### ISSUE THREAD

**Issue by mlopezgva** [benweet/stackedit#992]
When writing more than 2 notes, all of them get the lastest text!

Also, I need to separate them with a blank line so they won't merge (in that case, ALL text is shown!)

This is what I get without blank lines:
![image](https://cloud.githubusercontent.com/assets/996070/15650072/65a41504-264c-11e6-8877-9b073ca859fd.png)

And, even after that:
![image](https://cloud.githubusercontent.com/assets/996070/15650095/877e8c0e-264c-11e6-8220-65d2376d2f67.png)

**Comment by benweet** [comment]
In the v5 all your `[^whatever]` footnotes will be merged into one footnote, which is the expected behavior I think. You have to use different names for your footnotes to have them separated.
