### ISSUE TITLE
markdown render error.

### ISSUE THREAD

**Issue by tiany** [benweet/stackedit#993]
when render the following markdown,  the result is not correct. Is there anything I missed?

``````
1. list-item

    ```python
    #test code
    print('hello')
    ```
``````

result preview(two extra blank line) :  
![](http://ww2.sinaimg.cn/large/4d1782b1gw1f4gxfzz23pj207v051749.jpg)

correct result:
1. list-item
   
   ``` python
   #test code
   print('hello')
   ```

**Comment by benweet** [comment]
Please open a new ticket if you still have the problem with the v5.

**Comment by tiany** [comment]
It works now, thanks a lot.
