### ISSUE TITLE
Error for wordpress publish

### ISSUE THREAD

**Issue by aeuveritas** [benweet/stackedit#996]
I use StakcEdit for Wordpress.
To make a post similar to StakcEdit, I publish markdown as html.
However, it has a difference for a quotation symbol.

The below image will help you understand.
http://googledrive.com/host/0B78hzfPX0FeNUnZ6dkcyd2VnUkE

In StakcEdit , the quotation symbol is the same as 16's.
However, I publish a post to Wordpressas html,
the quotation symbol is changed to 15's.

For StakcEdit , only 16's quotation symbol works well for code snippet.

Is it possible to make them same?

**Comment by benweet** [comment]
Not reproduced. Please open a new ticket if it's not fixed in the v5.
