### ISSUE TITLE
Creating a new document inside a folder?

### ISSUE THREAD

**Issue by geckolinux** [benweet/stackedit#998]
Hello,

Stackedit is really nice, but I'm having trouble with creating documents in folders. It appears that new documents are always created at the root, and then I have to move them into the correct folder. Is there a way to create documents directly inside a folder?

Thanks a lot!

**Comment by EnCey** [comment]
+1 wondering the same

**Comment by ShylaThompson** [comment]
I can publish to a folder just fine using a file path like this:  folder-name/file-name.md. Where the "folder-name" folder is a folder at the root of the repo. 

I cannot publish to a folder nested within a folder though. I attempted to change the path to be: folder-name/nested-folder/file-name.md, thinking that this would publish the file into the nested folder, but instead, it created a new folder at the root level named "folder-name/nested-folder".

**Comment by benweet** [comment]
Should be better with the v5.

**Comment by geckolinux** [comment]
Wow, fantastic, I'm really glad to see the continued development of StackEdit.
